// Generated by gen-data.mjs from real UAT.md files (+ one labelled synthetic) — do not edit.
window.UAT_DOCS = {
 "syn": {
  "key": "syn",
  "label": "synthetic (testing)",
  "synthetic": true,
  "file": "~/labelore/.planning/sketches/015-uat-page/synthetic-testing-UAT.md",
  "project": "labelore",
  "fm": {
   "status": "testing",
   "phase": "03-file-browsing",
   "source": "[03-01-SUMMARY.md, 03-02-SUMMARY.md, 03-VERIFICATION.md]",
   "started": "2026-07-21T09:12:00Z",
   "updated": "2026-07-21T10:47:31Z"
  },
  "current": {
   "number": "5",
   "name": "Browsing a genuinely unreachable tier",
   "expected": "Unplug the Vault drive (or stop its mount), then open /browse/vault. The pane shows\n\"Vault is unreachable right now — retry.\" with a Retry button, the tier switcher stays\nusable, and the dot beside Vault turns muted grey, not red. Plug it back in and press\nRetry: the listing returns without a page reload.",
   "awaiting": "user response",
   "fromSection": "Current Test"
  },
  "currentLine": null,
  "tests": [
   {
    "n": 1,
    "name": "Deep-link / refresh / back-button navigation (D-01/D-02)",
    "result": "issue",
    "resultRaw": "issue",
    "fields": [
     {
      "key": "expected",
      "value": "Open /browse/stage/projects/2026, refresh, then use Back twice. Each step lands on the same folder it showed before, the breadcrumb matches the URL, and the tier switcher keeps Stage selected."
     },
     {
      "key": "result",
      "value": "issue"
     },
     {
      "key": "reported",
      "value": "Refresh works but Back from a subfolder jumps straight to /browse, skipping the parent folder"
     },
     {
      "key": "severity",
      "value": "major"
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "Sort-header clicks + \"Show hidden files\" toggle (D-05/D-08)",
    "result": "issue",
    "resultRaw": "issue",
    "fields": [
     {
      "key": "expected",
      "value": "Click Name, Size and Modified headers in turn; folders stay first and the arrow shows the direction. Toggle \"Show hidden files\" and dotfiles appear without the scroll position jumping."
     },
     {
      "key": "result",
      "value": "issue"
     },
     {
      "key": "reported",
      "value": "the size column sorts 1.2 GB below 900 MB"
     },
     {
      "key": "severity",
      "value": "minor"
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "Real end-to-end download + oversized LAN-path handoff (D-10/D-11)",
    "result": "blocked",
    "resultRaw": "blocked",
    "fields": [
     {
      "key": "expected",
      "value": "Download a 40 MB file from Stage and confirm the checksum. Then select a 120 GB file: Download is disabled with \"Too large for the portal — 120 GB.\" and a copyable LAN path."
     },
     {
      "key": "result",
      "value": "blocked"
     },
     {
      "key": "blocked_by",
      "value": "third-party"
     },
     {
      "key": "reason",
      "value": "Cloudflare tunnel is rate-limiting large downloads this morning; retry after the window resets"
     }
    ],
    "lead": ""
   },
   {
    "n": 4,
    "name": "Cloud listing timeout (D-14)",
    "result": "skipped",
    "resultRaw": "skipped",
    "fields": [
     {
      "key": "expected",
      "value": "With the rclone remote throttled to 1 KB/s, open /browse/cloud. After 10 s the pane shows \"Cloud listing timed out — retry.\" and Retry re-attempts without a reload."
     },
     {
      "key": "result",
      "value": "skipped"
     },
     {
      "key": "reason",
      "value": "No throttling proxy set up on this host yet"
     }
    ],
    "lead": ""
   },
   {
    "n": 5,
    "name": "Browsing a genuinely unreachable tier",
    "result": "pending",
    "resultRaw": "[pending]",
    "fields": [
     {
      "key": "expected",
      "value": "The pane shows the unreachable copy with Retry, the switcher stays usable, the dot turns muted grey, and Retry recovers once the drive is back."
     },
     {
      "key": "result",
      "value": "[pending]"
     }
    ],
    "lead": ""
   },
   {
    "n": 6,
    "name": "10,000-entry folder scroll performance (D-07)",
    "result": "pending",
    "resultRaw": "[pending]",
    "fields": [
     {
      "key": "expected",
      "value": "Open the archive folder with 10,000 entries. Scrolling stays smooth at 60 fps and the row count matches `ls | wc -l`."
     },
     {
      "key": "result",
      "value": "[pending]"
     }
    ],
    "lead": ""
   },
   {
    "n": 7,
    "name": "Copy SMB path affordance (D-11)",
    "result": "pending",
    "resultRaw": "[pending]",
    "fields": [
     {
      "key": "expected",
      "value": "Click \"Copy path\" beside an oversized file; the label swaps to \"Copied\" for ~2 s and the clipboard holds the full \\\\cinedise path."
     },
     {
      "key": "result",
      "value": "[pending]"
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "7",
   "passed": "0",
   "issues": "2",
   "pending": "3",
   "skipped": "1",
   "blocked": "1"
  },
  "gaps": {
   "items": [
    {
     "truth": "Back from a subfolder returns to the parent folder, not the tier root",
     "status": "failed",
     "reason": "User reported: Refresh works but Back from a subfolder jumps straight to /browse, skipping the parent folder",
     "severity": "major",
     "test": "1",
     "root_cause": "browse-pane.tsx navigates with router.replace() on folder open, so each drill-down overwrites the history entry instead of pushing a new one",
     "artifacts": [
      {
       "path": "frontend/components/browse-pane.tsx",
       "issue": "line 88 uses router.replace for folder navigation"
      },
      {
       "path": "frontend/lib/use-browse.ts",
       "issue": "openFolder() mirrors the replace call into the query cache key"
      }
     ],
     "missing": [
      "Use router.push for folder navigation; keep replace only for sort/hidden-toggle query changes",
      "Add an e2e step: drill two levels, Back twice, assert each parent"
     ],
     "debug_session": ".planning/debug/back-skips-parent.md"
    },
    {
     "truth": "Sorting by Size orders files by byte size",
     "status": "failed",
     "reason": "User reported: the size column sorts 1.2 GB below 900 MB",
     "severity": "minor",
     "test": "2",
     "root_cause": "",
     "artifacts": [],
     "missing": [],
     "debug_session": ""
    }
   ],
   "prose": null
  },
  "gapsTitle": "Gaps",
  "extra": []
 },
 "sp103": {
  "key": "sp103",
  "label": "sp v1.0/03 (gaps)",
  "synthetic": false,
  "file": "~/studio-portal/.planning/milestones/v1.0-phases/03-file-browsing/03-UAT.md",
  "project": "studio-portal",
  "fm": {
   "status": "complete",
   "phase": "03-file-browsing",
   "source": "[03-VERIFICATION.md]",
   "started": "2026-07-21T00:00:00.000Z",
   "updated": "2026-07-22T00:20:00.000Z"
  },
  "current": null,
  "currentLine": "testing complete",
  "tests": [
   {
    "n": 1,
    "name": "Deep-link / refresh / back-button navigation (D-01/D-02)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Open /browse, drill into a folder, click a breadcrumb ancestor to go back up, then refresh the page mid-folder. Single-pane drill-down replaces the listing; the breadcrumb walks back up; a hard refresh and the browser back button both land on the same folder."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "note",
      "value": "Passed after three deployed fixes: G-03-1 (tier-root route), G-03-2 (space double-encode), G-03-3 (cloud '.'-root). Verified live on prod across all four tiers incl. cloud."
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "Sort-header clicks + \"Show hidden files\" toggle (D-05/D-08)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Click the Name/Size/Modified column headers to re-sort, and toggle \"Show hidden files\". Sort direction toggles per click; folders always stay grouped first regardless of sort column/direction; hidden dotfiles/cruft are hidden by default and reveal on toggle — no network re-fetch on either action."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "Real end-to-end download + oversized LAN-path handoff (D-10/D-11)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Download a small in-cap local file end to end; then attempt to download a file over max_download_bytes. The in-cap file streams and saves via the browser's native download handling. The oversized file shows a DISABLED Download button, \"Too large for the portal — {size}.\", and a copyable \"\\\\cinedise\\{tier}\\{path}\" LAN path whose \"Copy path\" button swaps to \"Copied\" for ~2s. (Server-side enforcement already proven by backend/tests/download_ticket_scope.rs.)"
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "note",
      "value": "Passed after G-03-4 (Cloudflare Access OPTIONS-preflight bypass) and G-03-5 (Content-Disposition filename). Verified on prod: small file streams and saves with its real name+extension; ~750MB oversized file shows the disabled button + 'Too large' + copyable LAN path."
     }
    ],
    "lead": ""
   },
   {
    "n": 4,
    "name": "Browsing a genuinely unreachable tier (D-15)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Unplug/disconnect one local tier (or otherwise make it genuinely unreachable) and browse into it from the tier switcher. Navigation is not blocked by the switcher's health dot; the listing pane shows the in-pane \"{Tier} is unreachable right now — retry.\" Alert with a working Retry button."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "note",
      "value": "Initially failed (empty-folder copy on a downed tier). Fixed via G-03-6 (503 tier_unreachable carve-out). Re-verified on prod: with /mnt/archive unmounted, browsing archive showed the 'unreachable — retry' alert; service logs confirm 503 responses during the unmount window (00:08:55–58). Host umount does propagate into the service mount namespace, so the mountinfo check fires as intended."
     }
    ],
    "lead": ""
   },
   {
    "n": 5,
    "name": "Breadcrumb horizontal-scroll overflow on a deep path",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "View the breadcrumb on a deep folder path in a narrow viewport. The breadcrumb row scrolls horizontally; the listing below never shifts or reflows."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   },
   {
    "n": 6,
    "name": "Secrets-outside-tier-roots filesystem-layout check (ACCESS-05 Manual-Only companion)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "On the production host, confirm rclone.conf and any SSH keys used by the tier probers/download handlers live physically outside all four configured tier roots (/mnt/stage, /mnt/vault, /mnt/archive, and the cloud remote's local config dir), so a successful browse/download of a tier root can never expose them. This is 03-VALIDATION.md's documented Manual-Only check (status: draft, not yet signed off) — the most important item to confirm."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "note",
      "value": "Verified on prod host: rclone.conf at /opt/cinedise-portal/data/rclone.conf (0600, outside all tier roots). Tier roots are distinct /mnt devices (stage=LVM, vault=sda2, archive=sdc2). Scanned /mnt/{stage,vault,archive} to depth 6 for rclone.conf/*.pem/id_rsa*/*.key/authorized_keys/.ssh/*.env/.netrc — zero hits. Phase-3 handlers use rclone (config in /opt) + cap-std (no keys); ProtectHome=true walls off ~/.ssh. Cloud tier browses the Drive remote, never the local config."
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "6",
   "passed": "6",
   "issues": "0",
   "pending": "0",
   "skipped": "0",
   "blocked": "0"
  },
  "gaps": {
   "items": [
    {
     "gap_id": "G-03-1",
     "truth": "Opening /browse (or any tier root) lists that tier's top-level entries",
     "status": "resolved",
     "resolved_at": "2026-07-21",
     "resolved_by": "Test 1 pass on prod (all four tier roots list)",
     "reason": "User reported: 'Couldn't load this folder — check the path and try again.' for all 4 tiers. This is the frontend's notFound state (browse-table.tsx:167) = backend returned 404 at every tier root.",
     "severity": "blocker",
     "test": "1",
     "root_cause": "No route serves a tier ROOT. Only /api/browse/{tier}/{*path} exists; the wildcard never matches an empty final segment. use-browse.ts:117 requests the root as path '.', producing /api/browse/{tier}/. — HTTP clients/proxies (browser, Cloudflare, hyper) normalize the '.' dot-segment away to /api/browse/{tier}/ which matches no route -> 404. Verified: `curl /api/browse/stage/.` -> 404 (normalized), `curl --path-as-is /api/browse/stage/.` -> 401 (route matches). Backend unit tests pass '.' directly to the handler, bypassing HTTP normalization, so this never surfaced pre-deploy.",
     "artifacts": [
      {
       "path": "backend/src/lib.rs:82",
       "issue": "Only /api/browse/{tier}/{*path} registered; no tier-root route"
      },
      {
       "path": "frontend/lib/use-browse.ts:117",
       "issue": "Root requested as path '.', which URL normalization strips before it reaches the wildcard route"
      }
     ],
     "missing": [
      "backend: add .route(\\\"/api/browse/{tier}\\\", get(browse_root_handler)) mapping to path '.'",
      "frontend: request tier root as /api/browse/{tier} (drop the '/.') when path is empty"
     ],
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Direct fix. backend/src/lib.rs + api/browse.rs: dedicated /api/browse/{tier} root route via browse_root_handler sharing a new list_tier() helper. frontend/lib/use-browse.ts: empty path targets /api/browse/{tier} directly (no '.'). New HTTP-level regression test backend/tests/browse_tier_root.rs drives the real router through reqwest (normalizes dot-segments like a browser). Full suite green: 228 lib + all integration tests. Backend+frontend redeployed to prod. Awaiting user re-verification before marking resolved."
    },
    {
     "gap_id": "G-03-2",
     "truth": "Drilling into a folder whose name contains a space lists its contents",
     "status": "resolved",
     "resolved_at": "2026-07-21",
     "resolved_by": "Test 1 pass on prod (space-named folders open)",
     "reason": "User reported (during Test 1 re-verify, after G-03-1 fixed): 'Couldn't load this folder — check the path and try again.' for any directory name with spaces.",
     "severity": "major",
     "test": "1",
     "root_cause": "Frontend double-encoding. Next 16's client-side useParams() returns URL dynamic segments still percent-encoded ('My%20Videos'), unlike the Server Component params prop. app/browse/[tier]/[[...path]]/page.tsx built currentPath from those raw segments; use-browse.ts then encodeURI'd again -> 'My%2520Videos'. Backend decodes exactly once -> looks up literal 'My%20Videos' -> 404. Backend decoding proven correct by new HTTP test (a_folder_name_with_spaces_lists_over_real_http passes: GET /api/browse/stage/My%20Videos -> 200), so the fault was purely the frontend's extra encode.",
     "artifacts": [
      {
       "path": "frontend/app/browse/[tier]/[[...path]]/page.tsx",
       "issue": "segments taken raw from useParams() (percent-encoded in Next 16), then re-encoded downstream -> double-encode"
      }
     ],
     "missing": [
      "frontend: decode each useParams segment at the source before it feeds currentPath / breadcrumb / download-path / child URLs"
     ],
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Direct fix. page.tsx: decodeSegment() (guarded decodeURIComponent, safe no-op on unescaped input) mapped over (params.path ?? []) so the component works in human-readable names and the single downstream encode is correct. Backend unchanged (already decodes once). Backend regression test a_folder_name_with_spaces_lists_over_real_http added. tsc clean, eslint 0 errors. Frontend redeployed to prod. Awaiting user re-verification."
    },
    {
     "gap_id": "G-03-3",
     "truth": "Browsing the cloud tier root lists its top-level Drive folders",
     "status": "resolved",
     "resolved_at": "2026-07-21",
     "resolved_by": "Test 1 pass on prod (cloud tier lists 21-entry root)",
     "reason": "User reported (during Test 1 re-verify): cloud tier shows 'Couldn't load this folder — check the path and try again.' while stage/vault/archive work. Backend log: rclone lsjson exited code=3 'error listing: directory not found'. NOT a config/auth issue — rclone.conf is provisioned and the remote (cinedise:) resolves; the PATH was wrong.",
     "severity": "major",
     "test": "1",
     "root_cause": "Same '.' root-sentinel class as G-03-1/2, in the cloud arm. browse_root_handler passes '.' as the tier root. scope::resolve_cloud rejected '..' but let a bare '.' through as the literal subpath; cloud.rs build_lsjson_command assembles format!(\\\"{remote}{subpath}\\\") = 'cinedise:.'. rclone reads ':.' as a directory literally named '.' -> 'directory not found' -> Failed(Unreachable) -> collapses to generic 404 (reject-identically). cap-std absorbs '.' as root for local tiers; the lexical cloud arm never did. Missed pre-deploy because scope unit tests never asserted the '.'-root case for cloud, and 03-VERIFICATION.md Req 1 ('browse ... cloud') was marked VERIFIED on unit tests + npm build, never a real end-to-end cloud-root browse.",
     "artifacts": [
      {
       "path": "backend/src/tiers/scope.rs",
       "issue": "resolve_cloud passed a bare '.' through as subpath instead of normalizing it to the empty (root) subpath"
      },
      {
       "path": "backend/src/tiers/browse/cloud.rs",
       "issue": "build_lsjson_command assembles remote+subpath verbatim -> 'cinedise:.' for the '.' root"
      }
     ],
     "missing": [
      "backend: resolve_cloud must drop '.' segments so the root sentinel yields an empty subpath (-> 'remote:' root); reject unchanged for '..'/absolute/nul/empty-segment"
     ],
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Direct fix. scope.rs resolve_cloud: build subpath from meaningful segments only, dropping '.' (root sentinel -> empty subpath -> argv 'cinedise:'); '..'/empty-segment still Rejected. New unit test cloud_resolve_maps_the_dot_root_sentinel_to_an_empty_subpath (+ 'projects/./2026' -> 'projects/2026'). Backend-only change; frontend unchanged. Full suite green: 229 lib + all integration. Backend rebuilt; awaiting host redeploy + user re-verification. NOTE: also exposes a UX gap — a cloud reachability/listing failure collapses to notFound ('check the path') rather than the unreachable/timeout state; logged for follow-up, not fixed here."
    },
    {
     "gap_id": "G-03-4",
     "truth": "Clicking Download mints a ticket and the file streams (or an oversized file shows the 'Too large' + LAN-path affordance)",
     "status": "resolved",
     "resolved_at": "2026-07-21",
     "resolved_by": "Test 3 pass on prod (download works after CF Access preflight bypass)",
     "reason": "User reported: 'Couldn't get a download link — try again.' for two files. File names having spaces was a coincidence — every JSON POST is affected.",
     "severity": "blocker",
     "test": "3",
     "root_cause": "NOT a phase-3 code bug — a Cloudflare Access config gap for cross-origin POST. POST /api/dl-ticket sends Content-Type: application/json, which forces a CORS preflight OPTIONS. Browsers send preflight requests WITHOUT cookies by design, so Cloudflare Access 403s the OPTIONS before it reaches the backend (verified: `curl -X OPTIONS https://api.cinedise.com/api/dl-ticket -H 'Origin: https://studio.cinedise.com' -H 'Access-Control-Request-Method: POST'` -> HTTP 403, server: cloudflare, HTML body; zero backend logs for the request). Simple browse GETs skip preflight so they work. This is the exact split-origin failure mode STACK.md predicted (line 86). Also breaks POST /api/ws-ticket -> the tier health socket/dots on prod. Backend CorsLayer is correct but never consulted because CF Access intercepts OPTIONS first.",
     "artifacts": [
      {
       "path": "Cloudflare Access application (api.cinedise.com)",
       "issue": "No CORS settings on the Access app, so cookie-less OPTIONS preflights are 403'd instead of being answered by CF"
      },
      {
       "path": "frontend/components/download-affordance.tsx:79-84",
       "issue": "application/json POST forces a preflight (correct API design; the failure is upstream at CF Access)"
      }
     ],
     "missing": [
      "PRIMARY (infra): configure CORS on the api.cinedise.com Cloudflare Access application — allow origin https://studio.cinedise.com, methods incl. OPTIONS/POST, allow header content-type, allow credentials; CF then answers the preflight. Fixes downloads AND the WS health socket. Keeps the clean JSON contract.",
      "ALT (code workaround): send the mint POSTs (dl-ticket, ws-ticket) as a CORS-safelisted Content-Type (text/plain) to skip preflight; backend accepts the body without requiring application/json. Sidesteps CF entirely but weakens the API contract."
     ],
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Infra fix (no code change). Enabled options_preflight_bypass=true on the 'Cinedise Portal' Cloudflare Access application (id 08b85a89-af82-4a34-ab39-f56f86380f3a, account 52f21b21…) via the CF API (read-modify-write PUT; PATCH not allowed for the token scheme). Now CF Access forwards OPTIONS preflights to the origin, and the backend's existing tower-http CorsLayer answers them (single source of CORS headers — no duplicate ACAO). The app is multi-domain (studio.cinedise.com + api.cinedise.com), which is why credentialed GETs already worked; only the preflight was blocked. Verified from host: OPTIONS https://api.cinedise.com/api/dl-ticket -> HTTP 200 with access-control-allow-origin: https://studio.cinedise.com + allow-credentials: true (was 403 cloudflare). ws-ticket preflight also 200. Policy ('Allow studio owner' -> cinedisestudio@gmail.com) and both domains preserved (backup at scratchpad/cf-app-backup.json). CONFIRMED by user re-test: oversized (~750MB) file correctly showed the LAN-path affordance, and small file downloaded — so mint+stream+oversized paths all work now. Remaining sub-issue split into G-03-5 (filename)."
    },
    {
     "gap_id": "G-03-5",
     "truth": "A downloaded file is saved under its real name and extension",
     "status": "resolved",
     "resolved_at": "2026-07-21",
     "resolved_by": "Test 3 pass on prod (file saved with real name + .mp4)",
     "reason": "User reported (Test 3 re-test, after G-03-4 fixed): downloading '0_Stylish_Design_1920x1080 - Tutorial Video.mp4' saved a file named '91b4ffb9...' (the ticket hex) with no extension.",
     "severity": "major",
     "test": "3",
     "root_cause": "The serve responses (backend/src/download/mod.rs serve_local + serve_cloud) set Content-Type: application/octet-stream but NO Content-Disposition header. The serve URL is deliberately path-free (/dl/{ticket}, D-13), so with no Content-Disposition the browser names the saved file after the URL's last segment = the opaque ticket hex, extensionless. Never surfaced pre-deploy: download tests asserted status + streamed bytes + referrer-policy, but not the saved filename.",
     "artifacts": [
      {
       "path": "backend/src/download/mod.rs:161",
       "issue": "serve_local sets no Content-Disposition"
      },
      {
       "path": "backend/src/download/mod.rs:212",
       "issue": "serve_cloud sets no Content-Disposition"
      }
     ],
     "missing": [
      "backend: emit Content-Disposition: attachment; filename=... (RFC 6266 + RFC 5987 filename* for spaces/unicode) using the ticket's stored basename, on both serve arms"
     ],
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Direct fix. download/mod.rs: new content_disposition_attachment() (RFC 6266 ASCII filename= fallback + RFC 5987 filename*=UTF-8'' extended form; control chars neutralized = header-injection defense). Basename derived from the ticket's stored path (never a URL segment) in download_handler and passed to serve_local/serve_cloud, both of which now emit the header. Unit test content_disposition_encodes_spaces_and_unicode_losslessly_with_an_ascii_fallback (incl. the exact reported filename, café.mov, and a CR/LF/quote injection case) + header assertion added to a_valid_scoped_ticket_streams_the_real_file. Backend-only. Full suite green: 230 lib + all integration. Backend rebuilt; awaiting host redeploy + user re-verification."
    },
    {
     "gap_id": "G-03-6",
     "truth": "Browsing a genuinely unreachable local tier shows the '{Tier} is unreachable right now — retry' alert, not a misleading empty-folder state",
     "status": "resolved",
     "resolved_at": "2026-07-22",
     "resolved_by": "Test 4 pass on prod; service logged 503 tier_unreachable during the archive unmount window — the namespace caveat is settled (host umount propagates to the service ns, mountinfo check fires).",
     "reason": "User unmounted /mnt/archive; browsing archive rendered the empty-folder copy ('This folder is empty. Nothing here yet — files added by other members will show up on refresh.') instead of the D-15 unreachable alert. Especially harmful here: archive is the SMART-failing drive being evacuated, so 'files will show up on refresh' is exactly the wrong signal when the drive is actually gone.",
     "severity": "major",
     "test": "4",
     "root_cause": "The browse path never checks mount liveness. An unmounted mountpoint (/mnt/archive) still exists as an empty, readable directory, so list_local's read_dir succeeds and returns [] -> 200 OK empty -> frontend renders the empty state. The frontend's 'unreachable' state only fires on a fetch throw or a non-403/404/504 status, which the backend never emits for a downed local tier (BrowseError::Unreachable itself maps to 404 -> notFound). The mountinfo liveness detector EXISTS (tiers/local.rs read_mount_table + mount_entry, pub) but is used only by the health prober, not the browse path. Consistent with the module's own doc: reachability is explicitly NOT a security-sensitive distinction (permission-denied=403, cloud-timeout=504 are already carve-outs) — so tier-unreachable collapsing to 404 is the oversight, not intended.",
     "artifacts": [
      {
       "path": "backend/src/api/browse.rs",
       "issue": "list_tier's Local arm lists the directory without first checking whether the tier root is a live mount"
      },
      {
       "path": "backend/src/tiers/browse/local.rs",
       "issue": "list_local returns [] for an unmounted-but-present mountpoint (indistinguishable from a genuinely empty folder)"
      }
     ],
     "missing": [
      "backend: in the browse Local arm, check mountinfo liveness (reuse tiers::local::read_mount_table + mount_entry) for mount-backed tier roots; when not mounted, return a distinct 503 {error: tier_unreachable} carve-out (analogous to 403/504). Frontend already maps a non-403/404/504 status -> 'unreachable', so NO frontend change needed."
     ],
     "design_note": "Non-trivial vs the other gaps: the mountinfo check must NOT fire for the test suite's /tmp scratch-dir tier roots (they are not real mounts). Needs a 'this tier root is mount-backed' discriminator — either a per-tier config flag (~20 TierConfig::Local sites) or a pragmatic /mnt-rooted heuristic. Pre-existing design gap, not a regression from this session.",
     "debug_session": "",
     "fix_deployed": "2026-07-21",
     "fix": "Direct fix (backend-only, zero config churn). api/browse.rs: list_tier's Local arm now calls local_tier_unreachable(mount_path) before listing; when true, returns a distinct 503 {error: tier_unreachable} (new carve-out alongside 403/504). Discriminator tier_unreachable_from_table(mount_path, table): true only when the path is under /mnt (component-wise) AND absent from /proc/self/mountinfo — reuses tiers::local::{read_mount_table, mount_entry}. The /mnt gate is safe+zero-churn: production tier roots are compile-time /mnt constants never env-overridable (from_env only touches binary paths + cloud remote), while the test suite always uses /tmp scratch dirs (so scratch-dir tests stay green — verified, no existing test broke). Fails OPEN on a mountinfo read error. Frontend unchanged (already maps non-403/404/504 -> unreachable). New fixture test tier_unreachable_only_fires_for_a_downed_mnt_root_never_a_scratch_dir. Full suite green: 231 lib + all integration. CAVEAT TO VERIFY: the service runs in a systemd mount namespace with /mnt/archive bind-mounted (ReadWritePaths); must confirm a host umount removes /mnt/archive from the SERVICE's /proc/self/mountinfo (else the check won't fire). The health prober relies on the same signal and is documented to detect unmounts, so expected to work — pending live re-verification (unmount archive again + browse)."
    }
   ],
   "prose": null
  },
  "gapsTitle": "Gaps",
  "extra": []
 },
 "sp3": {
  "key": "sp3",
  "label": "sp P3 (reverified)",
  "synthetic": false,
  "file": "~/studio-portal/.planning/phases/03-account-administration-session-control/03-UAT.md",
  "project": "studio-portal",
  "fm": {
   "status": "complete",
   "phase": "03-account-administration-session-control",
   "source": "[03-VERIFICATION.md]",
   "started": "2026-08-18T20:52:00Z",
   "updated": "2026-08-21T00:00:00Z"
  },
  "current": null,
  "currentLine": "testing complete",
  "tests": [
   {
    "n": 1,
    "name": "Account section — Disable/Enable badge, confirmation dialog, and the self-disable greyed-out state (03-01)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "On /admin/users/{id} for a member who is not you: Account section shows Active/Disabled badge, Disable account opens the confirmation naming the member and the three concrete effects, confirming flips the badge and button label; on your own account Disable account is greyed out with the stated reason. Both themes. Self-disable is visibly greyed out, never submit-then-fail."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "Login alerts — disabled-account copy vs. generic credential failure, and focus management (03-02)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Sign in at /login with a disabled member's correct password, then with a wrong password for the same handle. Correct password against a disabled account shows the plain disabled-account alert; wrong password renders the identical generic credential-failure alert used everywhere else. Password cleared, username retained, focus returned. Both themes."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "/audit — Accounts tab, decoded Detail column, interleaving, and long-value truncation (03-04)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "After a create, a disable, a role change, and a permission change: all four interleave with transfer rows in one table, the Accounts tab narrows to just those four, each row's Detail cell reads as a decoded sentence, a transfer row shows an em-dash, and a long Detail value truncates within its cell rather than widening the table. Both themes."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   },
   {
    "n": 4,
    "name": "Create-member and reset-password dialogs — inline validation and in-place list refresh (03-06)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "On /admin click New member: short-password and duplicate-handle captions appear inline (not page-level), a successful create closes the dialog and the new member appears in the list with no page reload. On /admin/users/{id} click Reset password: the session-stays-signed-in copy is present and success closes silently."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "reverified",
      "value": "2026-08-21 — re-tested after the G-03-4 fix (491f1da); clean mount and on-submit reveal both confirmed"
     },
     {
      "key": "prior_result",
      "value": "issue"
     },
     {
      "key": "prior_reported",
      "value": "pass - one note: the password is too short error appears before even a focus on the field"
     },
     {
      "key": "prior_severity",
      "value": "minor"
     }
    ],
    "lead": ""
   },
   {
    "n": 5,
    "name": "Sessions section and Danger Zone — row rendering, this-is-you scoping, typed-match delete gate (03-07)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "For a member signed in on two devices: Sessions lists two rows (device/address/relative-time); exactly one row on your own detail page carries the this-is-you badge even with two of your own sessions; disabling the member and reloading shows \"Not currently logged in.\"; the Danger zone has a destructive-toned heading and its delete confirmation only enables on an exact case-sensitive handle match (wrong-case stays disabled); layout holds at the narrowest supported viewport. Both themes."
     },
     {
      "key": "result",
      "value": "pass"
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "5",
   "passed": "5",
   "issues": "0",
   "pending": "0",
   "skipped": "0",
   "blocked": "0"
  },
  "gaps": {
   "items": [
    {
     "gap_id": "G-03-4",
     "truth": "Password-length validation on the create-member dialog surfaces only after the user has engaged the field, not on an untouched form",
     "status": "resolved",
     "resolved_by": "491f1da fix(03-06): reveal the password rule on submit, not on an untouched dialog",
     "resolved_at": "2026-08-21",
     "reverified_at": "2026-08-21",
     "reverify": "Test 4 — reopen New member and confirm the dialog mounts with no destructive caption (confirmed pass)",
     "reason": "User reported: pass - one note: the password is too short error appears before even a focus on the field",
     "severity": "minor",
     "test": "4",
     "root_cause": "create-member-dialog.tsx computes `ruleFailure` at render time (line 58) instead of inside the submit handler, so an untouched dialog mounts with password==\\\"\\\" -> validateNewPassword returns \\\"too-short\\\" -> the destructive caption and aria-invalid=true render before any interaction. The file's own comment (lines 54-57) claims validation 'fires on submit only', citing /change-password as precedent, but /change-password actually calls validateNewPassword INSIDE handleSubmit and stores the result in state. The dialog also gates submitDisabled on `ruleFailure !== undefined`, whereas the precedent gates on field emptiness -- the two diverge together, and the second is why the eager compute could not simply be moved without also changing the gate.",
     "artifacts": [
      {
       "path": "frontend/components/create-member-dialog.tsx",
       "issue": "line 58 derives ruleFailure at render; lines 163/166 and 183/185 consume it eagerly; line 59 gates submit on it"
      },
      {
       "path": "frontend/app/change-password/page.tsx",
       "issue": "the correct precedent -- validation inside handleSubmit (line 66), submit gated on emptiness (lines 55-56)"
      }
     ],
     "missing": [
      "Hold the rule failure in state; compute it only inside handleSubmit",
      "Gate submitDisabled on field emptiness, not on ruleFailure, so an on-submit reveal is reachable",
      "Clear the held failure when either password field changes, matching handleTakenCaption's reset",
      "Drive both captions and both aria-invalid flags from the held state, never the derived value"
     ],
     "debug_session": "diagnosed inline during verify-work -- single-file root cause, no debug agent spawned"
    }
   ],
   "prose": null
  },
  "gapsTitle": "Gaps",
  "extra": []
 },
 "sp1": {
  "key": "sp1",
  "label": "sp P1 (skips, notes)",
  "synthetic": false,
  "file": "~/studio-portal/.planning/phases/01-portal-owned-identity-sessions/01-UAT.md",
  "project": "studio-portal",
  "fm": {
   "status": "complete",
   "phase": "01-portal-owned-identity-sessions",
   "source": "[01-01-SUMMARY.md, 01-02-SUMMARY.md, 01-03-SUMMARY.md, 01-04-SUMMARY.md, 01-05-SUMMARY.md, 01-06-SUMMARY.md, 01-VERIFICATION.md]",
   "started": "2026-08-05T12:35:00Z",
   "updated": "2026-08-05T09:26:00Z"
  },
  "current": null,
  "currentLine": "testing complete",
  "tests": [
   {
    "n": 1,
    "name": "Cold start smoke test",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Stop `cinedise-portal` entirely, then start it from cold. It boots with no error,\nthe `0003_accounts_and_sessions.sql` migration applies (or is cleanly already-applied) with\nnothing logged as a failure, and an unauthenticated `GET /api/whoami` against the live origin\nreturns 401 `invalid session` — a real answer from a live process, not a connection refusal\nand not a 500."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "observed",
      "value": "2026-08-05T07:21:36Z. Operator ran `systemctl stop` then `systemctl start`. Genuine cold\nprocess — PID moved 1270071 → 1327104, service Active since 12:51:36 IST.\n\nBoot journal clean end to end, no warning-or-worse entries at any priority since boot:\n  boot-time job reconciliation complete resumed=0 interrupted=0 orphans_killed=0\n  listening on 127.0.0.1:8787\nThe `0003_accounts_and_sessions.sql` migration logged no error (already-applied path,\nwhich this test admits).\n\nLive answers against the cold process, all DB-backed, none a 500 or a refused connection:\n  GET  /api/whoami       → 401 invalid session\n  POST /api/login  (bogus handle) → 401   — users table queryable cold\n  GET  /api/browse/tier1 → 401            — auth seam intact cold\n\nCaveat: stop and start were run back-to-back, so the down state was never directly\nobserved. It does not weaken the result — the PID change plus a fresh boot sequence in\nthe journal is the cold boot this test asks for."
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "A signed-in session survives a genuine power cut",
    "result": "skipped",
    "resultRaw": "skipped",
    "fields": [
     {
      "key": "expected",
      "value": "Sign in to the portal and confirm you are on the browse view. Hard-power-cycle\nthe host — pull power or use the PDU, not `reboot` and not `systemctl stop`. When the box\nis back and `cinedise-portal` is active, reload the portal page in the *same* browser\nwithout clearing cookies. You must land on the browse view still signed in, with your\ndisplay name in the header. Being sent to `/login` is a failure.\n\nThis is a distinct fault class from what `session_durability.rs` already proves. That test\ncovers an ungraceful pool drop plus `init_pool` reopen — the process dying without closing\nSQLite cleanly. A real power cut additionally exercises the filesystem and disk cache losing\nwrites that were acknowledged but not yet physically flushed. The schema opens WAL with\n`synchronous=FULL` specifically so this holds, but that is a claim about the pragma, not an\nobservation of the hardware."
     },
     {
      "key": "source",
      "value": "01-01-SUMMARY.md D4 · 01-VERIFICATION.md human_verification · AUTH-06"
     },
     {
      "key": "result",
      "value": "skipped"
     },
     {
      "key": "reason",
      "value": "Waived by the operator on 2026-08-05, not observed. The physical power cycle was not\nperformed — host uptime confirms it: `uptime -s` = 2026-07-08 18:32:56, unbroken through\nthis session. Only `cinedise-portal` restarted (12:51:36), which is test 1, a different\nfault class.\n\nAccepted in place of the observation: the schema opens WAL with `synchronous=FULL`, and\n`backend/tests/session_durability.rs::a_session_survives_an_ungraceful_pool_drop_and_still_authenticates_after_reopen`\nproves survival of an ungraceful `Pool` drop plus `init_pool` reopen. That covers process\ndeath without a clean SQLite close; it does not cover the disk/filesystem losing writes\nthat were acknowledged but not yet physically flushed.\n\nAUTH-06's power-cut sub-case therefore remains unobserved by design, not by oversight —\nthe same disposition 01-VALIDATION.md's Manual-Only table already recorded (\"Open.\nDeliberately not performed — a hard power cycle on a host that moves footage was not\nworth the disruption at cutover\"). Re-open it with a pulled plug or the PDU if the\nguarantee ever needs to be evidence rather than argument."
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "Route inventory reviewed as a human checklist",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Read `01-ROUTE-INVENTORY.md` top to bottom as a checklist and confirm every Gate\nverdict is the one you actually want in production — not merely that the table is\ninternally consistent. `route_auth_coverage.rs` already proves the table's path set equals\n`build_router`'s and that session-gated rows enforce their gate; what it cannot judge is\nwhether `/api/login` is genuinely the only route that should be public, whether `/ws` and\n`/dl/{ticket}` being ticket-gated rather than session-gated is intended, and whether the\nthree must-change-exempt rows (`/api/logout`, `/api/change-password`, `/api/whoami`, and\nnothing else) are the right escape hatch — no wider."
     },
     {
      "key": "source",
      "value": "01-02-SUMMARY.md D9"
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "observed",
      "value": "Operator sign-off 2026-08-05, against a review cross-checking the table to `build_router`\nin `backend/src/lib.rs`:\n\n- All 17 rows match the registered path set exactly.\n- `MUST_CHANGE_EXEMPT_PATHS` (`backend/src/auth/mod.rs:38`) is\n  `[\"/api/whoami\", \"/api/change-password\", \"/api/logout\"]` — three paths, matching the\n  three \"Yes\" rows and no more.\n\n- `/api/login` is the sole public route, inside the rate-limited `credential_routes`\n  sub-router; `route_layer` (not `layer`) correctly keeps the governor off the outer\n  router's 404 fallback.\n\n- `/ws` and `/dl/{ticket}` genuinely take no `VerifiedIdentity` — correctly classed\n  ticket-gated rather than session-gated.\n\nRaised during review and consciously accepted by the operator, NOT logged as a gap:\nthe `AUTH_MODE=dev` guard (`backend/src/auth/mod.rs:197`) refuses to boot only when the\nbind is non-loopback. This host binds `127.0.0.1:8787` and is publicly exposed via\ncloudflared, which reaches it over loopback — so `AUTH_MODE=dev` in `portal.env` would\nboot without complaint and satisfy every session-gated row by injected identity, while\nthe tunnel kept serving the internet. Production is verifiably unaffected today:\nunauthenticated `GET /api/whoami` returns 401, which it would not under the dev bypass.\nNo route-coverage test can surface this — every verdict in the table stays correct while\nthe gate behind them is bypassed."
     }
    ],
    "lead": ""
   },
   {
    "n": 4,
    "name": "The route gate resolves all three outcomes end-to-end",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Against the live stack, confirm `proxy.ts` sends each case to exactly one place,\nbefore any app HTML renders:\n\n1. No cookie → request `/browse` → redirected to `/login`.\n2. Valid cookie, member flagged `must_change_password` → request `/browse` directly (not by\n following the sign-in flow) → redirected to `/change-password`, never the browse view.\n\n3. Valid cookie, no flag → request `/browse` → the real page.\n4. Valid cookie, backend stopped → request `/browse` → redirected to `/login` with the\n neutral connectivity notice, fail-closed. The app must never render.\n\nCases 1 and 4 were smoke-tested during 01-05 against a stopped backend. Case 2 as a\n*direct* redirect is the one that has never been observed — the 2026-08-05 walkthrough\nreached the change-password screen by signing in, which is a different path through the\ngate."
     },
     {
      "key": "source",
      "value": "01-05-SUMMARY.md D2 · AUTH-06"
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "scope",
      "value": "all four branches"
     },
     {
      "key": "observed",
      "value": "Branches 1-3, operator sign-off 2026-08-05:\n\n- Branch 1 (no cookie → `/login`) independently confirmed here:\n  `GET https://studio.cinedise.com/browse` → 307 → `https://studio.cinedise.com/login`.\n\n- Branches 2 and 3 (flagged `must_change_password` → `/change-password`; valid unflagged\n  cookie → the real page) attested by the operator against the live stack.\n\nBranch 4 (valid cookie + backend unreachable → `/login` with the neutral connectivity\nnotice, fail-closed) observed by the operator 2026-08-05 in a genuine stopped-backend\nwindow, corroborated by the unit journal:\n  14:54:02  Stopping cinedise-portal.service — Deactivated successfully\n  14:54:27  Started cinedise-portal.service   (25s down, PID → 1365985)\nThis is the combination 01-05's smoke test could not produce — that run proved the path\nagainst a stopped backend with no valid session cookie. With a real cookie present, the\ngate still fails closed rather than trusting a cookie it cannot validate, which is the\nactual T-01-28 contract."
     }
    ],
    "lead": ""
   },
   {
    "n": 5,
    "name": "The /login screen holds up visually and interactively",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Open `/login` in a browser and check it in both themes and at 390px wide:\n\n- Landing state is unfilled, with no validation shown before you submit.\n- Submit a wrong password: one fixed alert region appears, both inputs go `aria-invalid`,\nthe password field clears, the username stays, and focus returns. The message must be\ngeneric — nothing that reveals whether the account exists.\n\n- Trip the rate limiter: the countdown self-heals down to zero and never *reads* zero.\n- Arrive with the connectivity notice: it reads neutral, not destructive/alarming.\n- Hard-reload while signed out: no auth-loading flash — there is no client-side auth-loading\nstate anywhere by design.\n\nStructural checks (input caps, `aria-invalid` wiring, copy sourced from `LOGIN_COPY`, alert\nvariant selection, no artificial min-display timer) already pass as source greps. This is\nthe visual/interaction pass those greps explicitly deferred."
     },
     {
      "key": "source",
      "value": "01-05-SUMMARY.md D4"
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "observed",
      "value": "Operator browser observation, 2026-08-05 — both themes, 390px, wrong-password flow,\nrate-limit countdown, connectivity notice, hard-reload-while-signed-out.\n\nAttested, not independently reproducible from this environment: no browser and no\nPlaywright MCP in the verifying session, and the screen is served by Vercel rather than\nthis host, so no server-side signal exists that could corroborate or contradict it. The\nstructural half was already machine-proven by 01-05's source-grounded acceptance checks\n(input caps, `aria-invalid` wiring, copy sourced from `LOGIN_COPY`, alert-variant\nselection, no artificial min-display timer); this sign-off covers the visual and\ninteraction layer those checks explicitly deferred — chiefly that the rate-limit countdown\nnever *reads* zero, and that no auth-loading flash appears on hard reload, both of which\nare timing-sensitive and invisible to static analysis."
     }
    ],
    "lead": ""
   },
   {
    "n": 6,
    "name": "The authenticated header degrades toward signed-out when the backend is unreachable",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Sign in and confirm the header shows your display name and a log-out control.\nNow stop the backend while the page stays open, and interact with the app. The header must\ndegrade *toward* signed-out — it must not keep asserting a signed-in identity it can no\nlonger confirm, and it must not crash the view or hang on a spinner.\n\nThe signed-in half of this was observed in the 2026-08-05 operator walkthrough (sign-in →\nforced change → browse with name and log-out present). The degradation half never was."
     },
     {
      "key": "source",
      "value": "01-06-SUMMARY.md D2 · AUTH-03"
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "observed",
      "value": "Operator observation 2026-08-05, in the same stopped-backend window that closed test 4's\nbranch 4. Corroborated by the unit journal:\n  14:54:02  Stopping cinedise-portal.service — Deactivated successfully\n  14:54:27  Started cinedise-portal.service   (25s down, PID → 1365985)\n\nWith `/api/whoami` no longer answering, the authenticated header degraded toward\nsigned-out rather than continuing to assert an identity it could no longer confirm — no\ncrash of the view, no hang on a spinner.\n\nThe signed-in half was already covered by the 2026-08-05 operator walkthrough (sign-in →\nforced change → browse, with display name and log-out control present), and `npm run build`\nis clean with the browse route still ● SSG. Both halves of D2 are now observed."
     }
    ],
    "lead": ""
   },
   {
    "n": 7,
    "name": "Cf-Connecting-Ip reaches the origin through the production tunnel (OPEN-02)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Cf-Connecting-Ip is set by Cloudflare and survives this tunnel, carrying the real\nclient address, so the rate limiter's address axis keys on something real."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D7"
     },
     {
      "key": "resolved_by",
      "value": "01-06-SUMMARY.md D4 — limiter-as-oracle, 2026-08-05. The address-axis bucket for\nthis host's public address was exhausted via direct `127.0.0.1:8787` requests carrying an\nexplicit `cf-connecting-ip` (10 admitted, then 429); a subsequent request *through the tunnel*\nwith a fresh handle returned 429 + `retry-after: 29`. Only a key resolving to that same public\naddress lands in that bucket. Distinct handles throughout kept the handle axis from\nconfounding. Recorded PASS in 01-VALIDATION.md Manual-Only Verifications."
     },
     {
      "key": "caveat",
      "value": "The extractor falls back to `ConnectInfo<SocketAddr>` when the header is absent, which\nbehind a tunnel is always `127.0.0.1` — a future loss of the header collapses all callers into\none shared bucket silently rather than erroring. Recorded in `ops/README.md` § Connecting-IP\nfinding."
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "7",
   "passed": "6",
   "issues": "0",
   "pending": "0",
   "skipped": "1",
   "blocked": "0"
  },
  "gaps": {
   "items": [],
   "prose": null
  },
  "gapsTitle": "Gaps",
  "extra": [
   {
    "title": "Notes",
    "body": "**Unobserved fault windows carried out of this phase.** One remains. Nothing here failed;\nit is a thing nobody has watched happen.\n\n| Item | What would close it |\n|------|---------------------|\n| Test 2 — AUTH-06 power-cut sub-case | A pulled plug or PDU cycle with a signed-in session live |\n\nClosed during this session: test 4 branch 4 (proxy fail-closed under a *valid* cookie) and\ntest 6 (header degradation when `/api/whoami` stops answering) were both observed in a single\n25-second stopped-backend window at 14:54:02–14:54:27, exactly as anticipated.\n\n**SUMMARY hygiene.** `01-06-SUMMARY.md`'s coverage entry D2 declares `kind: build`, which is\nnot a valid verification kind (`unit`, `integration`, `e2e`, `automated_ui`,\n`manual_procedural`, `other`). `uat classify-coverage` therefore reports it as\n`validation_failed` and routes it to a human checkpoint by fail-safe rather than reading its\nevidence. It was carried as a human checkpoint here regardless, so nothing was dropped — but\nthe block should be corrected so the classifier reads it properly on any re-run.\n\n**Resolved during this session.** Test 7 (01-04 D7 / OPEN-02, whether `Cf-Connecting-Ip`\nsurvives the production tunnel) was auto-passed rather than presented: 01-06 D4's\nlimiter-as-oracle result already answered it empirically. See that test's `resolved_by`."
   }
  ]
 },
 "sp2": {
  "key": "sp2",
  "label": "sp P2 (off-template)",
  "synthetic": false,
  "file": "~/studio-portal/.planning/phases/02-roles-permission-enforcement/02-UAT.md",
  "project": "studio-portal",
  "fm": {
   "status": "passed",
   "phase": "02-roles-permission-enforcement",
   "source": "[02-VERIFICATION.md]",
   "started": "2026-08-09T15:28:12Z",
   "updated": "2026-08-09T15:46:15Z"
  },
  "current": {
   "number": "1 (resolved)",
   "name": "02-08 Task 5 steps 1-5 — the non-admin read-side surfaces, as `qa`",
   "expected": "Signed in as `qa` holding `read:stage` ONLY:\n1. On `/`, all four tier cards show capacity and health, but only Stage is\n   clickable. The other three look IDENTICAL to Stage apart from not responding\n   to click — no dimming, no lock icon, no badge, no opacity change, no cursor\n   change. Both light and dark themes.\n2. Reload `/` and watch first paint: cards must not start clickable and then\n   stop. Momentarily non-clickable then upgrading is correct; the reverse is a bug.\n3. Nav shows exactly Browse and Jobs. No gap, no greyed Audit, no Admin item.\n   Confirm at 390px wide too.\n4. Type `/browse/vault` directly: the denied panel renders inside the normal\n   browse chrome, the tier switcher stays present and usable, no breadcrumb, and\n   switching `/browse/stage` <-> `/browse/vault` produces no layout jump.\n5. Type `/audit` directly: a page-level denial, not a redirect and not a 404.",
   "awaiting": "none — operator approved 2026-08-09",
   "fromSection": "Resolution"
  },
  "currentLine": "none — all items resolved 2026-08-09T15:46:15Z",
  "tests": [
   {
    "n": 1,
    "name": "02-08 Task 5 steps 1-5 — non-admin read-side surfaces, as `qa`",
    "result": "pass",
    "resultRaw": "passed (operator-approved; partially corroborated)",
    "fields": [
     {
      "key": "expected",
      "value": "The five renders above, observed in a browser as a `read:stage`-only member."
     },
     {
      "key": "result",
      "value": "passed (operator-approved; partially corroborated)"
     },
     {
      "key": "note",
      "value": "RESOLVED 2026-08-09 by operator approval. Corroboration: a `qa` session was active\nat 15:44:27, ~2 minutes before approval — consistent with the sign-in these steps\nrequire, and unlike the earlier 02-08 approval which had no `qa` activity at all.\nLIMIT ON THAT CORROBORATION, stated plainly: `qa` held ZERO permissions before and\nafter this window. Steps 1-2 discriminate a LINKED Stage card from three NON-LINKED\nones, which requires `read:stage`. A grant -> test -> revoke cycle would satisfy that\nand leave no trace, because permission changes are not written to `audit_log` (the\nvery gap this phase deferred to ADMIN-06). So the permission state during the test is\nUNKNOWABLE from the record, in either direction. Steps 3-5 (two-item nav, /browse/vault\ndenial, /audit denial) hold with zero permissions and are unaffected by this limit.\nThis checkpoint was approved by the operator on 2026-08-09, but no `qa` HTTP\nrequest reached the backend in the approval window (session last_seen 13:54:24\nvs approval ~14:05+), so the approval is the only evidence for these five steps.\nCode inspection supports the claim — canRead/canViewAudit/canViewAdmin all\nfail closed to false on a null payload, and use-whoami.ts has no retry path that\ncould flip a card to linked — but that is not the same as observing the render.\nACTIONABLE: re-runnable in ~5 minutes. `qa` currently holds zero permissions;\ngrant `read:stage` (and nothing else) first."
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "ROLE-06 last-admin refusal — the frontend ALERT RENDER",
    "result": "pass",
    "resultRaw": "closed — structurally unprovable via the live API by design (operator decision, 2026-08-09)",
    "fields": [
     {
      "key": "expected",
      "value": "Button re-enables and the destructive alert `Can't demote — no other admin would remain.` appears above the Role section."
     },
     {
      "key": "result",
      "value": "closed — structurally unprovable via the live API by design (operator decision, 2026-08-09)"
     },
     {
      "key": "note",
      "value": "STRUCTURALLY UNREACHABLE through the HTTP API by a sequential (non-racing)\ndemote. store.rs computes is_demotion BEFORE the guards; the route requires an\nauthenticated enabled admin as actor, rule 1 forces actor != target, and\nis_demotion forces target to be an admin — so enabled_admin_count is always >= 2\nwhen rule 2 counts. Only a true race (actor demoted between auth check and\ntransaction) trips it.\nENFORCEMENT is proven: 15 demotion-guard tests pass, including\nstore::demoting_the_only_enabled_admin_is_refused_and_the_users_row_is_unchanged,\napi::admin::set_role_handler_refuses_the_last_admin_demotion_with_the_last_admin_marker,\nand backstage::demote_with_two_enabled_admins_succeeds_and_a_second_demote_of_the_remaining_admin_is_then_refused.\nSource path reviewed end to end: page.tsx:102 -> api/admin.rs:88 -> store.rs:241.\nOnly the RENDER is unobserved. Closing this properly needs a frontend test that\nmounts the component with a stubbed 409 `last_admin_refused` response — not a\nbrowser session. Recommend deferring to a test, not a manual step."
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "02-10 Task 5 step 2 — em-dash fallback for a missing display name",
    "result": "pass",
    "resultRaw": "closed on unit-level proof — operator decision, 2026-08-09: \"unit tests are enough\"",
    "fields": [
     {
      "key": "expected",
      "value": "A member row with no display name renders an em dash, not a blank cell and not the handle repeated."
     },
     {
      "key": "result",
      "value": "closed on unit-level proof — operator decision, 2026-08-09: \"unit tests are enough\""
     },
     {
      "key": "note",
      "value": "NOT VERIFIABLE against current prod data — both accounts carry display names and\n`backstage create` requires `--name`. Unit-level proof exists (admin-summary.ts's\ndisplayNameCell has dedicated em-dash cases, covered by the 101/101 frontend suite).\nClosing this needs either an account created with a blank display name (if the CLI\npermits it) or acceptance of the unit-level proof. Recommend the latter."
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "3",
   "passed": "1",
   "accepted": "2",
   "issues": "0",
   "pending": "0",
   "skipped": "0",
   "blocked": "0",
   "resolution": "Item 1 approved by the operator with partial session corroboration (see its note for\nthe exact limit). Items 2 and 3 accepted on automated proof rather than observation —\nneither is closable by a browser session, and both carry a concrete follow-up below."
  },
  "gaps": {
   "items": [
    {
     "prose": true,
     "title": null,
     "body": "**The ROLE-06 last-admin alert is unreachable BY DESIGN, not by omission.** Operator's\nreading, confirmed correct: D-17 rule 1 (self-demotion refused — \"You can't remove your\nown admin access — ask another admin.\") is precisely what makes rule 2 unreachable. You\ncan never demote yourself, so the last admin can only be demoted by someone else — and\nthat someone else must be an enabled admin too, making `enabled_admin_count >= 2`\nwhenever rule 2 counts. The two guards are mutually exclusive over the API surface.\nClosed as unprovable-by-live-testing rather than left open. Enforcement remains proven\nby 15 passing tests; the `page.tsx:102` render stays unexercised end to end.\nFORWARD-LOOKING RISK for Phase 3: the count is\n`role='admin' AND disabled_at IS NULL`. Nothing can set `disabled_at` today (verified:\nevery write site inserts NULL), so this is inert. Once Phase 3 adds account disabling,\ndemoting a DISABLED admin while one enabled admin remains yields count=1 and trips\n`LastAdminRefused` — refusing an operation that would not reduce the enabled-admin count\nat all. That is an over-refusal, and it is also the first path that makes the alert\nreachable in a browser. Re-check this guard when disabling lands."
    },
    {
     "prose": true,
     "title": null,
     "body": "**The em-dash display-name fallback is closed on unit proof** (operator decision) —\n`admin-summary.ts`'s `displayNameCell` cases, covered by the 101/101 frontend suite."
    },
    {
     "prose": true,
     "title": null,
     "body": "**Steps 1-2 of item 1 rest on an unverifiable permission state** (see item 1's note).\nIf the read-side denial surfaces are ever suspected, re-run them with `read:stage`\nexplicitly granted and confirmed before starting."
    },
    {
     "prose": true,
     "title": null,
     "body": "Out of scope for this phase but worth carrying forward: role and permission changes\nwrite nothing to `audit_log`. Confirmed by the verifier as a genuine non-gap for\nPhase 2 (ADMIN-06 owns it, mapped to Phase 3, and 02-CONTEXT.md recorded that split\nat planning time) — not a defect here, but it means there is currently no record of\nwho changed whose access."
    }
   ],
   "prose": "Carried forward as real, open follow-ups — accepted, not proven:"
  },
  "gapsTitle": "Gaps",
  "extra": []
 },
 "lb01": {
  "key": "lb01",
  "label": "labelore 01 (23 tests)",
  "synthetic": false,
  "file": "~/labelore/.planning/milestones/v1.0-phases/01-read-layer-domain-model/01-UAT.md",
  "project": "labelore",
  "fm": {
   "status": "complete",
   "phase": "01-read-layer-domain-model",
   "source": "[01-01-SUMMARY.md, 01-02-SUMMARY.md, 01-03-SUMMARY.md, 01-04-SUMMARY.md]",
   "started": "2026-09-09T13:50:00Z",
   "updated": "2026-09-09T14:25:00Z"
  },
  "current": null,
  "currentLine": "testing complete",
  "tests": [
   {
    "n": 1,
    "name": "Cold Start Smoke Test",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "From a clean state (no build cache, no prior snapshot output), a fresh `npm ci` followed by `npm run snapshot -- fixtures/dense --stable` boots with no errors and prints pure JSON to stdout that parses on the first try — no npm lifecycle banner, no warning preamble, no partial write."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "executed_by",
      "value": "claude (user delegated: \"can you try it yourself?\")"
     },
     {
      "key": "evidence",
      "value": "`rm -rf node_modules` (540M removed) then `npm ci` — exit 0, 3.8s, 515 packages, zero stdout/stderr output (.npmrc loglevel=silent holding).\n`npm run snapshot -- fixtures/dense --stable` — exit 0, stderr 0 bytes, stdout 512326 bytes beginning at byte 0 with `{` (no npm lifecycle banner).\nJSON.parse succeeded on the first try. loadStatus ok; 3 milestones (v1.0/v2.0/v3.0), 5 phases, 6 requirements, 2 quick tasks, 2 warnings.\nRe-ran and compared: byte-identical across runs (no partial write, deterministic).\nAgainst test/__golden__/dense.json: identical except one trailing newline the CLI adds to stdout — the golden suite compares JSON.stringify output, so this is expected, not drift."
     }
    ],
    "lead": ""
   },
   {
    "n": 2,
    "name": "Manual smoke test against the real `~/studio-portal`",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "`npm run snapshot -- ~/studio-portal --stable > /tmp/sp.json` exits 0; `loadStatus.status` is `ok`; the phase list contains both the live milestone's phases and the archived `v1.0` ones with the two \"Phase 1\" entries distinct; the warning list is short enough to read and every entry names a real problem rather than a routine unresolved identifier; the mention index shows a decision id appearing across several files with sensible excerpts. Then repeat with a relative path, a `~`-prefixed path, and a symlink to the same directory and confirm all four resolve to the same root."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "executed_by",
      "value": "claude (user delegated: \"can you try it yourself?\")"
     },
     {
      "key": "evidence",
      "value": "Exit 0, stderr 0 bytes, loadStatus ok.\nPhase-1 distinctness: v1.0/01 identity-persistence-foundation (archived) and v2.0/01\nportal-owned-identity-sessions (live) are two separate entries — the compound identity holds.\n9 phases total across v1.0 + v2.0; the 9th (v2.0 #5, roadmap-only) correctly carries\ndiskStatus=no_directory rather than being invented or dropped.\nWarnings: 2, both genuine. Independently re-parsed both files with Python's yaml —\n01-06-SUMMARY.md fails on an unquoted backtick (line 12), 03-07-SUMMARY.md on an unquoted\n@-scoped package name (line 12). Neither is a routine unresolved identifier; both are real\nmalformed YAML. Salvage claim verified: frontmatter {} and body intact (12174 / 7446 bytes).\nMention index: 653 scheme-qualified ids (plan 494, requirement 121, decision 28, phase 10),\n9280 mentions. decision:D-07 spans 52 files with line numbers and readable context.\nAll 9280 excerpts contain their own id (0 misses).\nPath shapes: absolute, relative, ~-prefixed and symlink all exit 0 and produce byte-identical\noutput. Canonicalization proven directly — a symlink to a non-planning dir echoes the real\ntarget path (/tmp/no-planning-real), not the link."
     },
     {
      "key": "covers",
      "value": "[01-01 D8, 01-03 D7, 01-04 D6]"
     },
     {
      "key": "why_human",
      "value": "D-04 scopes this as a manual smoke target with zero committed assertions — no committed test may depend on `~/studio-portal`. The qualitative judgment (\"is the warning list short enough to read\", \"are the excerpts sensible\") needs a human."
     }
    ],
    "lead": ""
   },
   {
    "n": 3,
    "name": "Dense fixture — healthy tree",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The `fixtures/dense` snapshot shows three milestones (v1.0/v2.0 archived, v3.0 active) with an archived/live phase-01 collision spanning all three kept as distinct entries, the full spread of unfamiliar/invented artifact types present as `kind: \"unknown\"` rather than dropped, and `config.json`'s deliberately-unfamiliar keys round-tripping unchanged."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "executed_by",
      "value": "claude"
     },
     {
      "key": "evidence",
      "value": "Three milestones present with correct archived flags: v1.0(true), v2.0(true), v3.0(false).\nPhase-01 collision across all three kept distinct: v1.0/bootstrap, v2.0/legacy-ingest,\nv3.0/identity-slice — three separate entries, three separate dirPaths.\nNo file dropped: 53 files on disk, 52 artifacts in the snapshot, 1 deliberate exclusion\n(.planning/research/.cache/deadbeef.json, with a stated reason). 52 + 1 = 53.\nconfig.json round-trips byte-identical to disk, including vibe_check,\nexperimental_widget_pipeline, nested telemetry.sampling.rate and the polymorphic\nparallelization object. No prototype pollution.\nNote: only 6 artifacts are kind:'unknown' now, where 01-VERIFICATION.md recorded \"dozens\".\nNot a regression — phases 02/03 added typed handlers, so 01-SPEC.md, 01-AI-SPEC.md,\n01-COST-MODEL.md and v3.0-CAPACITY-PLAN.md now classify as spec/ai-spec/cost-model/\ncapacity-plan instead of unknown. The \"never dropped\" invariant is what matters and it holds."
     },
     {
      "key": "covers",
      "value": "[01-02 D2]"
     },
     {
      "key": "why_human",
      "value": "The 01-02 executor recorded this as human_judgment because two of its checks depended on plan 01-03's handlers, which had not merged at the time."
     }
    ],
    "lead": ""
   },
   {
    "n": 4,
    "name": "Dense fixture — corruption isolation",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The `fixtures/dense` snapshot reports exactly two warnings — `HANDOFF.json` (stage `structured-extraction`) and `02-01-PLAN.md` (stage `frontmatter`, body intact) — and no warning for the third deliberate defect (frontmatter-with-no-body, by design). Every other file in the tree parses cleanly and the load never throws."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "executed_by",
      "value": "claude"
     },
     {
      "key": "evidence",
      "value": "Exactly 2 warnings across 52 artifacts — 50 files parse cleanly, load never throws.\nDefect 1 (.planning/phases/02-transport-layer/02-01-PLAN.md, tab-indented nested\nfrontmatter key): stage=frontmatter, salvage \"body intact, frontmatter unavailable\" —\nconfirmed, frontmatter {} with bodyLength 2052.\nDefect 2 (.planning/HANDOFF.json, trailing comma): stage=structured-extraction,\nsalvage \"nothing readable\" — confirmed. This is the cross-plan gap 01-02 flagged as\nhuman_judgment; 01-03's json-config handler closed it.\nDefect 3 (.planning/phases/01-identity-slice/01-VERIFICATION.md, valid frontmatter,\nempty body): NO warning, 5 frontmatter keys, bodyLength 0 — correct by design, an empty\nbody is a legitimate document state, not a parse failure."
     },
     {
      "key": "covers",
      "value": "[01-02 D3]"
     },
     {
      "key": "why_human",
      "value": "Same cross-plan gap as test 3 — the 01-02 executor could not confirm these until 01-03's json-config handler merged."
     }
    ],
    "lead": ""
   },
   {
    "n": 5,
    "name": "Path resolution across absolute/relative/~/symlink (01-01 D1)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "A user-supplied project path (absolute, relative, ~-prefixed, symlinked, or pointing directly at .planning/) resolves to a canonicalized root and produces normalized snapshot JSON via one CLI command, exit 0."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D1"
     }
    ],
    "lead": ""
   },
   {
    "n": 6,
    "name": "load()/refresh() never throw; four-variant LoadStatus (01-01 D2)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "load()/refresh() never throw; every failure names one of the four LoadStatus values plus the exact path checked, with wording centralized in one exported message map."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D2"
     }
    ],
    "lead": ""
   },
   {
    "n": 7,
    "name": "PlanningFilesystem boundary holds under substitution (01-01 D3)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The PlanningFilesystem boundary holds — a second (in-memory) implementation produces byte-identical snapshot output to the Node-backed one."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D3"
     }
    ],
    "lead": ""
   },
   {
    "n": 8,
    "name": "Generic markdown handler catches everything (01-01 D4)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The generic markdown handler matches unconditionally, is registered last, and every discovered artifact (including unrecognized file types) survives as kind: 'unknown' rather than being dropped."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D4"
     }
    ],
    "lead": ""
   },
   {
    "n": 9,
    "name": "Whole snapshot rebuilds through one refresh() (01-01 D5)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The whole snapshot is rebuildable through one refresh() entry point, which is also what a future watcher will call."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D5"
     }
    ],
    "lead": ""
   },
   {
    "n": 10,
    "name": "Non-UI harness dumps snapshot through one entry point (01-01 D6)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "A non-UI harness (CLI + Vitest) dumps the parsed snapshot as JSON through one shared entry point, bodies omitted by default with length+hash retained, --with-bodies restores them, --stable makes goldens clone-portable."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D6"
     }
    ],
    "lead": ""
   },
   {
    "n": 11,
    "name": "Escaping symlink refused, not followed or dropped (01-01 D7)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "An inside-tree symlink resolving outside the canonicalized root has its content refused, not silently followed or silently dropped — the artifact still appears with an empty body and a stage 'read' warning naming the escaping path."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-01 D7"
     }
    ],
    "lead": ""
   },
   {
    "n": 12,
    "name": "sparse-started fixture shape (01-02 D1)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "sparse-started fixture: one phase, a ROADMAP.md, no milestones/quick/research, no SUMMARY.md, zero warnings, one deliberate dangling requirement reference."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-02 D1"
     }
    ],
    "lead": ""
   },
   {
    "n": 13,
    "name": "GSD filename/directory grammar transcribed and cited (01-03 D1)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "GSD's real filename and directory grammar is transcribed into naming.ts, one module, every expression cited to a gsd-core source symbol; discovery classifies every file by position (root/phase/archived-phase/quick/milestone-root/research/other) as well as filename."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D1"
     }
    ],
    "lead": ""
   },
   {
    "n": 14,
    "name": "Unrecognized filenames survive as kind:'unknown' (01-03 D2)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Every discovered artifact — including an unrecognized filename token — survives as a base Artifact with kind:'unknown', never dropped, and dispatch never consults file content."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D2"
     }
    ],
    "lead": ""
   },
   {
    "n": 15,
    "name": "Ten typed handlers extract structured content (01-03 D3)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Ten typed handlers (state, roadmap, requirements, project, plan, summary, context, frontmatter-only, json-config, windows) extract each artifact type's structured content, including ROADMAP.md's per-phase blocks and milestone-grouped <details> form, REQUIREMENTS.md's items/out-of-scope/traceability, PLAN.md/SUMMARY.md's nested frontmatter with pseudo-XML body untouched, CONTEXT.md's six tag sections, and WINDOWS.md's fenced-JSON-preferred rows."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D3"
     }
    ],
    "lead": ""
   },
   {
    "n": 16,
    "name": "config.json read as a fully open map (01-03 D4)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "config.json (and HANDOFF.json/estimation-calibration.json) is read as a fully open map — unknown keys at any nesting depth round-trip unchanged, a polymorphic field (parallelization) is preserved in whichever shape it arrives, and a prototype-named key never reaches an object prototype."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D4"
     }
    ],
    "lead": ""
   },
   {
    "n": 17,
    "name": "Phase identity is the compound key (01-03 D5)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Phase identity is the compound (milestoneVersion, projectCode, number) — a live phase and an archived phase sharing the same number remain two distinct Phase entries; roadmapComplete and diskStatus stay two independently-populated fields that can legitimately disagree."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D5"
     }
    ],
    "lead": ""
   },
   {
    "n": 18,
    "name": "assembleDomainModel produces the whole graph and degrades well (01-03 D6)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "assembleDomainModel produces the whole graph: a phase directory with no ROADMAP.md entry, a ROADMAP.md entry with no directory, an empty project, quick tasks cross-linked to STATE.md's authoritative table, and dual-channel warning identity are all correct — and it degrades to a well-formed Project (never null) when every input file failed to parse."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-03 D6"
     }
    ],
    "lead": ""
   },
   {
    "n": 19,
    "name": "Resolved cross-references, dangling ones marked not dropped (01-04 D1)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The snapshot exposes resolved requirement-to-phase, phase-to-plan, and decision-to-file references, with unresolvable ones present and explicitly marked."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D1"
     }
    ],
    "lead": ""
   },
   {
    "n": 20,
    "name": "Filesystem substitution changes nothing downstream (01-04 D2)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "Swapping the filesystem implementation changes nothing downstream, proven by byte-identical output."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D2"
     }
    ],
    "lead": ""
   },
   {
    "n": 21,
    "name": "refresh() rebuilds without mutating the previous snapshot (01-04 D3)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "The whole snapshot rebuilds through one refresh() call without mutating the previous one."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D3"
     }
    ],
    "lead": ""
   },
   {
    "n": 22,
    "name": "Corrupted file degrades to raw body plus warning (01-04 D4)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "A deliberately corrupted file degrades to its raw body plus a recorded warning while every other file parses cleanly."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D4"
     }
    ],
    "lead": ""
   },
   {
    "n": 23,
    "name": "All three fixture trees produce clone-portable snapshots (01-04 D5)",
    "result": "pass",
    "resultRaw": "pass",
    "fields": [
     {
      "key": "expected",
      "value": "All three fixture trees produce complete, committed, clone-portable snapshots."
     },
     {
      "key": "result",
      "value": "pass"
     },
     {
      "key": "source",
      "value": "automated"
     },
     {
      "key": "coverage_id",
      "value": "01-04 D5"
     }
    ],
    "lead": ""
   }
  ],
  "summary": {
   "total": "23",
   "passed": "23",
   "issues": "0",
   "pending": "0",
   "skipped": "0",
   "blocked": "0"
  },
  "gaps": {
   "items": [],
   "prose": null
  },
  "gapsTitle": "Gaps",
  "extra": []
 }
};
