/* Sketch 008 data. Text is verbatim from the two RESEARCH.md files except where trimmed (…) for
   length. Evidence tags ([VERIFIED: …], [CITED: …], [ASSUMED]) are kept verbatim; the page turns
   them into small markers. Fields marked HAND are annotations a parser would have to derive:
   `sus` from the "[WARNING: flagged as suspicious…]" suffix, `verdict` on alternatives from the
   tradeoff's opening word, `sev`/`code` from the pitfall heading's parenthetical, `badge` on tree
   rows from NEW / EXTEND / EXISTING in the comment. The diagram and tree strings are verbatim. */
window.DOCS = {
lab02: {
  file: '02-RESEARCH.md', project: 'labelore', phase: 'Phase 2', context: '02-CONTEXT.md',
  title: 'Situational Awareness & Artifact Reading',
  researched: '2026-08-25',
  validUntil: '2026-09-01 for package versions; architecture remains valid until Phase 1 domain contracts change.',
  domain: 'Local read-only React dashboard, milestone routing, and safe technical-document rendering',
  confidence: { raw: 'HIGH for repository architecture; MEDIUM for current external-library guidance', level: 'mixed' },
  breakdown: [
    { area: 'Standard stack', level: 'MEDIUM', note: 'official docs and registry versions are current, but 12 packages are protocol-flagged `SUS` solely for recent releases and require human approval.' },
    { area: 'Architecture', level: 'HIGH', note: 'derived directly from the implemented Phase 1 graph, serializers, handlers, fixtures, and locked Phase 2 decisions.' },
    { area: 'Pitfalls', level: 'HIGH', note: 'core failures are reproduced by current contracts/corpus shapes; external security ordering is confirmed by official docs.' },
    { area: 'Dashboard semantics', level: 'MEDIUM', note: 'source fields are verified, while prioritization/suppression rules remain assumptions A2/A3.' },
    { area: 'Coverage matching', level: 'MEDIUM-LOW', note: 'source mismatch is verified; the proposed inference rule needs corpus tests and explicit acceptance.' },
  ],
  summary: [
    'Phase 2 should be planned as six cooperating subsystems rather than three page-shaped plans: delivery/API shell, cycle-free client DTOs and selectors, canonical routing/reference resolution, dashboard/roadmap/history views, the artifact-rendering pipeline, and the studio-portal-derived visual shell. The Phase 1 dependency direction is already fixed: browser and server presentation code consume `PlanningRepository.load()` output and must never read the target filesystem directly. The repository refresh seam produces a new snapshot and is the only load boundary. [VERIFIED: `src/planning-repo/snapshot.ts:15-26,57-90`]',
    'The most important hidden constraint is serialization. The in-memory domain graph is deliberately cyclic: phase requirement references point to requirements, whose covering-phase references can point back to phases. `JSON.stringify` therefore cannot be used directly at a Hono endpoint. Phase 2 needs an explicit cycle-free API DTO that replaces object references with canonical identity keys and provides artifact bodies through snapshot-derived lookup—not through route-local disk reads. [VERIFIED: `src/planning-repo/serialize.ts:28-45`; `src/domain/model.ts:120-171`]',
    'The renderer should treat source markdown as hostile even though the app is local. Parse the small, recognized PLAN pseudo-XML grammar into semantic segments before Markdown conversion; run ordinary content through the official raw-HTML/sanitization chain; add only trusted heading/link/highlight nodes after sanitization; initialize Shiki once; and render Mermaid in the browser with `securityLevel: \'strict\'`. [CITED: https://github.com/remarkjs/remark-rehype#example-supporting-html-in-markdown-properly] [CITED: https://mermaid.js.org/config/usage.html]',
  ],
  recommendation: 'Build one reusable `ProjectPresentation`/DTO and one canonical route/reference codec first; make every dashboard, roadmap, preview, and document view consume those two seams.',
  stackIntro: 'The project already pins TypeScript `5.9.3`, Vitest `4.1.11`, and `gray-matter` `4.0.3`; keep those exact versions and add the web stack without upgrading the established toolchain. [VERIFIED: `package.json:14-25`]',
  core: [
    { name: 'vite', sus: true, version: '8.2.2', date: '2026-08-20', purpose: 'Browser dev/build tool', why: 'Official backend integration and JS APIs fit the existing Node entrypoint. [CITED: https://vite.dev/guide/backend-integration.html]' },
    { name: 'react, react-dom', version: '19.2.8', date: '2026-07-21', purpose: 'UI and DOM renderer', why: 'React\'s official existing-project guide installs both packages. [VERIFIED: npm registry] [CITED: https://react.dev/learn/add-react-to-an-existing-project]' },
    { name: 'hono + @hono/node-server', sus: true, version: '4.13.4 · 2.1.1', date: '2026-08-24', purpose: 'JSON API and production static server', why: 'Official Node adapter supplies `serve` and static-file middleware. [CITED: https://hono.dev/docs/getting-started/nodejs]' },
    { name: 'react-router', version: '8.3.0', date: '2026-07-22', purpose: 'Client routing', why: 'Official library mode supports nested routes, dynamic segments, loaders, and route handles. [VERIFIED: npm registry] [CITED: https://reactrouter.com/start/data/routing]' },
    { name: '@tanstack/react-query', sus: true, version: '5.102.3', date: '2026-08-24', purpose: 'Server-state cache', why: 'Establishes one query invalidation seam for Phase 4 refresh and future watcher events. [CITED: https://tanstack.com/query/latest/docs/framework/react/installation]' },
    { name: 'tailwindcss + @tailwindcss/vite', version: '4.3.3', date: '2026-07-16', purpose: 'Token-driven styling', why: 'Official Vite plugin and CSS-first setup match the theme source. [VERIFIED: npm registry] [CITED: https://tailwindcss.com/docs/installation/using-vite]' },
  ],
  supporting: [
    { name: '@vitejs/plugin-react', sus: true, version: '6.1.0', purpose: 'React Fast Refresh transform', why: 'Vite web configuration. [CITED: https://vite.dev/plugins/]' },
    { name: 'unified', version: '11.0.5', purpose: 'AST pipeline', why: 'Processor core. [VERIFIED: npm registry]' },
    { name: 'remark-parse / remark-gfm', version: '11.0.0 · 4.0.1', purpose: 'Markdown and GFM parsing', why: 'All artifact bodies. [VERIFIED: npm registry]' },
    { name: 'remark-rehype', version: '11.1.2', purpose: 'mdast → hast', why: 'Bridge after PLAN segmentation. [VERIFIED: npm registry]' },
    { name: 'rehype-raw / rehype-sanitize', version: '7.0.0 · 6.0.0', purpose: 'Parse then sanitize embedded HTML', why: 'Always adjacent and in this order. [VERIFIED: npm registry]' },
    { name: 'rehype-slug / rehype-stringify', version: '6.0.0 · 10.0.1', purpose: 'Stable heading IDs and HTML', why: 'Whole-document postprocessing/output. [VERIFIED: npm registry]' },
    { name: 'shiki', sus: true, version: '4.4.3', purpose: 'Code highlighting with dual themes', why: 'Initialize once; emit light/dark CSS variables. [CITED: https://shiki.style/guide/dual-themes]' },
    { name: 'mermaid', sus: true, version: '11.17.1', purpose: 'Diagram rendering', why: 'Browser-only, manually run under strict security. [CITED: https://mermaid.js.org/config/usage.html]' },
    { name: '@base-ui/react', sus: true, version: '1.7.0', purpose: 'Accessible popover/disclosure primitives', why: 'Link previews and roadmap expansion. [CITED: https://base-ui.com/react/components/popover]' },
    { name: 'lucide-react', sus: true, version: '1.34.0', purpose: 'Icons', why: 'Theme toggle, copy link, status/attention icons. [CITED: https://lucide.dev/]' },
    { name: 'class-variance-authority, clsx, tailwind-merge', version: '0.7.1 · 2.1.1 · 3.6.0', purpose: 'Generated component variants and class merging', why: 'Match base-sera component conventions. [VERIFIED: npm registry]' },
    { name: 'tw-animate-css', version: '1.4.0', purpose: 'Generated component transition utilities', why: 'Only where selected base-sera primitives require them. [VERIFIED: npm registry]' },
    { name: 'shadcn', sus: true, version: '4.19.0', purpose: 'One-time base-sera component generation', why: 'Install as a dev tool and invoke locally; do not make the app import the CLI. [CITED: https://ui.shadcn.com/docs/installation/vite]' },
    { name: '@types/react, @types/react-dom', sus: true, version: '19.2.18 · 19.2.5', purpose: 'React TypeScript types', why: 'React\'s official TypeScript guide names both packages; use them only in the web tsconfig. [CITED: https://react.dev/learn/typescript]' },
    { name: 'eslint-plugin-react-hooks', version: '7.1.1', purpose: 'Hooks lint rules', why: 'Extend the existing flat ESLint config for TSX. [VERIFIED: npm registry]' },
  ],
  alternatives: [
    { instead: 'Separate cycle-free DTO', could: '`normalizeForGolden()` output', verdict: 'rejected', tradeoff: 'Rejected: golden normalization duplicates shared references, emits `$circularRef` stubs, and optionally removes bodies; it is a harness format, not a client API contract. [VERIFIED: `src/planning-repo/serialize.ts:41-87`]' },
    { instead: 'Server-rendered sanitized HTML', could: 'Client-only Markdown processing', verdict: 'rejected', tradeoff: 'Client processing increases bundle/work per navigation and makes security/pipeline consistency harder; Mermaid remains the one browser-only stage. [CITED: https://mermaid.js.org/config/usage.html]' },
    { instead: 'Bounded PLAN grammar', could: 'XML DOM parser', verdict: 'rejected', tradeoff: 'GSD PLAN bodies contain Markdown within XML-like wrappers rather than a schema-validated XML document; parsing only recognized wrappers preserves forward-compatible Markdown. [VERIFIED: `src/planning-repo/handlers/plan.ts:1-25`]' },
    { instead: 'Vertical execution spine', could: 'Parsed dependency graph', verdict: 'rejected', tradeoff: 'The existing source contract deliberately keeps phase dependency text free-form and does not create edges. [VERIFIED: `src/domain/model.ts:127-130`]' },
    { instead: 'Base UI popover', could: 'Custom floating/focus manager', verdict: 'rejected', tradeoff: 'Base UI already supports anchoring to a supplied element and collision handling. [CITED: https://base-ui.com/react/components/popover]' },
  ],
  audit: {
    intro: 'The table records the exact 2026-08-25 package-legitimacy seam output. `SUS` here means the latest release triggered the seam\'s `too-new` rule; protocol requires a human checkpoint even where official documentation and very high download counts strongly indicate a legitimate package. [VERIFIED: package-legitimacy seam]',
    rows: [
      ['vite','npm','6y','169,369,863','github.com/vitejs/vite','SUS','too-new','Flagged — checkpoint'],
      ['react','npm','14y','170,480,639','github.com/react/react','OK','','Approved'],
      ['react-dom','npm','12y','159,631,504','github.com/react/react','OK','','Approved'],
      ['@vitejs/plugin-react','npm','4y','83,483,737','github.com/vitejs/vite-plugin-react','SUS','too-new','Flagged — checkpoint'],
      ['hono','npm','4y','56,399,133','github.com/honojs/hono','SUS','too-new','Flagged — checkpoint'],
      ['@hono/node-server','npm','3y','52,961,881','github.com/honojs/node-server','SUS','too-new','Flagged — checkpoint'],
      ['react-router','npm','12y','51,841,394','github.com/remix-run/react-router','OK','','Approved'],
      ['@tanstack/react-query','npm','4y','66,137,030','github.com/TanStack/query','SUS','too-new','Flagged — checkpoint'],
      ['unified','npm','11y','52,760,558','github.com/unifiedjs/unified','OK','','Approved'],
      ['remark-parse','npm','10y','49,018,100','github.com/remarkjs/remark','OK','','Approved'],
      ['remark-gfm','npm','5y','37,445,521','github.com/remarkjs/remark-gfm','OK','','Approved'],
      ['remark-rehype','npm','10y','42,083,773','github.com/remarkjs/remark-rehype','OK','','Approved'],
      ['rehype-raw','npm','9y','17,693,218','github.com/rehypejs/rehype-raw','OK','','Approved'],
      ['rehype-sanitize','npm','9y','9,547,765','github.com/rehypejs/rehype-sanitize','OK','','Approved'],
      ['rehype-slug','npm','9y','3,306,643','github.com/rehypejs/rehype-slug','OK','','Approved'],
      ['rehype-stringify','npm','10y','7,768,595','github.com/rehypejs/rehype','OK','','Approved'],
      ['shiki','npm','12y','20,802,425','github.com/shikijs/shiki','SUS','too-new','Flagged — checkpoint'],
      ['mermaid','npm','11y','14,526,740','github.com/mermaid-js/mermaid','SUS','too-new','Flagged — checkpoint'],
      ['tailwindcss','npm','8y','125,155,069','github.com/tailwindlabs/tailwindcss','OK','','Approved'],
      ['@tailwindcss/vite','npm','2y','46,022,969','github.com/tailwindlabs/tailwindcss','OK','','Approved'],
      ['@base-ui/react','npm','8mo','10,466,051','github.com/mui/base-ui','SUS','too-new','Flagged — checkpoint'],
      ['lucide-react','npm','5y','96,054,697','github.com/lucide-icons/lucide','SUS','too-new','Flagged — checkpoint'],
      ['class-variance-authority','npm','4y','64,279,699','github.com/joe-bell/cva','OK','','Approved'],
      ['clsx','npm','7y','120,733,677','github.com/lukeed/clsx','OK','','Approved'],
      ['tailwind-merge','npm','5y','82,644,022','github.com/dcastil/tailwind-merge','OK','','Approved'],
      ['tw-animate-css','npm','1y','38,303,711','github.com/Wombosvideo/tw-animate-css','OK','','Approved'],
      ['shadcn','npm','2y','8,179,709','github.com/shadcn-ui/ui','SUS','too-new','Flagged — checkpoint'],
      ['@types/react','npm','10y','159,239,097','github.com/DefinitelyTyped/DefinitelyTyped','SUS','too-new','Flagged — checkpoint'],
      ['@types/react-dom','npm','10y','132,166,946','github.com/DefinitelyTyped/DefinitelyTyped','SUS','too-new','Flagged — checkpoint'],
      ['eslint-plugin-react-hooks','npm','7y','97,785,728','github.com/facebook/react','OK','','Approved'],
    ],
    slop: [],
    susNote: 'The planner must place one consolidated `checkpoint:human-verify` before installation and show the exact seam evidence. [VERIFIED: package-legitimacy seam]',
    extra: [],
  },
  diagramId: 'lab02-diagram',
  diagramNote: 'No arrow returns to the filesystem. The UI is observational and read-only. [VERIFIED: `.claude/CLAUDE.md:16-31`; `src/planning-repo/snapshot.ts:57-90`]',
  treeId: 'lab02-tree',
  treeNote: 'This preserves the existing one-way `planning-fs → planning-repo → domain` layering; `presentation`, `rendering`, and `web` may import the zero-I/O domain vocabulary but must not import `planning-fs` or handler internals.',
  patterns: [
    { title: 'Explicit Cycle-Free API DTO', what: 'Convert the in-memory graph into plain records keyed by canonical IDs. Serialize references as keys or `null`, never by recursively embedding resolved objects.', when: 'Every server response. Do not return `Project` directly.' },
    { title: 'One Canonical Route Codec', what: 'Centralize `phaseKey`, `planKey`, `artifactToken`, builders, and parsers.', when: 'Everywhere a URL or identity is created or decoded.' },
    { title: 'Pure Situational-Awareness Selectors', what: 'Build a single `DashboardViewModel` from snapshot facts before React rendering.' },
    { title: 'Bounded PLAN Grammar Before Markdown', what: 'Recognize a small allowlist of wrapper tags (`objective`, `task`, `decision`, …) with a stack-based, linear scanner that ignores fenced code.', when: 'Only for artifacts whose resolved kind is the verbatim handler value `kind: \'plan\'`.' },
    { title: 'Sanitize Before Trusted Enrichment', what: 'Use one processor lifecycle: raw → sanitize → slug → references → Shiki → copy controls → stringify.' },
    { title: 'Known Frontmatter Views With a Generic Remainder', what: 'A field-view registry consumes `Record<string, unknown>`, type-guards each known field, records handled keys, then renders every remaining entry recursively as safe text.' },
    { title: 'Conservative Truth-to-Coverage Matching', what: 'Coverage rows do not carry a stable pointer to a plan truth. Exact normalized text first, then mutual-unique Jaccard ≥ 0.60.' },
    { title: 'Ordered Flow, Not Invented Graph', what: 'Render one vertical execution spine through phases in existing order, with compact connectors/status markers.' },
  ],
  anti: [
    { lead: '`c.json(snapshot.project)`', rest: 'the graph contains real cycles and JSON serialization throws. Build the DTO.' },
    { lead: 'Route-local filesystem reads', rest: 'they create a second freshness/cache truth and violate Phase 1\'s seam.' },
    { lead: 'Passing PLAN tags into raw HTML parsing', rest: 'Markdown inside pseudo-XML becomes opaque HTML or disappears. Segment recognized wrappers first.' },
    { lead: 'Array-index coverage pairing', rest: 'real plan truths and summary coverage arrays need not align.' },
    { lead: 'Phase number as a key', rest: 'archived and active milestones can both contain Phase 1.' },
    { lead: 'Always-visible anchor icons', rest: 'D-16 requires hover/focus disclosure and no scroll-driven URL updates.' },
    { lead: 'Linkifying raw strings before Markdown parsing', rest: 'this corrupts code fences, inline code, and authored links.' },
    { lead: 'Mermaid `securityLevel: \'loose\'`', rest: 'loose allows HTML labels and click behavior; keep strict for artifact input.' },
    { lead: '`overflow-x: hidden` on the entire app as the only fix', rest: 'it masks which component is too wide.' },
  ],
  handroll: [
    { problem: 'Markdown/GFM parsing', dont: 'Regex Markdown renderer', use: 'unified + remark packages', why: 'Tables, task lists, nesting, raw HTML boundaries, and AST positions are already handled.' },
    { problem: 'HTML sanitization', dont: 'Tag/attribute blacklist', use: '`rehype-sanitize` immediately after `rehype-raw`', why: 'XSS requires context-sensitive sanitization; blacklists miss schemes and attributes.' },
    { problem: 'Syntax highlighting', dont: 'Regex lexer or per-request highlighter', use: 'Shiki singleton with dual themes', why: 'Shiki emits theme-aware token output.' },
    { problem: 'Diagram parsing', dont: 'Mermaid regex/SVG generation', use: 'Mermaid `run()` in strict mode', why: 'Diagram grammar and rendering are complex; strict mode limits embedded behavior.' },
    { problem: 'Floating preview geometry/focus', dont: 'Custom portal/positioning engine', use: 'Base UI Popover anchored to the clicked element', why: 'It supplies collision-aware anchoring and popup primitives.' },
    { problem: 'Component visual baseline', dont: 'Recreate a parallel design system', use: 'shadcn base-sera source plus studio tokens', why: 'Sera is specifically typography-first with square corners and uppercase tracking.' },
    { problem: 'Phase dependency graph', dont: 'Parse arbitrary arrows/free prose', use: 'Ordered spine + raw dependency labels', why: 'Phase 1 explicitly preserved the text rather than fabricating edges.' },
    { problem: 'Project reads', dont: 'API endpoint calling `node:fs` by path', use: '`PlanningRepository` snapshot/artifact index', why: 'One load/refresh seam preserves consistency and future watching.' },
  ],
  handrollInsight: 'The only justified custom parsers are domain adapters: the bounded PLAN wrapper grammar, view-model decoders for open frontmatter, and contextual ID resolution. Markdown, HTML security, code grammars, diagrams, popup focus, and general routing should remain library-owned.',
  pitfalls: [
    { title: 'Treating the Domain Graph as an API Shape', what: 'Hono throws while serializing or emits huge recursively duplicated responses.', why: 'Eager resolved references are ideal in memory but intentionally cyclic.', avoid: 'Create explicit DTOs and reference keys; add a dense-fixture JSON serialization test.', signs: '`$circularRef` appears in browser data, or an endpoint imports `normalizeForGolden`.' },
    { title: 'PLAN Pseudo-XML Is Swallowed or Leaked', what: '`<objective>` content disappears as HTML, task Markdown does not format, or closing tags print as garbage.', why: 'Those wrappers are domain syntax around Markdown, not ordinary HTML.', avoid: 'Segment the known grammar before Markdown; test multiline, inline, nested task fields, attributes, fenced-code tag text, mismatches, and unknown tags against a real multi-task plan.', signs: 'A toy plan passes while `.planning/phases/01-read-layer-domain-model/01-04-PLAN.md` fails.' },
    { title: 'Sanitization Happens Too Late—or Is Undone Later', what: 'Embedded scripts/events/unsafe URLs survive, or a post-sanitize plugin copies untrusted attributes into trusted nodes.', why: 'Raw HTML is expanded without a sanitizer, or trusted enrichment treats source attributes as configuration.', avoid: 'Keep the documented raw→sanitize order; allow only needed classes/tags; generate post-sanitize URLs exclusively through the route codec.', signs: '`onclick`, `javascript:`, user-controlled `style`, iframes, or SVG event attributes appear in renderer snapshots.' },
    { title: 'Coverage Matrix Claims More Than the Corpus Encodes', what: 'A truth is marked covered because it happened to share an array index with an unrelated coverage item.', why: '`must_haves.truths` has no stable IDs, while coverage has its own deliverable IDs.', avoid: 'Conservative one-to-one matching, inferred labels, unmatched rows, and pair tests from both the synthetic dense fixture and studio-portal.', signs: 'Every row is always “matched,” or reordering YAML changes the result.' },
    { title: 'Reference Resolution Loses Milestone Context', what: '“Phase 1” in an archived document previews the active Phase 1.', why: 'Resolution uses number alone rather than the source artifact\'s milestone context.', avoid: 'Resolve phase/plan prose relative to the containing artifact\'s milestone; root current docs resolve against the active milestone. Unresolved remains text.', signs: '`phase.number` or plan ID appears as a global `Map` key without milestone scope.' },
    { title: 'Deep Links Work In-App but 404 on Refresh', what: 'React navigation succeeds, but pasting a plan URL into a new tab returns a static-file 404.', why: 'Hono serves assets but has no final SPA fallback.', avoid: 'API routes first, static assets second, and a final non-API `index.html` response; integration-test a milestone-qualified plan URL.' },
    { title: 'Dashboard Status Is Recomputed from Displayed Markdown', what: 'Visual progress conflicts with STATE, or disk completion is collapsed into roadmap completion.', why: 'Components count checkboxes/files independently.', avoid: 'Pure selectors over the DTO; keep formal/observed provenance in each returned signal.' },
    { title: 'Wide Content Breaks the Shell', what: 'A table or Shiki/Mermaid block expands the page body horizontally, especially inside nested flex/grid containers.', why: 'An ancestor lacks `min-width: 0`, or content wrappers rely on body clipping.', avoid: 'Assert `html, body, #root { max-width: 100%; }`, set `min-w-0` at each content column, and wrap `table`, `pre`, and Mermaid output in local horizontal scrollers.', signs: 'A 390px viewport can pan the whole page, or the header moves sideways while a table scrolls.' },
    { title: 'Theme Flash and Highlight Drift', what: 'Initial paint uses the wrong theme, or code blocks remain light after switching dark.', why: 'Theme is applied after React mounts, or Shiki output has one theme.', avoid: 'Apply the stored class in a compile-time constant inline head script before paint; emit Shiki dual-theme variables keyed by the same `.dark` root class.' },
  ],
  questionsHeading: 'Open Questions (RESOLVED)',
  questions: [
    { title: 'authoritative truth-to-coverage matching rule.', resolved: true, body: 'Normalize case, whitespace, and punctuation and accept exact text matches first. For remaining rows, require significant-token Jaccard overlap of at least `0.60`. If both rows declare requirement IDs, at least one ID must also be shared; requirement overlap alone is never evidence.' },
    { title: 'authored blocker and human-verification sources.', resolved: true, body: 'Dependency blocks come from unresolved or incomplete `Plan.dependsOnRefs`. StateHandler projects a dedicated `structured.blockersConcerns` record; selectors never grep STATE body text.' },
    { title: 'browser UAT runs as a blocking end-of-phase human checkpoint.', resolved: true, body: 'No `chromium`, `google-chrome`, or `firefox` command was detected in PATH. After all automated suites pass, execution pauses at one blocking browser checkpoint.' },
  ],
  env: [
    { dep: 'Node.js', by: 'server, Vite, tests', ok: true, ver: '22.23.1', fb: '—' },
    { dep: 'npm', by: 'package install/scripts', ok: true, ver: '10.9.8', fb: '—' },
    { dep: 'Git', by: 'project workflow', ok: true, ver: 'detected', fb: '—' },
    { dep: 'ripgrep', by: 'corpus checks', ok: true, ver: 'detected', fb: '—' },
    { dep: 'Existing Vitest suite', by: 'regression checks', ok: true, ver: '4.1.11', fb: '—' },
    { dep: 'Vite/React/Hono/renderer packages', by: 'Phase 2 implementation', ok: false, ver: 'not installed', fb: 'Install after package checkpoint' },
    { dep: 'Chromium/Chrome/Firefox CLI', by: 'automated visual smoke', ok: false, ver: '—', fb: 'Human browser UAT' },
  ],
  envNotes: ['**Missing dependencies with no fallback:** none for implementation after approved npm installation.', '**Missing dependencies with fallback:** browser CLI—use the host browser for required visual/keyboard/contrast/overflow UAT.'],
  runtime: null,
  sources: {
    primary: ['`src/domain/model.ts`, `src/planning-repo/{snapshot,assemble,serialize,crossref,mentions}.ts`, and handlers — current repository contracts and discrete values.', '`.planning/STATE.md`, `.planning/ROADMAP.md`, `.planning/REQUIREMENTS.md`, Phase 1 plans/summaries, and dense fixtures — current project/corpus behavior.', '`/home/cinedise/studio-portal/frontend/{package.json,components.json,app/globals.css,…}` — required visual reference.', '`/home/cinedise/studio-portal/.planning/phases/04-bulk-archive-downloads/04-05-{PLAN,SUMMARY}.md` — real mismatch-sensitive plan/coverage pair.', 'Live npm registry and package-legitimacy seam checks on 2026-08-25 — versions, publish signals, downloads, repositories, postinstall fields, and verdicts.'],
    secondary: ['https://vite.dev/guide/backend-integration.html — backend/Vite integration.', 'https://vite.dev/plugins/ — official React plugin identity and purpose.', 'https://react.dev/learn/add-react-to-an-existing-project and https://react.dev/learn/typescript — official React/React DOM and TypeScript package setup.', 'https://hono.dev/docs/getting-started/nodejs — Node adapter and static serving.', 'https://reactrouter.com/start/data/routing — library/data route configuration.', 'https://github.com/remarkjs/remark-rehype#example-supporting-html-in-markdown-properly — safe raw HTML order.', 'https://shiki.style/guide/dual-themes — dual-theme highlighting.', 'https://mermaid.js.org/config/usage.html — strict security and `run()`.', 'https://tailwindcss.com/docs/installation/using-vite and https://tailwindcss.com/docs/dark-mode — Vite and manual theme setup.', 'https://ui.shadcn.com/docs/installation/vite and https://ui.shadcn.com/docs/changelog/2026-04-sera — Vite/base-sera setup.', 'https://base-ui.com/react/components/popover — anchored preview primitive.', 'OWASP XSS/Input Validation cheat sheets and ASVS project page — rendering security controls.'],
    tertiary: ['Assumptions A1–A5 above; each needs planner/user confirmation or an explicit implementation test.'],
  },
  constraints: {
    locked: [
      { group: 'Landing-Page Hierarchy', ids: ['D-01','D-02','D-03','D-04'] },
      { group: 'Roadmap and Milestone Browsing', ids: ['D-05','D-06','D-07','D-08'] },
      { group: 'Artifact-Reading Experience', ids: ['D-09','D-10','D-11','D-12'] },
      { group: 'Deep Links and Document Navigation', ids: ['D-13','D-14','D-15','D-16','D-17'] },
    ],
    discretion: ['Exact spacing, typography scale, responsive breakpoints, and low-level component composition within the required studio-portal visual language.', 'Exact route segment names and slug-normalization mechanics, provided D-13\'s milestone-qualified, readable hierarchy and stable identity constraints hold.', 'Preview placement, dismissal mechanics, and subtle transitions, provided pointer and keyboard users receive equivalent access.', 'Exact dependency-connector drawing technique for the vertical flow.'],
    deferred: ['Add a richer dependency graph canvas in a future phase. Phase 2 intentionally uses the vertical phase flow with compact connectors; ROAD-03\'s legible-flow requirement must still be satisfied now.'],
  },
  requirements: [
    ['DASH-01','Landing view shows current milestone, current phase number and name, status, and progress, sourced from `STATE.md` frontmatter','Dashboard selector and cycle-free DTO patterns'],
    ['DASH-02','Landing view shows what comes next and what is blocked','Deterministic next-work and dependency selectors'],
    ['DASH-03','Landing view shows work awaiting human verification','Coverage/checkpoint attention extraction'],
    ['DASH-04','Formal roadmap completion and observed disk state remain separate and disagreements are visible','Existing `roadmapComplete` / `diskStatus` contract'],
    ['ROAD-01','Every phase shows goal, success criteria, mapped requirements, and dependencies','Existing `Phase` projection and expansion pattern'],
    ['ROAD-02','Plans are grouped by wave with blocked-on relationships','Open-frontmatter wave grouping and `dependsOnRefs`'],
    ['ROAD-03','Phase dependencies render as a legible flow, not ASCII art','Ordered vertical spine plus verbatim dependency labels'],
    ['ROAD-04','Phase identity is milestone-qualified throughout','Canonical route-key builder from `PhaseIdentity`'],
    ['READ-01','GFM tables, highlighted code, task lists, and blockquotes render','unified/remark/rehype/Shiki pipeline'],
    ['READ-02','Known YAML fields render as structured panels','Frontmatter view registry with generic remainder'],
    ['READ-03','PLAN pseudo-XML renders as semantic structure','Bounded pseudo-XML segment parser before markdown'],
    ['READ-04','Rendered markdown is sanitized','`rehype-raw` → `rehype-sanitize` security order'],
    ['READ-05','Plan and summary read together with truth-to-coverage matching','Pair DTO plus conservative match matrix'],
    ['READ-06','Document headings have stable anchors','`rehype-slug` plus custom copy-link affordance'],
    ['NAV-02','Requirement IDs in prose link to the covering phase','AST text-node linkifier and canonical resolver'],
    ['NAV-03','Phase and plan references in prose link correctly','Milestone-contextual reference resolution'],
    ['NAV-04','Undefined IDs remain plain text','Linkifier emits a control only after successful resolution'],
    ['NAV-06','URLs map to milestone → phase → plan → artifact','Central route codec and SPA fallback'],
    ['HIST-01','Archived milestones are viewable and visually distinct','Archived milestone section from `Project.milestones`'],
    ['HIST-02','Archived phase trees are browsable','Expandable archived phase/artifact projection'],
    ['UI-01','Use studio-portal oklch/base-sera/lucide/squared-corner language','Verified visual source and shadcn Vite setup'],
    ['UI-02','Light and dark themes work on long-form content','Shared token port, no-flash theme init, Shiki dual themes'],
    ['UI-03','Wide content scrolls locally; page body never scrolls horizontally','Explicit containment contract and real-corpus UAT'],
  ],
  respMap: [
    ['Target path and snapshot loading','API / Backend','Database / Storage (filesystem adapter)'],
    ['Cycle-free project/artifact DTO','API / Backend','Browser / Client'],
    ['Dashboard fact derivation','API / Backend','Browser / Client'],
    ['Roadmap and history flow','Browser / Client','API / Backend'],
    ['Markdown and PLAN parsing','API / Backend','Browser / Client'],
    ['Canonical URLs and reference resolution','Shared route module','API / Backend'],
    ['Reference preview interaction','Browser / Client','API / Backend'],
    ['Static assets and SPA fallback','API / Backend','CDN / Static'],
  ],
  sourceOnly: [['Installation', 'Standard Stack'], ['Version verification', 'Standard Stack'], ['Code Examples', '4 blocks'], ['State of the Art', ''], ['Verification Strategy', ''], ['Assumptions Log', '5 rows'], ['Security Domain', ''], ['Metadata', '']],
},

sp02: {
  file: '02-RESEARCH.md', project: 'studio-portal', phase: 'Phase 2', context: '02-CONTEXT.md',
  title: 'Storage Health & Status',
  researched: '2026-07-17',
  validUntil: '~2026-08-16 (30 days) for the stack. **Hardware findings are perishable:** device enumeration, mount state, and archive\'s SMART verdict can change at any moment.',
  domain: 'Host-integrated storage health probing (statvfs / SMART / rclone) with per-tier fault isolation, pushed over WebSocket',
  confidence: { raw: 'HIGH', level: 'HIGH' },
  breakdown: [
    { area: 'Standard stack', level: 'HIGH', note: 'rustix compile-and-run verified against a real tier; host binaries version-checked in situ; legitimacy gate clean' },
    { area: 'Architecture', level: 'HIGH', note: 'the isolation design is grounded in measured numbers (30 s SCSI timeout, 0.002 ms healthy statvfs, 512-thread pool) and official tokio docs, not inference' },
    { area: 'Pitfalls', level: 'HIGH', note: 'HIGH for F1/F2/F5/F8/F9 (proven or read from the authoritative man page on this host); MEDIUM for F3/F4; LOW for A1/A2' },
    { area: 'Capacity probing', level: 'HIGH', note: 'math validated against `df` on all three local tiers' },
    { area: 'SMART probing', level: 'MEDIUM', note: 'the *mechanism* (bitmask, `-j`, device paths) is HIGH; the *actual drive verdicts* are unverified and gated' },
    { area: 'UI', level: 'HIGH', note: 'UI-SPEC is approved (6/6) and the installed toolchain matches it exactly' },
  ],
  summary: [
    'This phase is unusual in that **the research could be run against the real production host** — I probed the actual four tiers, the actual Seagate/SanDisk USB bridges, the actual `cloud:` remote, and compile-ran the candidate `statvfs` API against `/mnt/archive`. That converted most of what would normally be assumed knowledge into measured fact, and it surfaced **three defects that the locked decisions do not currently prevent** and that would each individually cause the phase to ship broken while looking finished.',
    'The most important is **F1**: `/mnt/vault` and `/mnt/archive` are mounted `nofail`. When a USB tier is absent, the mount point degrades to an ordinary empty directory on the root filesystem, and `statvfs("/mnt/archive")` then **succeeds in microseconds and returns the root filesystem\'s capacity**. It does not error and it does not hang, so D-15\'s bounded-canary design — whose entire signal is *the timeout* — cannot detect it. The archive card would render **healthy, with fabricated numbers**. The fix is cheap and strictly additive: read `/proc/self/mountinfo` first, then run the bounded canary.',
    'The second is **F2**: `smartctl`\'s exit status is a **bitmask**, and bit 3 (value 8) means "SMART status check returned DISK FAILING". … The third is **F3**: tokio\'s own docs confirm `spawn_blocking` closures are uncancellable *and* that "runtime shutdown will wait indefinitely for all started `spawn_blocking` to finish" — so a wedged tier would also stall every restart on a box that restarts constantly.',
  ],
  recommendation: 'Build one dedicated OS thread per tier (never `spawn_blocking`), each running a layered probe — `/proc/self/mountinfo` (never blocks) → bounded `statvfs` canary (~2 s, vs. a measured 0.002 ms healthy / 30 s SCSI timeout) → SMART on a slower cadence with **bitmask-decoded** exit codes — publishing into a `watch`/`broadcast` bus that the existing ticket-authorized `/ws` handler fans out per-tier.',
  stackIntro: null,
  core: [
    { name: 'rustix', version: '1.1.4', purpose: '`statvfs` for tier capacity + `ST_RDONLY` detection', why: 'Rust std has no `statvfs`. rustix is the maintained, safe, `1.x`-stable wrapper (bytecodealliance; 17.4M downloads/week). **Compile-verified in this session** against `/mnt/archive`. Adds exactly **one** new leaf crate to this tree (`linux-raw-sys`). [VERIFIED: cargo run + Cargo.lock]', isNew: true },
    { name: 'tokio', version: '1.52.3', pinned: true, purpose: 'Runtime; `broadcast` bus; `time::interval`; `process::Command` for subprocess probes', why: 'Already in the tree; `broadcast` is ARCHITECTURE.md\'s chosen fan-out [VERIFIED: Cargo.lock]' },
    { name: 'axum', version: '0.8.9', pinned: true, purpose: '`/ws` handler (already built and hardened in Phase 1)', why: 'Already in the tree [VERIFIED: Cargo.lock]' },
    { name: 'serde / serde_json', version: '1.0.228 · 1.0.150', pinned: true, purpose: 'Tagged `Event` enum wire format (D-19); parsing `smartctl -j` and `rclone about --json`', why: 'Already in the tree [VERIFIED: Cargo.lock]' },
    { name: 'smartctl', host: true, version: '7.5 2025-04-30 r5714', purpose: 'SMART verdict + pending/reallocated sector counts', why: 'Installed at `/usr/sbin/smartctl`; supports `-j/--json` [VERIFIED: `smartctl --version`, `smartctl -h`]' },
    { name: 'rclone', host: true, version: 'v1.74.3', purpose: '`rclone about cloud: --json` for cloud quota', why: 'Installed at `/usr/local/bin/rclone`; remote `cloud:` (type `drive`) configured and authenticated [VERIFIED: `rclone version`, `rclone listremotes`]' },
  ],
  supporting: [
    { name: 'std::thread', version: 'std', purpose: 'One dedicated OS thread per tier prober', why: '**Preferred over `tokio::task::spawn_blocking`** for this phase — see F3 / Pitfall 3. tokio\'s own docs: "Use dedicated threads for long-lived or persistent blocking workloads" [CITED: docs.rs/tokio spawn_blocking]' },
    { name: 'tokio::sync::watch', version: 'bundled with tokio', purpose: 'Per-tier latest-snapshot cell feeding the broadcast bus + the on-connect snapshot (D-19)', why: 'ARCHITECTURE.md names `watch`/`broadcast`; `watch` is the natural fit for "latest value per tier"' },
    { name: 'tokio-util', version: '0.7.18', pinned: true, purpose: '`CancellationToken` for clean prober shutdown', why: 'Already in the tree [VERIFIED: Cargo.lock]' },
  ],
  alternatives: [
    { instead: '`rustix`', could: '`nix` 0.31.3', verdict: 'viable', tradeoff: 'Equally legitimate (11.5M downloads/week, `nix::sys::statvfs`). Choose `nix` only if the project later wants its broader POSIX surface; `rustix` has the smaller footprint here. Both clean per the legitimacy gate' },
    { instead: '`rustix`', could: '`libc::statvfs` directly', verdict: 'rejected', tradeoff: 'Zero new crates (`libc` already transitively present), but requires `unsafe` + manual `errno` handling for a syscall used on the phase\'s hot path. Not worth it' },
    { instead: '`rustix`', could: '**`sysinfo` 0.39.6**', verdict: 'harmful', tradeoff: '**Actively harmful here — do not use.** Its `Disks` API refreshes *every* mounted disk in one call, which structurally recouples all four tiers into a single operation: one wedged mount hangs the whole refresh. Rejected on isolation grounds, not maturity' },
    { instead: 'Dedicated `std::thread` per tier', could: '`tokio::task::spawn_blocking` + `timeout`', verdict: 'rejected', tradeoff: 'Simpler-looking, but leaks into tokio\'s *shared* 512-thread blocking pool and makes runtime shutdown wait indefinitely (F3).' },
    { instead: '`smartctl` subprocess', could: 'reading `smartd` state', verdict: 'rejected', tradeoff: 'Rejected in D-11 (adds a service, mail-oriented format, decouples freshness from our poll loop)' },
    { instead: '`rclone about` subprocess', could: '`rclone rcd` RC HTTP API', verdict: 'later', tradeoff: 'RC API is ARCHITECTURE.md\'s documented upgrade path but is scoped to **Phase 4** (job progress). For a single quota read per minute, a bounded subprocess is simpler. Do not pull Phase 4\'s daemon forward' },
  ],
  audit: {
    intro: 'Verdicts from `gsd-tools query package-legitimacy check --ecosystem crates`, cross-checked against `cargo search` and the crates.io API.',
    rows: [
      ['rustix','crates.io','~4.7 yrs','17,442,928','github.com/bytecodealliance/rustix','OK','','Approved — recommended'],
      ['nix','crates.io','~11.7 yrs','11,551,002','github.com/nix-rust/nix','OK','','Approved — viable alternative'],
      ['sysinfo','crates.io','~11 yrs','2,943,454','github.com/GuillaumeGomez/sysinfo','OK','','Rejected on design grounds, not legitimacy'],
      ['libc','crates.io','~11.5 yrs','22,736,502','github.com/rust-lang/libc','OK','','Already present transitively (0.2.186)'],
    ],
    slop: [],
    susNote: null,
    extra: ['**Postinstall scripts:** N/A (crates ecosystem; seam reported `postinstall: null` for all four)', '**Frontend:** this phase adds **no new npm packages**. shadcn copies component source into the repo; its peer deps are all already in `frontend/package.json` [VERIFIED: package.json].'],
  },
  diagramId: 'sp02-diagram',
  diagramNote: '**The load-bearing property:** every arrow *out* of a prober thread is non-blocking. A prober can hang forever in D-state and the only observable consequence is that its own tier\'s `probed_at` stops advancing — which the registry converts into `unreachable` for that tier alone. Nothing downstream ever calls *into* a tier.',
  treeId: 'sp02-tree',
  treeNote: 'Follows ARCHITECTURE.md §Recommended Project Structure (CONTEXT.md directs: follow unless there\'s a concrete reason not to).',
  patterns: [
    { title: 'Layered probe — cheap-and-safe before bounded-and-dangerous', what: 'Never make a device-touching syscall the *first* question. Order the probe by blast radius.' },
    { title: 'One dedicated OS thread per tier, not `spawn_blocking`', what: '`std::thread::spawn` one prober per tier at `init_state`. Each loops: sleep interval → probe → `watch::Sender::send` (never blocks) → repeat. The async side never awaits the thread; it reads the `watch` cell and applies a staleness deadline.' },
    { title: 'Explicit tier config — never auto-discover the SMART device', what: 'Declare each tier\'s mount path, SMART device path, and SMART device type explicitly in config. Do not derive the block device from the mount point at runtime.' },
  ],
  anti: [
    { lead: 'Treating `statvfs` success as proof the tier is alive.', rest: 'It is not. Proven: an unmounted tier returns the root filesystem\'s numbers in microseconds (F1). Always ask `/proc/self/mountinfo` first.' },
    { lead: '`output.status.success()` on `smartctl`.', rest: 'A failing drive exits non-zero *by design* (F2). This single line would break HEALTH-02 on archive.' },
    { lead: 'Using `sysinfo`/`Disks::refresh_list()` for capacity.', rest: 'Refreshes all disks in one call → recouples the tiers → Pitfall 6 reintroduced through a dependency.' },
    { lead: '`du` / recursive walk for capacity.', rest: 'Explicitly forbidden by D-17; catastrophic on a degraded mount.' },
    { lead: 'Unifying transfer behind the tier trait.', rest: 'ARCHITECTURE.md Anti-Pattern 1 — browse/stat only.' },
    { lead: 'Persisting health to SQLite.', rest: 'health is ephemeral/live-only.' },
    { lead: 'Relying on `tokio::process::Child` drop to kill a subprocess.', rest: 'It does not (Pitfall 4). `smartctl`/`rclone` need explicit `kill().await` + `wait().await`.' },
  ],
  handroll: [
    { problem: 'Filesystem capacity', dont: '`df` subprocess + stdout parsing', use: '`rustix::fs::statvfs`', why: 'A subprocess per tier per 5 s, with locale-dependent, column-aligned output — for data available as a µs syscall.' },
    { problem: 'SMART parsing', dont: 'Regex over `smartctl -a` human output', use: '`smartctl -j` (JSON) + `serde_json`', why: 'smartmontools ships structured JSON in 7.5 (verified present). Human output has no stability contract.' },
    { problem: 'SMART verdict semantics', dont: 'Custom "is it failing?" heuristics', use: '**Decode the documented exit bitmask** (F2)', why: 'The exit status *is* the machine-readable verdict, specified in the man page.' },
    { problem: 'Cloud quota', dont: 'Google Drive API client + OAuth', use: '`rclone about cloud: --json`', why: 'The remote is already configured and authenticated; the OAuth token stays in rclone\'s config.' },
    { problem: 'Mount liveness', dont: '`mountpoint`/`findmnt` subprocess', use: 'Read `/proc/self/mountinfo` directly', why: '0.14 ms, no subprocess, no PATH dependency, and gives `maj:min` + `ro` flags in the same read.' },
    { problem: 'Relative time ("4s ago")', dont: 'Custom tick/format logic sprinkled per card', use: 'One shared client hook + `Intl.RelativeTimeFormat`', why: 'UI-SPEC fixes exact thresholds; centralise so all four cards agree.' },
    { problem: 'Reconnect/backoff', dont: 'Ad-hoc `setTimeout` retry', use: 'One capped exponential-backoff helper (D-21)', why: 'Tickets are single-use, ~60 s TTL, cleared on restart; reconnect is the steady state, not an edge case.' },
  ],
  handrollInsight: 'every "don\'t" in this table is a case where the host already exposes a *structured, machine-readable* answer (a syscall, procfs, a JSON flag, an exit bitmask) and the tempting shortcut is to scrape a *human-readable* rendering of that same answer.',
  pitfalls: [
    { sev: 'CRITICAL', code: 'F1', title: 'An unmounted tier reports the root filesystem\'s capacity as its own', what: '`/mnt/vault` and `/mnt/archive` are mounted with `nofail`. When the drive is absent, the mount point is an ordinary empty directory on `/`. `statvfs("/mnt/archive")` then returns **`/`\'s numbers** — instantly, with no error. The archive card renders **healthy** at ~36% used with ~62 GB free. Every value is fiction.', why: 'The locked design reasons about the *wedged* mount. But `nofail` produces the opposite failure: not a hang, a **fast wrong answer**.', avoid: 'check `/proc/self/mountinfo` for the mount point **before** trusting any capacity reading.', signs: 'a tier card showing ~98 GiB total (that is `/`, not any tier); two tiers reporting identical total/free.' },
    { sev: 'CRITICAL', code: 'F2', title: '`smartctl` exits non-zero on a failing drive; naive error handling turns `degraded` into `unreachable`', what: '`smartctl`\'s exit status is a **bitmask**. Archive is SMART-failed, so `smartctl` will exit with **bit 3 set** — non-zero. Idiomatic Rust maps that to a probe failure, collapsing `degraded` into `unreachable`.', why: 'non-zero exit means failure in every other subprocess this codebase will ever spawn. `smartctl` inverts that convention.', avoid: 'never branch on `status.success()`. Extract the raw code and mask it.', signs: 'archive\'s card showing `unreachable` while `/mnt/archive` is mounted and `statvfs` returns real numbers.' },
    { sev: 'CRITICAL', code: 'F3', title: '`spawn_blocking` is uncancellable *and* blocks runtime shutdown forever', what: 'two documented tokio behaviours compound: abort has no effect on a `spawn_blocking` task, and runtime shutdown waits indefinitely for them. A wedged archive makes the process **unable to shut down**.', why: '`spawn_blocking` is the reflexive answer to "I have a blocking syscall in an async program," and it is correct for *short* blocking work.', avoid: 'dedicated `std::thread` per tier (Pattern 2). Additionally, set `TimeoutStopSec` explicitly in the systemd unit.', signs: '`systemctl restart` taking ~90 s; `ps -eLo state | grep D`; probe intervals visibly drifting.' },
    { sev: 'HIGH', code: 'F4', title: 'rclone\'s own timeout flags cannot bound wall-clock; defaults allow multi-minute hangs', what: 'Worst case is many minutes for a probe on a ~60 s interval. First `rclone about cloud: --json` of the session took **35.5 s**; subsequent calls **0.78 s**.', why: '`--timeout` reads like a deadline. It is an idle timer.', avoid: 'bound from the parent, and treat rclone flags as defence-in-depth only.', signs: 'cloud card flapping to `unreachable` on a rough hourly cadence; `pgrep rclone` showing accumulating processes.' },
    { sev: 'HIGH', code: 'F5', title: '`/dev/sdX` names are unstable — SMART can report the wrong drive\'s health', what: 'config pins `/dev/sdc` for archive; a replug or reboot re-enumerates and `/dev/sdc` is now vault (or nothing).', avoid: 'use `/dev/disk/by-id/usb-Seagate_One_Touch_w_PW_…` (serial-bound) in both the tier config *and* the sudoers grant.', signs: 'archive\'s SMART verdict changing after a replug with no physical cause.' },
    { sev: 'MEDIUM', code: 'F8', title: '`used/total` is not the percentage `df` shows', what: 'ext4 reserves blocks for root. Naive `used/total` disagrees with `df`, `studio-status`, and the member\'s mental model.', avoid: 'compute as `df` does — `pct = used / (used + avail)`. Note the denominator is **not** `total`.' },
    { sev: 'MEDIUM', code: 'F9', title: 'Google Drive\'s `used` understates consumed quota', what: '`used` (169 GB) excludes `other` (48 GB — Gmail/Google Photos, which *do* consume the shared 5 TB quota). Rendering `used` as "used" understates by 48 GB and makes the bar disagree with its own free/total line.', avoid: 'cloud `used = total − free`. This is both authoritative and semantically consistent with the local tiers\' df-style computation.' },
    { sev: 'MEDIUM', code: null, title: 'Reintroducing a banner, an `unknown` state, or capacity warnings', what: 'The user made three explicit calls against recommendation. Guard them in review.', avoid: '**D-09:** red card only — **no page-level banner**. **D-12/D-13:** exactly **three** states. Capacity-threshold warnings — **do not add without asking**, even though vault at 85% makes it tempting.' },
  ],
  questionsHeading: 'Open Questions',
  questions: [
    { title: 'Can `smartctl` actually read vault — and is archive genuinely SMART-FAILED?', blocks: 'blocks HEALTH-02\'s completeness', resolved: false, body: '**the plan must open with a `checkpoint:human-verify` task** — run, with the user present, on the host. **Do not plan SMART parsing tasks before it lands.** If vault has no SMART: this is a **user decision, not Claude\'s** — it changes UI copy.' },
    { title: 'What parent deadline for the cloud probe?', blocks: 'Claude\'s discretion, but evidence is incomplete', resolved: false, body: 'start at **`CLOUD_PROBE_DEADLINE = 45s`** with a `60s` interval (deadline < interval keeps D-16 from starving the tier).' },
    { title: 'Should an exFAT `errors=remount-ro` flip surface as `degraded`?', resolved: false, body: '**do not add it as an alarm criterion without asking**. Capture the `ro` flag in the frame now (it costs nothing) and raise the question with the user during planning.' },
    { title: 'Should this phase fix WR-04 (`API_ORIGIN` hardcoded)?', resolved: false, body: 'fold it in — reading `NEXT_PUBLIC_API_ORIGIN` with the current value as fallback is a few lines in code that is being replaced regardless. Planner\'s call.' },
  ],
  env: [
    { dep: '`smartctl`', by: 'HEALTH-02', ok: true, ver: '7.5 2025-04-30 r5714', fb: '—' },
    { dep: '`smartctl` JSON (`-j`)', by: 'HEALTH-02', ok: true, ver: 'supported in 7.5', fb: '—' },
    { dep: 'NOPASSWD sudo for `smartctl`', by: 'HEALTH-02 (D-11)', ok: false, ver: 'only `/usr/bin/smbstatus` is NOPASSWD', fb: 'None — blocking.', blocking: true },
    { dep: '`rclone`', by: 'HEALTH-01 (cloud)', ok: true, ver: 'v1.74.3', fb: '—' },
    { dep: 'rclone remote `cloud:`', by: 'HEALTH-01 (cloud)', ok: true, ver: 'type `drive`, authenticated', fb: '—' },
    { dep: '`/mnt/stage`', by: 'HEALTH-01', ok: true, ver: 'ext4 on LVM, 363.1 GiB, 53% used', fb: '—' },
    { dep: '`/mnt/vault`', by: 'HEALTH-01', ok: true, ver: 'exFAT on `/dev/sda2`, 1863.0 GiB, 85% used', fb: '—' },
    { dep: '`/mnt/archive`', by: 'HEALTH-01/02', ok: true, ver: 'exFAT on `/dev/sdc2`, 4657.2 GiB, 79% used', fb: '—' },
    { dep: 'Rust toolchain', by: 'backend', ok: true, ver: 'cargo/rustc 1.96.0', fb: '—' },
    { dep: 'Node/npm + shadcn CLI', by: 'D-05/D-06', ok: true, ver: 'shadcn 4.13.0, Next 16.2.10', fb: '—' },
    { dep: 'Frontend test framework', by: 'Nyquist validation', ok: false, ver: 'none', fb: 'See Validation Architecture — Wave 0' },
    { dep: 'systemd unit for backend', by: 'deployment', ok: false, ver: 'does not exist yet', fb: 'None — blocking', blocking: true },
    { dep: 'Dedicated non-root service user', by: 'D-11 / Pitfall 10', ok: false, ver: 'only `cinedise` and `studio`', fb: 'None — blocking.', blocking: true },
  ],
  envNotes: ['All probed directly on the target host (`cinedise`) during this session.'],
  runtime: null,
  sources: {
    primary: ['`man smartctl` §EXIT STATUS (smartmontools 7.5, local) — the exit bitmask (F2). **The single most important source for this phase.**', '`smartctl --version` / `--scan` / `--scan-open` / `-h` — version, JSON support, and vault\'s omission from the scan (F6)', '`rclone version` / `rclone about cloud: --json` / `rclone help flags` — live quota, JSON shape, default timeouts (F4, F9)', '`/proc/self/mountinfo`, `/etc/fstab`, `lsblk`, `ls -l /dev/disk/by-id/` — tier→device map, `nofail`, stable naming', '**Executed measurements:** `statvfs` 0.002–0.012 ms; `/proc/self/mountinfo` 0.14 ms; `rclone about` 35.5 s cold / 0.78 s warm', '**Compile-and-run:** `rustix 1.1.4` `statvfs` against real `/mnt/archive`', '`gsd-tools query package-legitimacy check --ecosystem crates` — OK ×4'],
    secondary: ['docs.rs/tokio · `spawn_blocking` — uncancellable; shutdown waits indefinitely', 'docs.rs/tokio · `Builder::max_blocking_threads` — default 512', 'docs.rs/tokio · `sync::broadcast` — `Lagged` advances the receiver (F12)', 'docs.rs/rustix · `fs::statvfs` — signature', 'Project research: `.planning/research/{PITFALLS,ARCHITECTURE,STACK}.md`'],
    tertiary: ['smartmontools#526 — SanDisk Extreme Portable SSD support', 'smartmontools#275 — Unknown USB bridge', 'Reading SMART on a Samsung Portable SSD T7 (claudiokuenzler.com)', 'SMART on external USB drives — openmediavault forum', 'scrutiny#45 — allow device type for devices not found in scan'],
  },
  constraints: {
    locked: [
      { group: null, ids: ['D-01','D-02','D-03','D-04','D-05','D-06','D-07','D-08','D-09','D-10','D-11','D-12','D-13','D-14','D-15','D-16','D-17','D-18','D-19','D-20','D-21'] },
    ],
    discretion: ['**Exact interval values** for each probe type, and whether they\'re env-configurable vs. compile-time constants.', '**Tier configuration shape** — how mount paths, SMART device paths, and the rclone remote name are declared.', '**The canary timeout value** (N seconds) and blocking-thread budget per tier.', '**Broadcast bus lag handling** — what happens to a slow WS client that falls behind.', '**How a tier transitions back to `healthy`** after recovery.', '**Frame wire format** (JSON shape, Event enum variant naming) and the module layout.', '**Capacity-threshold warnings** were not discussed — do not add without asking.'],
    deferred: ['None raised — discussion stayed within phase scope.'],
  },
  requirements: [
    ['HEALTH-01','Member can see live capacity (used/free) for all four tiers (stage, vault, archive, cloud) in one view','§Capacity Probing — `rustix::fs::statvfs` compile-verified against real tiers'],
    ['HEALTH-02','Member can see local-drive health (SMART status, pending sectors) with a prominent alert when a drive is failing','§SMART Probing — `smartctl -j` bitmask exit-code decoding (F2)'],
    ['HEALTH-03','Status updates live over WebSocket without a page reload','§Live Push — existing ticket-authorized `/ws` handler, `tokio::broadcast` fan-out'],
    ['HEALTH-04','A single unreachable or dead tier never hangs status for the healthy tiers','§Unreachable Detection — **F1**, F3'],
  ],
  respMap: [
    ['Capacity read (`statvfs`)','API / Backend (host-integrated)','—'],
    ['Mount liveness / reachability','API / Backend','—'],
    ['SMART health read','API / Backend (privileged subprocess)','OS (sudoers grant)'],
    ['Cloud quota read','API / Backend (`rclone` subprocess)','External (Google Drive API)'],
    ['Health state aggregation & fan-out','API / Backend (`tokio::broadcast`)','—'],
    ['Live transport','Browser ↔ API/Backend (direct WSS)','—'],
    ['Ticket mint','Frontend Server (Next.js) → API','—'],
    ['Rendering, relative-age ticking, reconnect','Browser / Client','—'],
  ],
  sourceOnly: [['Installation', 'Standard Stack'], ['Version verification', 'Standard Stack'], ['Code Examples', '5 blocks'], ['State of the Art', ''], ['Assumptions Log', ''], ['Validation Architecture', ''], ['Security Domain', ''], ['Project Constraints', ''], ['Metadata', '']],
},
};

/* SYNTHETIC — no real RESEARCH.md in either project has removed a package yet. This overlay adds
   two invented removals and one extra SUS so the audit's worst case can be judged. The names are
   made up and flagged as such in the UI. */
window.SYNTHETIC_AUDIT = {
  slop: [
    { name: 'react-markdown-safe-render', reason: 'no source repository; published 9 days ago; 212 downloads/wk; name shadows `react-markdown` + `rehype-sanitize`', replacedBy: 'unified + rehype-sanitize (already in stack)' },
    { name: 'hono-sse-toolkit', reason: 'repo link 404s; single maintainer created 3 weeks ago; postinstall script fetches a remote binary', replacedBy: 'Hono\'s built-in `streamSSE`' },
  ],
  rows: [
    ['react-markdown-safe-render','npm','9d','212','—','SLOP','no-repo, too-new','Removed'],
    ['hono-sse-toolkit','npm','3w','1,048','404','SLOP','postinstall, no-repo','Removed'],
  ],
};
