// Generated by gen-data.mjs from real PATTERNS.md files — do not edit by hand.
const DOCS = {
 "sp02": {
  "project": "studio-portal",
  "label": "sp v1.0/02 (hard)",
  "file": "02-PATTERNS.md",
  "phase": "2",
  "title": "Storage Health & Status",
  "mapped": "2026-07-17",
  "filesAnalyzed": "24 new/modified",
  "analogsFound": "15 / 24 (9 with no analog)",
  "preNotes": [
   "**Verification note:** every claim CONTEXT.md § Existing Code Insights makes about existing\npatterns was checked against the real code, not taken on trust. All four named precedents\n(`spawn_sweeper`, `FIRST_MESSAGE_GRACE`, the `lib.rs`/`main.rs` split, per-concern integration\ntests) are **confirmed** — with one important qualification on `spawn_sweeper` (see § Shared\nPatterns → Detached Background Task, and the **divergence warning** attached to it).\n**The backend has no subprocess-spawning code at all.** `grep -rn \"Command\" backend/src` returns\nzero hits. `smartctl` and `rclone` are the project's first subprocesses; there is no in-repo\nprecedent for spawning, bounding, killing, or reaping a child. Likewise `broadcast`/`watch`:\nzero hits in `backend/src` — the bus is greenfield. Plan accordingly; RESEARCH.md § Code Examples\nis the reference for these, not the codebase."
  ],
  "files": [
   {
    "file": "`backend/src/health/mod.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "model",
    "flow": "transform",
    "analog": "`backend/src/tickets/store.rs` (types + consts + `mod.rs` re-export shape)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/src/health/collector.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "service",
    "flow": "event-driven / polling",
    "analog": "`backend/src/tickets/store.rs::spawn_sweeper`",
    "q": "partial",
    "qNote": "see divergence"
   },
   {
    "file": "`backend/src/health/smart.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "service",
    "flow": "subprocess / transform",
    "analog": "**none** — first subprocess in the repo",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/mod.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "model / config",
    "flow": "transform",
    "analog": "`backend/src/tickets/mod.rs` + `store.rs` type block",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/local.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "service",
    "flow": "file-I/O",
    "analog": "**none** — first filesystem-probing module",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/rclone_tier.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "service",
    "flow": "subprocess",
    "analog": "**none** — first subprocess in the repo",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/ws/bus.rs`",
    "group": "Backend — new modules (greenfield)",
    "role": "provider",
    "flow": "pub-sub",
    "analog": "**none** — no `broadcast`/`watch` anywhere in tree",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/lib.rs`",
    "group": "Backend — modified",
    "role": "config / wiring",
    "flow": "—",
    "analog": "**itself** (extend in place; `init_state` already spawns a background task)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/config.rs`",
    "group": "Backend — modified",
    "role": "config",
    "flow": "—",
    "analog": "**itself** (`Config::from_env` env-var + safe-default convention)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/ws/mod.rs`",
    "group": "Backend — modified",
    "role": "route / handler",
    "flow": "pub-sub",
    "analog": "**itself** (replace the echo loop at lines 51–58 only)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/Cargo.toml`",
    "group": "Backend — modified",
    "role": "config",
    "flow": "—",
    "analog": "itself (`cargo add rustix@1.1.4 --features fs`)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/tests/tier_isolation.rs`",
    "group": "Backend — tests & fixtures",
    "role": "test (integration)",
    "flow": "event-driven",
    "analog": "`backend/tests/ws_ticket_flow.rs`",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/tests/ws_health_flow.rs`",
    "group": "Backend — tests & fixtures",
    "role": "test (integration)",
    "flow": "request-response",
    "analog": "`backend/tests/ws_ticket_flow.rs`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "unit tests in `health::*` / `tiers::*`",
    "group": "Backend — tests & fixtures",
    "role": "test (unit)",
    "flow": "transform",
    "analog": "`backend/src/tickets/store.rs` § `mod tests` (lines 164–317)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/fixtures/smartctl-{failing,healthy,nvme}.json`",
    "group": "Backend — tests & fixtures",
    "role": "fixture",
    "flow": "—",
    "analog": "`backend/fixtures/spike-fixture.txt` (path convention only)",
    "q": "partial",
    "qNote": null
   },
   {
    "file": "`backend/fixtures/rclone-about.json`",
    "group": "Backend — tests & fixtures",
    "role": "fixture",
    "flow": "—",
    "analog": "same",
    "q": "partial",
    "qNote": null
   },
   {
    "file": "`frontend/app/page.tsx` (rewrite)",
    "group": "Frontend",
    "role": "component (client)",
    "flow": "streaming / event-driven",
    "analog": "`frontend/app/page.tsx` (current — for the mint→connect→ticket flow **only**)",
    "q": "partial",
    "qNote": null
   },
   {
    "file": "`frontend/app/layout.tsx` (modify)",
    "group": "Frontend",
    "role": "component (root layout)",
    "flow": "—",
    "analog": "itself",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/ui/{card,badge,progress,alert,skeleton}.tsx`",
    "group": "Frontend",
    "role": "component (primitive)",
    "flow": "—",
    "analog": "**none installed** — generated by `npx shadcn add`, do not hand-write",
    "q": "none",
    "qNote": "generated"
   },
   {
    "file": "`frontend/components/tier-card.tsx`",
    "group": "Frontend",
    "role": "component",
    "flow": "—",
    "analog": "**none** — first real component in the repo",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`frontend/components/nav-shell.tsx`",
    "group": "Frontend",
    "role": "component",
    "flow": "—",
    "analog": "**none**",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`frontend/components/connection-indicator.tsx`",
    "group": "Frontend",
    "role": "component",
    "flow": "—",
    "analog": "**none**",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`frontend/lib/use-health-socket.ts`",
    "group": "Frontend",
    "role": "hook",
    "flow": "streaming",
    "analog": "`frontend/app/page.tsx::connectWs` (lines 27–70)",
    "q": "partial",
    "qNote": null
   },
   {
    "file": "`frontend/lib/use-relative-time.ts`",
    "group": "Frontend",
    "role": "hook",
    "flow": "transform",
    "analog": "**none**",
    "q": "none",
    "qNote": null
   },
   {
    "file": "systemd unit (backend service)",
    "group": "Ops artifacts",
    "role": "config",
    "flow": "—",
    "analog": "**none in repo.** Host has `studio-proxy-dashboard.service` — an **anti-precedent** (`User=root`)",
    "q": "none",
    "qNote": null
   },
   {
    "file": "sudoers grant for `smartctl`",
    "group": "Ops artifacts",
    "role": "config",
    "flow": "—",
    "analog": "**none in repo.** Host's only NOPASSWD entry is `/usr/bin/smbstatus`",
    "q": "none",
    "qNote": null
   }
  ],
  "noAnalog": [
   {
    "file": "`backend/src/health/smart.rs`",
    "reason": "**Zero subprocess code in the repo** (`grep -rn \"Command\" backend/src` → no hits). No precedent for spawning, bounding, killing, or reaping a child. Use RESEARCH § Code Examples (bitmask decode, lines 524–564). F2 is the phase's #1 correctness trap and has no guardrail in existing code"
   },
   {
    "file": "`backend/src/tiers/rclone_tier.rs`",
    "reason": "Same. Use RESEARCH lines 566–594 (parent `timeout` + explicit `kill().await` + `wait().await` — `tokio::process::Child` does **not** kill on drop)"
   },
   {
    "file": "`backend/src/tiers/local.rs`",
    "reason": "No filesystem-probing code exists; `rustix` is a new dependency. Use RESEARCH § Code Examples (`statvfs` — compile-and-run verified; `/proc/self/mountinfo` parse, lines 472–518). F1 has no precedent to copy"
   },
   {
    "file": "`backend/src/ws/bus.rs`",
    "reason": "No `broadcast`/`watch` anywhere in `backend/src`. Use RESEARCH lines 596–617 + ARCHITECTURE.md § Component Responsibilities"
   },
   {
    "file": "`frontend/components/tier-card.tsx`",
    "reason": "`frontend/` has 2 `.tsx` files and no `components/`. First real component in the project. Use UI-SPEC § Layout / § Copywriting / § Screen-Reader contracts"
   },
   {
    "file": "`frontend/components/{nav-shell,connection-indicator}.tsx`",
    "reason": "Same. No nav or status-chip precedent"
   },
   {
    "file": "`frontend/lib/use-relative-time.ts`",
    "reason": "No hooks exist. UI-SPEC § Copywriting fixes the exact thresholds; RESEARCH § Don't Hand-Roll says centralize on one shared hook + `Intl.RelativeTimeFormat` so all four cards and D-14's \"last seen\" stamp agree"
   },
   {
    "file": "**systemd unit**",
    "reason": "**First of its kind in this repo.** No unit file exists in-tree. The host's `studio-proxy-dashboard.service` is an **anti-precedent** — RESEARCH line 632: *\"runs as `User=root` — a precedent on this box, but the **wrong** one... Do not copy that unit file.\"* `cloudflared.service` is a second anti-precedent (tunnel token inline in `ExecStart`, world-readable via `systemctl cat`). Requirements come from RESEARCH § Environment Availability: dedicated non-root service user, explicit `TimeoutStopSec` (Pitfall 3), `EnvironmentFile=` for secrets"
   },
   {
    "file": "**sudoers grant**",
    "reason": "**First of its kind in this repo.** Host's only NOPASSWD entry today is `/usr/bin/smbstatus` — unrelated shape, not a precedent for a device-read grant. Exact argv to whitelist is at RESEARCH lines 557–564, and is **gated on the Open Q1 `checkpoint:human-verify`** (lines 646–656), which resolves A1, A2, and the exact arg vector at once"
   }
  ],
  "noAIntro": "Files with no close match in the codebase. Planner: use RESEARCH.md / UI-SPEC.md patterns, not\ncodebase inference.",
  "assignments": [
   {
    "heading": "`backend/src/health/collector.rs` (service, event-driven)",
    "targets": [
     "backend/src/health/collector.rs"
    ],
    "tail": "(service, event-driven)",
    "analog": "`backend/src/tickets/store.rs::spawn_sweeper` — **partial match, read the divergence warning.**",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**⚠ DIVERGENCE WARNING — do not copy this analog's mechanism**\n`spawn_sweeper` uses **`tokio::spawn`**. RESEARCH.md § Pattern 2 (F3) requires the tier probers\nuse a **dedicated `std::thread` per tier — explicitly NOT `tokio::spawn`/`spawn_blocking`**,\nbecause the sweeper's work (a mutex + `retain` over a HashMap) can never block, while a prober's\nwork (`statvfs` on a wedged USB mount) can block **forever in D-state**.\n**Copy from this analog:**\n- the *shape*: named interval constant → detached loop → tick → do work → repeat\n- the \"skip the immediate first tick\" comment-and-code idiom\n- the \"detached — the handle is dropped; the task runs for the process lifetime\" framing\n- the doc-comment density: what it does, what failure it prevents, which decision ID\n**Do NOT copy:**\n- `tokio::spawn` / the async runtime binding (use `std::thread::spawn`)\n- `tokio::time::interval` inside the prober (use `std::thread::sleep`; the thread is not async)\n- returning a `JoinHandle` for lifecycle (a prober thread is *never* joined — D-15 accepts it as leaked)",
     "**What the collector's *async* side may still copy verbatim** — the registry/staleness-watchdog task\nis pure in-memory work with no device contact, so it **is** a true `spawn_sweeper` analog and should\nuse `tokio::spawn` + `tokio::time::interval` exactly as above."
    ],
    "excerpts": 2
   },
   {
    "heading": "`backend/src/health/mod.rs` (model, transform)",
    "targets": [
     "backend/src/health/mod.rs"
    ],
    "tail": "(model, transform)",
    "analog": "`backend/src/tickets/store.rs` type block (lines 24–65) — role-match.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Note: **every variant and every field carries its own doc comment.** Match that density —\n`TierState::Degraded` must document that it means \"reachable but SMART-failing (D-12), and must\nnever collapse into `Unreachable`\".",
     "Existing wire timestamps are **unix seconds as `u64`** (`TicketMeta::expires_at`,\n`TicketResponse::exp`, `Claims::exp`). `probed_at` should match — do not introduce an\nRFC3339 string or a `chrono` dependency for one field."
    ],
    "excerpts": 3
   },
   {
    "heading": "`backend/src/ws/bus.rs` (provider, pub-sub)",
    "targets": [
     "backend/src/ws/bus.rs"
    ],
    "tail": "(provider, pub-sub)",
    "analog": null,
    "applyTo": null,
    "useInstead": "RESEARCH.md § Code Examples → \"`broadcast` lag handling\" (lines 596–617), which resolves the `Lagged` discretion item with a cited tokio-docs rationale.",
    "guidance": [
     "**Analog: NONE.** `grep -rn \"broadcast\\|watch::\" backend/src` returns exactly one hit — a comment in\n`ws/mod.rs` line 52 saying this is a later phase's job. There is no fan-out precedent in the tree.",
     "**Do borrow the tagged-enum serde style from** `backend/src/auth/mod.rs` (lines 23–37) — the repo's\nonly serde-derive precedent, and it uses field-level `#[serde(default)]` attributes with per-field\ndocs:"
    ],
    "excerpts": 2
   },
   {
    "heading": "`backend/src/ws/mod.rs` (route/handler, pub-sub) — MODIFY",
    "targets": [
     "backend/src/ws/mod.rs"
    ],
    "tail": "(route/handler, pub-sub) — MODIFY",
    "analog": "itself. **The auth boundary is done — do not rebuild it.**",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Replace with: send snapshot (D-19) → subscribe → forward frames, with `Lagged` → resend snapshot\nper RESEARCH.md lines 598–617. The comment above it is a literal pointer to this phase.",
     "Every new tunable — `CLOUD_PROBE_DEADLINE` (45 s), `CAPACITY_PROBE_INTERVAL`, `SMART_PROBE_INTERVAL`,\n`CANARY_TIMEOUT`, `STALENESS_DEADLINE` — gets this exact treatment: a doc comment naming **the\nconcrete failure it prevents**, not just what the number is."
    ],
    "excerpts": 3
   },
   {
    "heading": "`backend/src/lib.rs` (config/wiring) — MODIFY",
    "targets": [
     "backend/src/lib.rs"
    ],
    "tail": "(config/wiring) — MODIFY",
    "analog": "itself. The header's \"OWNED and FINALIZED by Plan 01-01\" scopes to *Phase 1's* module wiring; extending for Phase 2 is expected (CONTEXT.md § Canonical References).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Every field is either `Clone`-cheap by construction (`TicketStore` = `Arc<Mutex<..>>` newtype) or\n`Arc`-wrapped. New fields must hold that invariant — `broadcast::Sender` is already cheap to clone;\nthe snapshot registry needs the `Arc<Mutex<HashMap<..>>>` newtype treatment.",
     "Per-tier probers spawn here, alongside the sweeper, with the same `let _x_handle = ...` +\ndecision-citing comment shape."
    ],
    "excerpts": 4
   },
   {
    "heading": "`backend/src/config.rs` (config) — MODIFY",
    "targets": [
     "backend/src/config.rs"
    ],
    "tail": "(config) — MODIFY",
    "analog": "itself. Tier mount paths, `by-id` SMART device paths, device types, and the rclone remote name land here (RESEARCH § Pattern 3).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Two conventions to match exactly:\n1. `env::var(\"X\").unwrap_or_else(|_| default)` — **never** `.expect()`. `from_env` never\npanics; validation is a separate `assert_safe_startup` concern (see docs at lines 41–43).\n2. **The uppercase \"NEVER default to X\" comment naming the danger.** Tier config's equivalent:\n*never* default a SMART device to `/dev/sdX` — `by-id` only, because enumeration has already\nshifted on this box (F5).",
     "**Hard-gate-at-startup precedent** — `backend/src/auth/mod.rs::assert_safe_startup` (lines 105–132)\nis the pattern if the phase wants to refuse boot on a dangerous tier config (e.g. a `/dev/sdX`\ndevice path). It panics with a message that states **the failure it prevents**, not just the rule:"
    ],
    "excerpts": 3
   },
   {
    "heading": "`backend/tests/ws_health_flow.rs` (test, integration)",
    "targets": [
     "backend/tests/ws_health_flow.rs"
    ],
    "tail": "(test, integration)",
    "analog": "`backend/tests/ws_ticket_flow.rs` — **exact match.** Same transport, same auth, same harness needs.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**This is a struct literal, not `..Config::from_env()`.** Adding tier-config fields to `Config`\n**breaks every one of these builders at compile time** — `ws_ticket_flow.rs`, `download_ticket.rs`,\nand `jwt_verification.rs` each have their own copy. That is a feature (the compiler forces each\ntest to declare its tier config), but the planner must budget for it: **a `Config` field addition\nis a multi-file change.** Contrast `lib.rs` line 108–111, which *does* use\n`..Config::from_env()` spread and will not break.",
     "Note it **returns `AppState`** so the test can mint tickets directly, bypassing the JWT-gated HTTP\nendpoints. `ws_health_flow.rs` needs the same trick, plus a handle to inject health frames."
    ],
    "excerpts": 4
   },
   {
    "heading": "`backend/tests/tier_isolation.rs` (test, integration) — the phase's highest-value test",
    "targets": [
     "backend/tests/tier_isolation.rs"
    ],
    "tail": "(test, integration) — the phase's highest-value test",
    "analog": "`ws_ticket_flow.rs` for the harness (above) — role-match. **No analog for the fault injection itself**; nothing in the repo fakes a dependency in-process.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "The one adjacent precedent for *deterministic control over timing-sensitive state* is\n`store.rs::consume_expired_ticket_fails` (lines 187–201), which reaches into private state rather\nthan sleeping:",
     "And `concurrent_consume_exactly_one_wins` (lines 211–249) shows the repo's `std::thread` +\n`Barrier` idiom for forcing a real race — the nearest thing to the \"wedged prober\" simulation\nRESEARCH.md line 733 requires:"
    ],
    "excerpts": 2
   },
   {
    "heading": "`backend/fixtures/*.json` (fixture)",
    "targets": [
     "backend/fixtures/*.json"
    ],
    "tail": "(fixture)",
    "analog": "`backend/fixtures/spike-fixture.txt` — path convention only.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Referenced via a compile-time path (`backend/src/download/mod.rs` line 21):",
     "Use `concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/fixtures/...\")` — or `include_str!` for parse-only unit\ntests, which is stricter (fails at compile time if the fixture is missing)."
    ],
    "excerpts": 1
   },
   {
    "heading": "`frontend/app/page.tsx` (component, streaming) — REWRITE",
    "targets": [
     "frontend/app/page.tsx"
    ],
    "tail": "(component, streaming) — REWRITE",
    "analog": "its own current contents — **partial.** The page is being replaced (D-03/D-07); only the mint→connect→ticket-first-message *mechanism* survives.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**Gate:** `frontend/AGENTS.md` (the whole file): *\"This is NOT the Next.js you know. This version\nhas breaking changes — APIs, conventions, and file structure may all differ from your training\ndata. Read the relevant guide in `node_modules/next/dist/docs/` before writing any code.\"*\nNext 16.2.10 + React 19.2.4. **This existing file is itself unverified against that warning** —\nit is a spike. Treat its React idioms as unvetted; treat only its *protocol sequence* as proven\n(it was validated cross-origin against the real deployment).",
     "Three things are load-bearing and must survive the rewrite:\n- `credentials: \"include\"` on the mint (the Access cookie is the auth)\n- ticket sent as the **first WS message**, never in the URL\n- **a fresh mint per reconnect attempt** (D-21 / RESEARCH § ASVS V3) — tickets are single-use;\nthe whole `connectWs` body must re-run on each backoff attempt, never just the `new WebSocket(...)`"
    ],
    "excerpts": 4
   },
   {
    "heading": "`frontend/app/layout.tsx` (component, root layout) — MODIFY",
    "targets": [
     "frontend/app/layout.tsx"
    ],
    "tail": "(component, root layout) — MODIFY",
    "analog": "itself — exact.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Current state (lines 1–18, 30–37) — `shadcn init` already wired the preset's fonts alongside the\nNext-template Geist fonts:",
     "Two jobs here per UI-SPEC § Design System: **remove the dead Geist imports/variables** (no longer\nthe active `--font-sans`/`--font-heading` source; flagged as opportunistic cleanup, not a\nrequirement), and mount the nav shell (D-03) so `/browse`+`/jobs` inherit it in Phase 3/4.\n`body` already has `min-h-full flex flex-col` — the 56px header + content column drops straight in."
    ],
    "excerpts": 3
   },
   {
    "heading": "`frontend/components/ui/*.tsx` (component, primitive)",
    "targets": [
     "frontend/components/ui/*.tsx"
    ],
    "tail": "(component, primitive)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**Analog: NONE — and none is wanted.** These are **generated**, not written:",
     "`components.json` is committed and configured; the aliases below tell you where generated files\nland and how to import them:"
    ],
    "excerpts": 2
   },
   {
    "heading": "`frontend/components/{tier-card,nav-shell,connection-indicator}.tsx` (component)",
    "targets": [
     "frontend/components/{tier-card,nav-shell,connection-indicator}.tsx"
    ],
    "tail": "(component)",
    "analog": null,
    "applyTo": null,
    "useInstead": "`02-UI-SPEC.md` is the authority and is unusually complete — it locks card anatomy (§ Layout), the exact lucide icons per state (§ Non-color state redundancy), copy strings (§ Copywriting Contract), the aria contract (§ Screen-Reader / Live-Region Contract), and the reduced-motion rules (§ Motion). Treat it as the spec, not a suggestion.",
    "guidance": [
     "**Analog: NONE.** `frontend/` contains exactly two `.tsx` files (`layout.tsx`, `page.tsx`) and no\n`components/` directory. This phase creates the project's first real component tree — there is no\nin-repo convention for component file naming, prop typing, or client/server boundaries to copy.",
     "Precedents that *do* transfer:\n- **`cn()`** from `@/lib/utils` for class composition (above)\n- **`\"use client\"`** as line 1 for anything holding a socket or timer (`page.tsx` line 1) — note\n`components.json` sets `\"rsc\": true`, so components are **server** by default and must opt in\n- The union-type state enum idiom (`page.tsx` line 11)"
    ],
    "excerpts": 0
   }
  ],
  "shared": [
   {
    "name": "Named tunable constants that cite the failure they prevent",
    "source": "`backend/src/ws/mod.rs:18-22`, `backend/src/tickets/store.rs:27-44`",
    "applyTo": "every constant in `health/`, `tiers/`, `ws/bus.rs`",
    "rule": "The comment states **the failure**, the **relationship to another constant** (\"well under the ~60s\nTTL\"), and the **decision ID**. `CLOUD_PROBE_DEADLINE` should read the same way: *45s — above a real\nOAuth token refresh (measured 35.5s cold) and below the 60s probe interval, so D-16's skip-overlapping-ticks\nrule cannot starve the tier (F4: rclone's own `--timeout` is an idle timer and cannot bound wall clock).*\nCONTEXT.md § Claude's Discretion names this convention explicitly for that constant.",
    "excerpts": 1
   },
   {
    "name": "Doc comments that cite decision IDs and pitfalls",
    "source": "every backend module. Verified: 30+ citations of `D-NN` / `Pitfall N` / `T-01-NN` / `WR-0N` / `CR-0N` across `lib.rs`, `ws/mod.rs`, `auth/`, `download/`, `tickets/`, `db/`, `config.rs`.",
    "applyTo": "every new backend file.",
    "rule": "Module-header exemplar (`backend/src/ws/mod.rs:1-7`):",
    "excerpts": 1
   },
   {
    "name": "Detached background task",
    "source": "`backend/src/lib.rs:89-92` (spawn site) + `backend/src/tickets/store.rs:118-138` (impl)",
    "applyTo": "the health registry / staleness watchdog task **only**",
    "rule": "⚠ **Not applicable to the per-tier probers** — they must be `std::thread`, not `tokio::spawn`\n(RESEARCH § Pattern 2 / F3). See the divergence warning under `health/collector.rs`. CONTEXT.md\nnames `spawn_sweeper` as \"the per-tier prober precedent\"; that is true of its **shape** and false of\nits **mechanism**, and the mechanism is the part that decides whether a wedged archive can hang\n`systemctl restart` for 90 seconds.",
    "excerpts": 1
   },
   {
    "name": "Reject/fail identically — never leak internals",
    "source": "`backend/src/ws/mod.rs:42-49`, `backend/src/tickets/store.rs:99-116`, `backend/src/download/mod.rs:41-46`, `backend/src/auth/mod.rs:45-54`",
    "applyTo": "every probe-failure path in `health/`, `tiers/`",
    "rule": "Four independent instances make this an unambiguous project convention, and it maps directly onto\nRESEARCH § Security Domain V7 (\"map probe failures to the opaque `unreachable` state; log details\nserver-side only, scrubbed\"). `AuthError`'s docs (lines 45–48) state the principle most plainly:",
    "excerpts": 1
   },
   {
    "name": "`lib.rs` + thin `main.rs` split",
    "source": "`backend/src/main.rs:1-6`, `backend/src/lib.rs:1-11`",
    "applyTo": "all health logic — it must be `cargo test --lib`-reachable (0.02s for 25 tests today)",
    "rule": "`main.rs` is 28 lines and does exactly four things: read config, build state, bind, serve. Keep it\nthat way — prober spawning belongs in `init_state`/`spawn_probers`, not `main`.",
    "excerpts": 1
   },
   {
    "name": "Unit tests colocated in `#[cfg(test)] mod tests`",
    "source": "`backend/src/tickets/store.rs:164-317` (10 tests), `config.rs:78-97`, `lib.rs:102-121`, `auth/mod.rs:160-197`",
    "applyTo": "`health::smart` (bitmask decode), `health::capacity` (df-math), `tiers::local` (mountinfo), `tiers::rclone_tier` (JSON parse) — all of RESEARCH's Wave-0 unit-test map",
    "rule": "Assertions carry a **message explaining the invariant**, not just a boolean:",
    "excerpts": 1
   }
  ],
  "other": [
   {
    "title": "Cross-Cutting Notes for the Planner",
    "items": [
     "**`Config` field additions are a 4-file change.** `Config` is constructed by struct literal in `ws_ticket_flow.rs`, `download_ticket.rs`, `jwt_verification.rs`, and `config.rs`'s own test — each breaks at compile time on a new field. Only `lib.rs:108-111` uses `..Config::from_env()` spread. Compile-time breakage is the desired behavior; just budget the task for it.",
     "**`init_state` is called by tests, not just `main`.** Integration tests build `AppState` by hand (`ws_ticket_flow.rs:36-57`) and bypass `init_state` — but any test that *does* call it would inherit unconditional prober spawning against real `/mnt/*` and real `smartctl`. Make prober spawning injectable/opt-in. This is the same seam RESEARCH.md line 733 demands for `tier_isolation.rs`, so it pays for itself twice.",
     "**Two conventions actively conflict with this phase's research, and research wins:** - `spawn_sweeper`'s `tokio::spawn` vs. RESEARCH's required `std::thread` per tier (F3) - \"reject identically / opaque failures\" vs. D-10's required specific reason line (locked user decision; scoped exception for `degraded` only) Both should be called out **in code comments** where they diverge, in the established decision-citing style — otherwise a reviewer holding the Phase 1 conventions will read them as mistakes.",
     "**The frontend has no verified pattern to copy — only a spike and a warning.** `frontend/AGENTS.md` says the installed Next.js differs from training data and that `node_modules/next/dist/docs/` must be read before writing code. The existing `page.tsx` predates any such verification. Its *protocol sequence* is proven against the real deployment; its *React/Next idioms* are not. Every frontend task needs the docs-read step (D-07, and RESEARCH § Project Constraints marks it **Mandatory**).",
     "**Base UI, not Radix.** `components.json` → `\"style\": \"base-sera\"` → primitives are backed by `@base-ui/react` 1.6.0. Training-data shadcn examples assume Radix and will not match the generated source. Read the generated component file before composing with it. ---"
    ]
   }
  ],
  "scope": "`backend/src/**` (14 files), `backend/tests/**` (4 files), `frontend/app/**`, `frontend/lib/**`, `frontend/components.json`, `frontend/AGENTS.md`, plus repo-wide searches for `Command`/`spawn_blocking`/`std::thread`/`broadcast`/`watch::`, `*.service`/`*sudoers*`/`*.conf`, and `deploy|ops|infra|scripts|systemd` directories.",
  "scanned": "24 read in full (all ≤ 333 lines); 6 targeted greps.",
  "lines": 981
 },
 "sp04": {
  "project": "studio-portal",
  "label": "sp P4 (grouped)",
  "file": "04-PATTERNS.md",
  "phase": "4",
  "title": "Bulk Archive Downloads",
  "mapped": "2026-08-21",
  "filesAnalyzed": "29 new/modified files",
  "analogsFound": "28 / 29",
  "preNotes": [],
  "files": [
   {
    "file": "`backend/Cargo.toml`",
    "group": null,
    "role": "config",
    "flow": "build-time",
    "analog": "existing dependency entries in the same file",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/migrations/0005_archive_jobs.sql` (suggested)",
    "group": null,
    "role": "migration",
    "flow": "CRUD",
    "analog": "`backend/migrations/0002_jobs_and_audit.sql`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/config.rs`",
    "group": null,
    "role": "config",
    "flow": "transform",
    "analog": "its `max_download_bytes` policy",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/mod.rs`",
    "group": null,
    "role": "model/store",
    "flow": "CRUD",
    "analog": "its `JobAction`, `Tool`, `Job`, `insert_job`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/executors/mod.rs`",
    "group": null,
    "role": "service interface",
    "flow": "event-driven",
    "analog": "`JobExecutor` / `ExecutorHandle`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/executors/archive.rs`",
    "group": null,
    "role": "service",
    "flow": "file-I/O, event-driven",
    "analog": "`backend/src/jobs/executors/rsync.rs`",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/worker.rs`",
    "group": null,
    "role": "service",
    "flow": "event-driven",
    "analog": "existing rsync/rclone dispatch",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/recovery.rs`",
    "group": null,
    "role": "service",
    "flow": "batch, file-I/O",
    "analog": "`reconcile_rows`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/jobs/audit.rs`",
    "group": null,
    "role": "model/service",
    "flow": "event-driven",
    "analog": "existing `AuditAction` + `record`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/browse/local.rs`",
    "group": null,
    "role": "service/utility",
    "flow": "file-I/O, batch",
    "analog": "`list_local` / `list_local_bounded`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/browse/cloud.rs`",
    "group": null,
    "role": "service",
    "flow": "request-response, batch",
    "analog": "existing `rclone lsjson` listing",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/src/tiers/browse/mod.rs`",
    "group": null,
    "role": "utility",
    "flow": "transform",
    "analog": "`bridge_blocking`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/api/jobs.rs`",
    "group": null,
    "role": "controller",
    "flow": "request-response, CRUD",
    "analog": "`create_job` and job detail DTO",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/download/mod.rs`",
    "group": null,
    "role": "controller/service",
    "flow": "request-response, streaming",
    "analog": "`serve_local`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/tickets/mint.rs`",
    "group": null,
    "role": "controller",
    "flow": "request-response",
    "analog": "`mint_dl_ticket` pre-mint refusal",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/lib.rs`",
    "group": null,
    "role": "route/config",
    "flow": "request-response",
    "analog": "existing `/api/jobs/{id}/*` routes",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/tests/archive_preflight.rs` (suggested)",
    "group": null,
    "role": "test",
    "flow": "request-response, file-I/O",
    "analog": "`backend/tests/job_scope_enforcement.rs`",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/tests/archive_executor.rs` (suggested)",
    "group": null,
    "role": "test",
    "flow": "file-I/O, event-driven",
    "analog": "`backend/tests/job_cancellation.rs`",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/tests/archive_download.rs` (suggested)",
    "group": null,
    "role": "test",
    "flow": "request-response, streaming",
    "analog": "`backend/tests/download_ticket.rs`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/tests/job_crash_recovery.rs`",
    "group": null,
    "role": "test",
    "flow": "batch, file-I/O",
    "analog": "existing recovery cases in same file",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/tests/route_auth_coverage.rs`",
    "group": null,
    "role": "test",
    "flow": "request-response",
    "analog": "`ROUTE_TABLE` in same file",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/lib/archive-download.ts` (suggested)",
    "group": null,
    "role": "utility",
    "flow": "request-response, transform",
    "analog": "`browse-view.tsx::postJob` + `download-affordance.tsx::handleDownload`",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`frontend/lib/archive-download.test.ts` (suggested)",
    "group": null,
    "role": "test",
    "flow": "transform",
    "analog": "`frontend/lib/browse-path.test.ts`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/archive-refusal-dialog.tsx` (suggested)",
    "group": null,
    "role": "component",
    "flow": "event-driven",
    "analog": "`frontend/components/collision-dialog.tsx`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/download-affordance.tsx`",
    "group": null,
    "role": "component",
    "flow": "request-response, event-driven",
    "analog": "its existing ticket flow",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/browse-row.tsx`",
    "group": null,
    "role": "component",
    "flow": "event-driven",
    "analog": "its shared `onDownload(entry)` callback",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/selection-bar.tsx`",
    "group": null,
    "role": "component",
    "flow": "event-driven",
    "analog": "its `onSendTo` action",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/browse-view.tsx`",
    "group": null,
    "role": "component/controller",
    "flow": "request-response, event-driven",
    "analog": "`handleSendTo(entries, fromSelection)`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/components/job-row.tsx`, `frontend/components/job-history-row.tsx`, `frontend/app/jobs/page.tsx`",
    "group": null,
    "role": "component/page",
    "flow": "event-driven, request-response",
    "analog": "Cancel/Retry/Resume shared action wiring",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/lib/use-jobs-socket.ts`, `frontend/lib/use-jobs-list.ts`",
    "group": null,
    "role": "hook",
    "flow": "event-driven, request-response",
    "analog": "existing terminal frame merge",
    "q": "exact",
    "qNote": null
   }
  ],
  "noAnalog": [
   {
    "file": "`backend/src/jobs/executors/archive.rs` (ZIP serialization details only)",
    "reason": "No in-process archive writer exists. Use `04-RESEARCH.md`'s pinned `zip` 8.6.0 example for `SimpleFileOptions`, fixed metadata, `large_file(true)`, ordered entries, and `finish()`. Lifecycle still follows `RsyncExecutor`."
   }
  ],
  "noAIntro": null,
  "assignments": [
   {
    "heading": "Archive schema and job model",
    "targets": [],
    "tail": "Archive schema and job model",
    "analog": "`backend/migrations/0002_jobs_and_audit.sql`",
    "applyTo": "`backend/migrations/0005_archive_jobs.sql`, `backend/src/jobs/mod.rs`, `backend/src/jobs/audit.rs`",
    "useInstead": null,
    "guidance": [
     "Copy the additive, decision-numbered migration style. Extend the job row with owner/archive metadata and add normalized `archive_entries` and `archive_omissions` child tables. Preserve DB-level closed sets while adding `archive` to both action and tool. Use `(job_id, ordinal)` and `(job_id, entry_name)` uniqueness, indexes on foreign keys used for ordered lookup/sweeping, and cascading or explicit lifecycle consistent with existing SQLite setup.",
     "Add exhaustive `Archive` arms; never coerce unknown strings. Give `OnCollision` the same closed deserialization behavior for HARDEN-01 and keep the SQL `CHECK` as defense in depth."
    ],
    "excerpts": 3
   },
   {
    "heading": "Archive executor and worker dispatch",
    "targets": [],
    "tail": "Archive executor and worker dispatch",
    "analog": "`backend/src/jobs/executors/rsync.rs`",
    "applyTo": "`backend/src/jobs/executors/archive.rs`, `backend/src/jobs/executors/mod.rs`, `backend/src/jobs/worker.rs`, `backend/Cargo.toml`",
    "useInstead": null,
    "guidance": [
     "Add a structurally distinct archive handle; retain concrete dispatch rather than introducing trait objects. The archive executor should own a dedicated blocking thread, cancellation signal, progress snapshot, and held `TierRoot` handles.",
     "Archive-specific differences: query manifest `ORDER BY ordinal`; reopen each file through `TierRoot` immediately before copy; normalize entry names before persistence; write `_archives/{job_id}.partial`; call `ZipWriter::finish`, flush/sync, then atomic rename to `{job_id}.zip`; update progress from uncompressed bytes copied; record vanished/symlink/unreadable entries as structured omissions. Cancel/error calls one idempotent partial cleanup helper. Pin `zip = 8.6.0` with only the researched feature set, and force stable timestamp/compression/permissions plus `large_file(true)`."
    ],
    "excerpts": 2
   },
   {
    "heading": "Recursive manifest walkers",
    "targets": [],
    "tail": "Recursive manifest walkers",
    "analog": "`backend/src/tiers/browse/local.rs`",
    "applyTo": "`backend/src/tiers/browse/local.rs`, `backend/src/tiers/browse/cloud.rs`, `backend/src/tiers/browse/mod.rs`",
    "useInstead": null,
    "guidance": [
     "Add a separately named archive-preflight deadline comfortably below the tunnel timeout. Local recursion stays on one `TierRoot`; never follow symlinks and never return partial totals. Cloud walking follows the existing cloud parser/process discipline but performs one `rclone lsjson -R -- remote:path` call. Unlike browse display, reject unknown/negative cloud sizes rather than clamping them to zero. Stable-sort normalized entry names before persistence."
    ],
    "excerpts": 2
   },
   {
    "heading": "Archive creation, ownership, omission detail, and HARDEN-01",
    "targets": [],
    "tail": "Archive creation, ownership, omission detail, and HARDEN-01",
    "analog": "`backend/src/api/jobs.rs::create_job`",
    "applyTo": "`backend/src/api/jobs.rs`, `backend/src/tickets/mint.rs`, `backend/src/lib.rs`, `backend/src/config.rs`",
    "useInstead": null,
    "guidance": [
     "Replace free-string `on_collision` with a closed request enum. Prefer a separate `CreateArchiveRequest { source_tier, source_paths }`: destination and collision fields must not be client-supplied. Return a closed refusal body with backend-authored `error` text plus real `selected_bytes/limit_bytes` or `required_bytes/free_bytes`. Include omission paths/count and ownership-safe collection state in job detail/WS DTOs.",
     "Mirror this with `MAX_ARCHIVE_BYTES`, default `400 * 1024 * 1024 * 1024`, including fixture updates and a default/override regression test."
    ],
    "excerpts": 3
   },
   {
    "heading": "Recovery, cancellation, and sweep",
    "targets": [],
    "tail": "Recovery, cancellation, and sweep",
    "analog": "`backend/src/jobs/recovery.rs::reconcile_rows` (lines 102-153)",
    "applyTo": "`backend/src/jobs/recovery.rs`, `backend/src/jobs/worker.rs`, archive persistence helpers",
    "useInstead": null,
    "guidance": [
     "Special-case `Tool::Archive`: unlink `.partial`, always mark `Interrupted`, and never apply copy auto-resume. Preserve completed final ZIPs across boot. The 24-hour sweep should query durable completed timestamps, skip active collection leases, unlink stale final artifacts idempotently, and make DB state reflect that collection is no longer available."
    ],
    "excerpts": 1
   },
   {
    "heading": "HTTP range serving and archive lifetime",
    "targets": [],
    "tail": "HTTP range serving and archive lifetime",
    "analog": "`backend/src/download/mod.rs::serve_local`",
    "applyTo": "`backend/src/download/mod.rs`, `backend/src/tickets/mint.rs`",
    "useInstead": null,
    "guidance": [
     "Reuse it directly for archive-friendly names; do not fork encoding.",
     "Extend, do not replace, this path: parse exactly one byte range; seek and `take(length)`; return 200/206/416 with exact `Content-Length`, `Accept-Ranges`, and `Content-Range`. Add an explicit body wrapper/stream state that unlinks only after true EOF. Early consumer drop retains the immutable final ZIP for a re-minted Range request. Ticket consumption remains atomic at serve start. Serialize active collection leases so sweep/concurrent tickets cannot unlink an in-flight artifact."
    ],
    "excerpts": 2
   },
   {
    "heading": "Browse download orchestration",
    "targets": [],
    "tail": "Browse download orchestration",
    "analog": "`frontend/components/download-affordance.tsx` (lines 76-105)",
    "applyTo": "`frontend/lib/archive-download.ts`, its test, `download-affordance.tsx`, `browse-row.tsx`, `selection-bar.tsx`, `browse-view.tsx`",
    "useInstead": null,
    "guidance": [
     "Extract one reusable direct-download helper so the row button, row context menu, and exactly-one-file bulk branch all mint and navigate identically. Keep the >500 MiB branch as a dialog state, not the retired card.",
     "Build `handleDownload(entries)` from the passed entries, never by rereading `selection` later. Pure-test the routing predicate: exactly one non-folder => direct; folder or 2+ entries => archive. Archive refusal leaves the selection intact. Delete `downloadEntry` and its card block."
    ],
    "excerpts": 4
   },
   {
    "heading": "Refusal and completed-job actions",
    "targets": [],
    "tail": "Refusal and completed-job actions",
    "analog": "`frontend/components/collision-dialog.tsx` (lines 53-68, 91-106)",
    "applyTo": "`frontend/components/archive-refusal-dialog.tsx`, `job-row.tsx`, `job-history-row.tsx`, `frontend/app/jobs/page.tsx`, `use-jobs-socket.ts`, `use-jobs-list.ts`",
    "useInstead": null,
    "guidance": [
     "Use one dialog for over-cap and insufficient-space responses, displaying the backend-authored real numbers. Dismissal must not clear selection.",
     "Add `Download` only for completed archive jobs with a collectable artifact and use one shared job-ticket helper from tray, history, and completion auto-start. Key auto-start on a transition/new completion frame, not every render or REST refresh; guard against duplicate starts during socket reconnect. Render omission count plus expandable exact paths in both tray/history detail."
    ],
    "excerpts": 2
   }
  ],
  "shared": [
   {
    "name": "Authorization and containment",
    "source": "`backend/src/api/jobs.rs`, `backend/src/tiers/scope.rs`, `backend/src/tickets/mint.rs`",
    "applyTo": null,
    "rule": "Apply source `Read` at archive creation; do not require stage `Write`. Persist creator identity and enforce owner equality at archive ticket mint. Every manifest walk and execution-time open goes through `TierRoot`; persisted paths are work descriptions, not authority. `_archives/` hiding in browse must be paired with explicit generic-ticket denial.",
    "excerpts": 0
   },
   {
    "name": "Errors and validation",
    "source": null,
    "applyTo": null,
    "rule": "Bounded operations fail closed and return no partial sum. Backend responses own user-facing refusal wording and exact numbers. Wire choices are closed enums, backed by SQL checks. Bound selected-root count, path length, manifest rows, request size, duplicates, normalized ZIP names, and cloud unknown sizes before insertion.",
    "excerpts": 0
   },
   {
    "name": "Progress and events",
    "source": null,
    "applyTo": null,
    "rule": "Reuse `bytes_total`, `bytes_done`, `progress_pct`, `current_file`, `last_heartbeat_at`, existing WS broadcasts, `TierLocks(source, stage)`, and the job tray. Count uncompressed bytes copied, not ZIP output bytes. Use `job_events`/structured omission rows rather than inventing a downloads subsystem.",
    "excerpts": 0
   },
   {
    "name": "Testing",
    "source": null,
    "applyTo": null,
    "rule": "Backend integration tests should copy the real-router/temp-tier/SQLite fixtures from `download_ticket.rs`, `job_scope_enforcement.rs`, `job_cancellation.rs`, and `job_crash_recovery.rs`. Frontend logic belongs in framework-free `frontend/lib/*.ts` with adjacent `node:test` files; component source-contract checks may supplement but not replace pure routing/copy tests.",
    "excerpts": 0
   }
  ],
  "other": [],
  "scope": "`backend/src`, `backend/tests`, `backend/migrations`, `frontend/components`, `frontend/lib`, `frontend/app/jobs`",
  "scanned": "93 candidate source/test/migration files; analog search stopped after five strong pattern families.",
  "lines": 420
 },
 "sp01": {
  "project": "studio-portal",
  "label": "sp P1",
  "file": "01-PATTERNS.md",
  "phase": "1",
  "title": "Portal-Owned Identity & Sessions",
  "mapped": "2026-08-03",
  "filesAnalyzed": "15",
  "analogsFound": "13 / 15",
  "preNotes": [],
  "files": [
   {
    "file": "`backend/src/auth/mod.rs` (swap body)",
    "group": null,
    "role": "middleware (extractor)",
    "flow": "request-response",
    "analog": "itself (existing `FromRequestParts` impl)",
    "q": "exact",
    "qNote": "modify in place"
   },
   {
    "file": "`backend/src/auth/session.rs` (NEW)",
    "group": null,
    "role": "service",
    "flow": "CRUD + request-response",
    "analog": "`backend/src/tickets/store.rs` (token issuance/consume discipline) + `backend/src/api/audit.rs` (handler idiom)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/src/auth/jwt.rs`",
    "group": null,
    "role": "—",
    "flow": "—",
    "analog": "DELETE wholesale",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/auth/dev_bypass.rs` (modify)",
    "group": null,
    "role": "utility",
    "flow": "request-response",
    "analog": "itself",
    "q": "exact",
    "qNote": "modify identity shape"
   },
   {
    "file": "`backend/src/bin/backstage.rs` (NEW)",
    "group": null,
    "role": "CLI / utility",
    "flow": "CRUD",
    "analog": "none in-repo (first bin target) — model on `main.rs`'s config/state bootstrap + `session.rs`'s hashing fns",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/ratelimit/mod.rs` (NEW)",
    "group": null,
    "role": "middleware",
    "flow": "request-response",
    "analog": "none in-repo (first rate-limit layer) — `tickets/store.rs`'s CSPRNG/`Mutex<HashMap>` discipline for the hand-rolled per-handle counter",
    "q": "partial",
    "qNote": null
   },
   {
    "file": "`backend/migrations/0003_accounts_and_sessions.sql` (NEW)",
    "group": null,
    "role": "migration",
    "flow": "CRUD",
    "analog": "`backend/migrations/0002_jobs_and_audit.sql`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`backend/src/db/mod.rs`",
    "group": null,
    "role": "config",
    "flow": "—",
    "analog": "itself (no change needed, only consumed)",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`backend/src/lib.rs` (modify router + CORS)",
    "group": null,
    "role": "route wiring",
    "flow": "request-response",
    "analog": "itself",
    "q": "exact",
    "qNote": "modify in place"
   },
   {
    "file": "`backend/src/main.rs` (modify — connect_info)",
    "group": null,
    "role": "config/bootstrap",
    "flow": "—",
    "analog": "itself",
    "q": "exact",
    "qNote": "modify in place"
   },
   {
    "file": "`backend/tests/session_auth_flow.rs` (NEW)",
    "group": null,
    "role": "test",
    "flow": "request-response",
    "analog": "`backend/src/auth/dev_bypass.rs`'s `#[cfg(test)]` module pattern + existing `tests/ws_ticket_flow.rs`/`download_ticket.rs` shape",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`backend/tests/session_durability.rs` (NEW)",
    "group": null,
    "role": "test",
    "flow": "file-I/O",
    "analog": "`backend/tests/db_durability.rs`",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`frontend/proxy.ts` (NEW)",
    "group": null,
    "role": "middleware (route gate)",
    "flow": "request-response",
    "analog": "none in-repo (first proxy/middleware file) — model on `send-to-dialog.tsx`'s `fetch(..., { credentials: \"include\" })` convention for the validation call",
    "q": "none",
    "qNote": null
   },
   {
    "file": "`frontend/app/login/page.tsx` (NEW)",
    "group": null,
    "role": "component (route)",
    "flow": "request-response",
    "analog": "`frontend/components/send-to-dialog.tsx` (form state/submit/error pattern)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`frontend/app/change-password/page.tsx` (NEW)",
    "group": null,
    "role": "component (route)",
    "flow": "request-response",
    "analog": "`frontend/components/send-to-dialog.tsx` (form state/submit/error pattern)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`frontend/components/nav-shell.tsx` (modify)",
    "group": null,
    "role": "component",
    "flow": "request-response",
    "analog": "itself",
    "q": "exact",
    "qNote": "modify in place"
   }
  ],
  "noAnalog": [
   {
    "file": "`backend/src/bin/backstage.rs`",
    "reason": "First binary target in this crate — no existing CLI to model beyond reusing `main.rs`'s config/panic conventions and `auth::session`'s hashing functions directly"
   },
   {
    "file": "`frontend/proxy.ts`",
    "reason": "First proxy/middleware file in this repo — RESEARCH.md's own Code Examples/Architecture Diagram section is the closest thing to a template; the fetch-call sub-pattern inside it is covered by `send-to-dialog.tsx`"
   },
   {
    "file": "`backend/src/ratelimit/mod.rs`'s `CfConnectingIpExtractor`",
    "reason": "No existing `tower_governor`/rate-limit code in this codebase — RESEARCH.md Pattern 4 supplies a complete, already-scoped illustrative implementation; treat that as the canonical starting point rather than a further in-repo search"
   }
  ],
  "noAIntro": null,
  "assignments": [
   {
    "heading": "`backend/src/auth/mod.rs` (middleware/extractor, request-response)",
    "targets": [
     "backend/src/auth/mod.rs"
    ],
    "tail": "(middleware/extractor, request-response)",
    "analog": "itself — swap the body of `FromRequestParts for VerifiedIdentity`, keep the contract.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [],
    "excerpts": 2
   },
   {
    "heading": "`backend/src/auth/session.rs` (NEW — service, CRUD + request-response)",
    "targets": [
     "backend/src/auth/session.rs"
    ],
    "tail": "(NEW — service, CRUD + request-response)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**Analog 1 — token/store discipline:** `backend/src/tickets/store.rs`",
     "Reuse verbatim for session-token generation (32 random bytes, hex-encoded) per RESEARCH's explicit recommendation — this is the exact discipline to copy for the `sessions.id` value, just persisted to SQLite instead of an in-memory map, and with a sliding-expiry UPDATE (D-01) instead of single-use consume."
    ],
    "excerpts": 4
   },
   {
    "heading": "`backend/src/auth/dev_bypass.rs` (modify — utility)",
    "targets": [
     "backend/src/auth/dev_bypass.rs"
    ],
    "tail": "(modify — utility)",
    "analog": "itself. Keep `fixed_identity()`'s shape and the `#[cfg(test)]` module structure (`backend/src/auth/dev_bypass.rs:1-151`) verbatim — only change the return type from JWT `Claims` to the new session-shaped `Identity` struct (carrying `user_id`, `must_change_password: false`, handle `\"dev@cinedise\"` or similar). Every existing test in this file (`dev_loopback_ok`, `dev_mode_panics_on_prod_bind`, `production_mode_panics_without_access_config`) should be preserved and adapted, not rewritten from scratch — they already assert exactly the invariants D-10's hard gate needs.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [],
    "excerpts": 0
   },
   {
    "heading": "`backend/src/bin/backstage.rs` (NEW — CLI, no analog)",
    "targets": [
     "backend/src/bin/backstage.rs"
    ],
    "tail": "(NEW — CLI, no analog)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "No existing binary target or CLI in this repo (`backend/Cargo.toml` declares zero `[[bin]]` entries; `main.rs` is the only binary today). Model the bootstrap shape on:",
     "`backstage` should share `db::init_pool` and `auth::session::{hash_password, ...}` directly (D-05 — \"sharing the db and auth modules with the server\"), not duplicate hashing/DB logic."
    ],
    "excerpts": 2
   },
   {
    "heading": "`backend/src/ratelimit/mod.rs` (NEW — middleware, request-response)",
    "targets": [
     "backend/src/ratelimit/mod.rs"
    ],
    "tail": "(NEW — middleware, request-response)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "No existing rate-limit layer in this codebase. Partial analog: `backend/src/tickets/store.rs`'s `Arc<Mutex<HashMap<...>>>` shape for the hand-rolled per-handle counter (RESEARCH Assumption A2 — `tower_governor`'s `KeyExtractor` is IP-shaped, not handle-shaped):",
     "The `Cf-Connecting-Ip`-reading `KeyExtractor` implementation is provided verbatim in RESEARCH.md Pattern 4 (`backend/src/ratelimit/mod.rs` illustrative shape) — copy directly, it is already scoped to this file path by the research pass."
    ],
    "excerpts": 1
   },
   {
    "heading": "`backend/migrations/0003_accounts_and_sessions.sql` (NEW — migration)",
    "targets": [
     "backend/migrations/0003_accounts_and_sessions.sql"
    ],
    "tail": "(NEW — migration)",
    "analog": "`backend/migrations/0002_jobs_and_audit.sql` (full file read, lines 1-89)",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Apply the same pattern to any closed-set column the new tables need (none obviously required for `users`/`sessions`, but keep this convention in mind if a status/role-shaped column appears — RESEARCH explicitly calls this out as the house style to follow).",
     "`0003` needs an index on `sessions(id)` (already the PK, likely free) and probably `sessions(user_id)` for the D-03 cascade-delete-on-password-change query and `users(handle)` for the normalized-handle uniqueness lookup — follow the same one-line-comment-per-index convention."
    ],
    "excerpts": 2
   },
   {
    "heading": "`backend/tests/session_durability.rs` (NEW — test, file-I/O)",
    "targets": [
     "backend/tests/session_durability.rs"
    ],
    "tail": "(NEW — test, file-I/O)",
    "analog": "`backend/tests/db_durability.rs` (not read in full this pass, but its pattern is explicitly named in RESEARCH.md as the direct model: \"AUTH-06 ... modeled directly on `db_durability.rs`'s drop-pool-without-close pattern\"). Also see `backend/src/db/mod.rs`'s own `#[cfg(test)]` module (lines 81-199) for the `TempDb` real-file-not-`:memory:` fixture pattern this durability test needs (WAL mode is only observable against a real file): ```rust // backend/src/db/mod.rs:98-121 — TempDb fixture pattern to reuse/extend struct TempDb { config: Config } impl TempDb { fn new(test_name: &str) -> Self { /* real temp-file path, not :memory: */ } } impl Drop for TempDb { fn drop(&mut self) { for suffix in [\"\", \"-wal\", \"-shm\"] { let _ = std::fs::remove_file(...); } } } ```",
    "applyTo": null,
    "useInstead": null,
    "guidance": [],
    "excerpts": 1
   },
   {
    "heading": "`backend/tests/session_auth_flow.rs`, `forced_password_change.rs`, `login_enumeration_safety.rs`, `login_rate_limit.rs` (NEW — tests, request-response)",
    "targets": [
     "backend/tests/session_auth_flow.rs",
     "forced_password_change.rs",
     "login_enumeration_safety.rs",
     "login_rate_limit.rs"
    ],
    "tail": "(NEW — tests, request-response)",
    "analog": "`backend/src/auth/dev_bypass.rs`'s `#[cfg(test)]` module (full file, lines 18-151) for the `AppState`-construction-per-test convention: ```rust let state = AppState { pool, tickets: TicketStore::new(), verifier: Verifier::empty(), config: Arc::new(config), bus: HealthBus::new(), health_registry: HealthRegistry::new(), job_executors: Arc::new(crate::jobs::worker::build_executors()), }; ``` Every new integration test needs this same full `AppState` assembly (now including whatever session/db fields land) — copy the shape exactly, including the `dev_loopback_config()`-style helper function for building a minimal valid `Config`.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Every new integration test needs this same full `AppState` assembly (now including whatever session/db fields land) — copy the shape exactly, including the `dev_loopback_config()`-style helper function for building a minimal valid `Config`."
    ],
    "excerpts": 1
   },
   {
    "heading": "`frontend/proxy.ts` (NEW — route gate, request-response)",
    "targets": [
     "frontend/proxy.ts"
    ],
    "tail": "(NEW — route gate, request-response)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "No `middleware.ts`/`proxy.ts` exists in this repo today (confirmed by RESEARCH). This is Next.js 16's renamed convention (`export function proxy(...)`, not `middleware`) — no in-repo analog for the file shape itself. For the backend-validation `fetch` call inside it, copy the credentialed-fetch convention already established in:",
     "`proxy.ts` needs the same `API_ORIGIN` constant convention, `credentials: \"include\"`, and a short explicit timeout (D-10 — use `AbortSignal.timeout(ms)`, no analog for this specific piece exists in-repo yet). On any non-ok response OR thrown error, fail closed to `/login` per D-11 — mirror the `catch { setError(...) }` shape's *intent* (never let a network failure fall through to \"treat as authenticated\")."
    ],
    "excerpts": 1
   },
   {
    "heading": "`frontend/app/login/page.tsx`, `frontend/app/change-password/page.tsx` (NEW — component/route, request-response)",
    "targets": [
     "frontend/app/login/page.tsx",
     "frontend/app/change-password/page.tsx"
    ],
    "tail": "(NEW — component/route, request-response)",
    "analog": "`frontend/components/send-to-dialog.tsx` (full file) — closest existing form-with-submit-and-error-state component in this codebase.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Use this exact `Alert`/`AlertTitle` pattern for the login failure/429/D-11 notices — UI-SPEC's Copywriting Contract already specifies the exact copy per state; this is the component shape to render it in. `/login` additionally needs `AlertAction` (already imported by `send-to-dialog.tsx:7`) for the rate-limit case's implicit disabled-submit countdown (no retry button needed there, but the same `Alert` composition applies).",
     "**Submit-disabled + spinner convention** — referenced in UI-SPEC as sourced from `job-row.tsx`/`connection-indicator.tsx` (not read this pass; UI-SPEC already quotes the exact class string): `RefreshCw` icon with `motion-safe:animate-spin motion-reduce:animate-pulse`, bound directly to the pending `fetch` promise — same rule `send-to-dialog.tsx`'s `submitting`-gated button follows (`disabled={submitting}` on line 281)."
    ],
    "excerpts": 2
   },
   {
    "heading": "`frontend/components/nav-shell.tsx` (modify — component)",
    "targets": [
     "frontend/components/nav-shell.tsx"
    ],
    "tail": "(modify — component)",
    "analog": "itself — insert the new display-name span + `Separator` + logout `Button` into the existing right-hand cluster (`nav-shell.tsx:203-211`): ```tsx <div className=\"flex shrink-0 items-center gap-2\"> <ThemeToggle /> <ConnectionIndicator state={connectionState} /> </div> ``` UI-SPEC's NavShell Addition section specifies inserting before `ThemeToggle`. Follow this file's existing conventions exactly: `Separator orientation=\"vertical\"` (already used at line 162 for the brand/nav break — same variant, hidden below 640px), `Button variant=\"ghost\" size=\"icon-sm\"` matching `ThemeToggle`'s own precedent, `hidden ... sm:inline` responsive-hide convention already used throughout this file (e.g. line 154's `hidden h-5 w-auto sm:block`).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "UI-SPEC's NavShell Addition section specifies inserting before `ThemeToggle`. Follow this file's existing conventions exactly: `Separator orientation=\"vertical\"` (already used at line 162 for the brand/nav break — same variant, hidden below 640px), `Button variant=\"ghost\" size=\"icon-sm\"` matching `ThemeToggle`'s own precedent, `hidden ... sm:inline` responsive-hide convention already used throughout this file (e.g. line 154's `hidden h-5 w-auto sm:block`)."
    ],
    "excerpts": 1
   }
  ],
  "shared": [
   {
    "name": "Fail-closed discipline (applies to every backend auth-adjacent file)",
    "source": "`backend/src/auth/mod.rs:105-154` (`assert_safe_startup`, `is_loopback_bind`) and `backend/src/db/mod.rs` (`init_pool`'s `unwrap_or_else(|err| panic!(...))`).",
    "applyTo": "`auth/mod.rs`, `auth/session.rs`, `ratelimit/mod.rs`, `bin/backstage.rs` — any unresolvable/unverifiable state is treated as unsafe/rejected, never defaulted to permissive. Example: `is_loopback_bind`'s `Err(_) => false` branch.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "`{ \"error\": \"...\" }` JSON error-body convention",
    "source": "`backend/src/api/audit.rs:66-73` (`ErrorResponse`, `error_response` helper).",
    "applyTo": "every new handler in `auth/session.rs` (`login_handler`, `logout_handler`, `change_password_handler`).",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "CSPRNG token generation via `rand::rng().fill_bytes` + hex-encode",
    "source": "`backend/src/tickets/store.rs:29, 124-128, 231-237` (`hex_encode` helper + `mint`'s byte-fill call).",
    "applyTo": "`auth/session.rs`'s session-token generation (D-01) — reuse the exact 32-byte/hex-encode shape, not a new scheme.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "Migration rationale-header + closed-enum-CHECK convention",
    "source": "`backend/migrations/0001_init.sql:1-5`, `backend/migrations/0002_jobs_and_audit.sql:1-8, 18, 29-31`.",
    "applyTo": "`backend/migrations/0003_accounts_and_sessions.sql`.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "Credentialed same-site fetch convention (frontend)",
    "source": "`frontend/components/send-to-dialog.tsx:29, 147-171` (`API_ORIGIN` const + `fetch(..., { credentials: \"include\" })`).",
    "applyTo": "`proxy.ts`'s backend validation call, `/login`'s submit handler, `/change-password`'s submit handler, `nav-shell.tsx`'s new logout handler (`POST /logout`).",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "Plain `useState` form pattern, no form library",
    "source": "`frontend/components/send-to-dialog.tsx` (whole file — `folderName`/`folderSubmitting`/`folderError` trio, submit-only validation).",
    "applyTo": "`/login/page.tsx`, `/change-password/page.tsx`.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "`#[cfg(test)]` module + fixture-`Config`-builder convention",
    "source": "`backend/src/auth/dev_bypass.rs:18-56` (`dev_loopback_config()` helper), `backend/src/db/mod.rs:98-121` (`TempDb`).",
    "applyTo": "every new `backend/tests/*.rs` integration file and any new `#[cfg(test)]` module inside `auth/session.rs`/`ratelimit/mod.rs`.",
    "rule": null,
    "excerpts": 0
   }
  ],
  "other": [],
  "scope": "`backend/src/auth/`, `backend/src/tickets/`, `backend/src/api/`, `backend/src/db/`, `backend/migrations/`, `backend/src/main.rs`, `backend/src/lib.rs`, `frontend/components/`, `frontend/app/`",
  "scanned": "`auth/mod.rs`, `auth/dev_bypass.rs`, `tickets/store.rs`, `api/audit.rs`, `db/mod.rs`, `migrations/0002_jobs_and_audit.sql`, `main.rs`, `lib.rs`, `nav-shell.tsx`, `send-to-dialog.tsx`",
  "lines": 342
 },
 "lb05": {
  "project": "labelore",
  "label": "labelore 05 (clean)",
  "file": "05-PATTERNS.md",
  "phase": "5",
  "title": "Per-Type Document Views",
  "mapped": "2026-09-20",
  "filesAnalyzed": "17 (new + modified)",
  "analogsFound": "17 / 17",
  "preNotes": [
   "All analog paths below were verified with `git ls-files` — every one is tracked source, none are\ngitignored mirrors."
  ],
  "files": [
   {
    "file": "`src/rendering/section-projection.ts` (NEW)",
    "group": null,
    "role": "utility (extractor)",
    "flow": "transform",
    "analog": "`src/planning-repo/handlers/markdown-sections.ts` + `src/rendering/frontmatter-views.ts`",
    "q": "role",
    "qNote": "composition of two shipped analogs"
   },
   {
    "file": "`src/web/views/registry.ts` (NEW)",
    "group": null,
    "role": "provider/store (registry)",
    "flow": "transform",
    "analog": "`src/planning-repo/handlers/index.ts` (`HANDLERS`) + `src/rendering/frontmatter-views.ts` (`FRONTMATTER_PANEL_BUILDERS`)",
    "q": "exact",
    "qNote": "structural mirror, explicitly named in CONTEXT.md"
   },
   {
    "file": "`src/web/views/discussion-log.tsx` (NEW)",
    "group": null,
    "role": "component",
    "flow": "transform",
    "analog": "`src/web/pages/artifact-page.tsx` (`MetadataPanel`/`ValueView`)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`src/web/views/verification.tsx` (NEW)",
    "group": null,
    "role": "component",
    "flow": "transform",
    "analog": "`src/web/pages/artifact-page.tsx` (`MetadataPanel`, `.metadata-list` dt/dd usage)",
    "q": "exact",
    "qNote": "frontmatter projection, zero new parsing"
   },
   {
    "file": "`src/web/views/plan.tsx` (NEW)",
    "group": null,
    "role": "component",
    "flow": "transform",
    "analog": "`src/rendering/markdown.ts` (`planSectionOpen`, `PLAN_ATTRIBUTE_NAMES`)",
    "q": "exact",
    "qNote": "tag projection, zero new parsing"
   },
   {
    "file": "`src/web/views/generic-fallback.tsx` (NEW, VIEW-06)",
    "group": null,
    "role": "component",
    "flow": "transform",
    "analog": "`src/presentation/tree.ts` (`unknownKind`, dead field) + `src/web/components/empty-state.tsx`",
    "q": "role",
    "qNote": "no live analog; see No Analog Found"
   },
   {
    "file": "`src/web/views/*.tsx` (12 remaining manifests: research, patterns, ui-spec, uat, validation, security, ui-review, coverage, learnings, context, summary, review, milestone-audit)",
    "group": null,
    "role": "component",
    "flow": "transform",
    "analog": "`src/rendering/section-projection.ts` (own new extractor) + `src/web/pages/artifact-page.tsx` (`MetadataPanel`)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`src/web/pages/artifact-page.tsx` (MODIFIED — dispatch to registry, wire `structured`, outline rebuild)",
    "group": null,
    "role": "component (page)",
    "flow": "request-response",
    "analog": "itself (existing file, extended not replaced)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`src/web/components/document-view-toggle.tsx` (NEW, D-01/D-03)",
    "group": null,
    "role": "component",
    "flow": "event-driven (local UI state)",
    "analog": "`src/web/components/ui/button.tsx` + `src/web/pages/plan-pair-page.tsx` (`plan-pair-jumps` slot usage inside `ArtifactHeader` children)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`src/web/components/document-outline.tsx` (NEW/extracted from `artifact-page.tsx`, D-11/D-12/D-13)",
    "group": null,
    "role": "component",
    "flow": "event-driven (IntersectionObserver)",
    "analog": "`src/web/pages/artifact-page.tsx` (`DocumentOutline`, existing) + `src/web/components/reference-preview.tsx` (Popover usage)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`src/planning-repo/mentions.ts` (MODIFIED — add `warning` `ID_PATTERNS` scheme)",
    "group": null,
    "role": "utility (scanner)",
    "flow": "transform",
    "analog": "itself (existing `decision`/`requirement`/`plan`/`phase` schemes)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`src/presentation/references.ts` (MODIFIED — add `decision`/`warning` to `ReferencePreviewType`, new preview builders)",
    "group": null,
    "role": "service",
    "flow": "transform",
    "analog": "itself (`requirementPreview`/`phasePreview`/`planPreview`, existing)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`src/rendering/linkify.ts` (MODIFIED — no change expected, consumes `references.ts` output)",
    "group": null,
    "role": "utility (rehype plugin)",
    "flow": "transform",
    "analog": "itself (unchanged pattern, `resolvePresentationReference` call site)",
    "q": "exact",
    "qNote": null
   },
   {
    "file": "`src/planning-repo/decisions-registry.ts` / `src/planning-repo/warnings-registry.ts` (NEW, per-phase D-XX/WR-XX extraction)",
    "group": null,
    "role": "service",
    "flow": "batch (build-time, per snapshot)",
    "analog": "`src/planning-repo/handlers/context.ts` (`extractTag`, tag-scanning regex discipline)",
    "q": "role",
    "qNote": null
   },
   {
    "file": "`docs/design-language.md` (NEW, D-07)",
    "group": null,
    "role": "config/doc",
    "flow": "—",
    "analog": "n/a (new doc; content seeded from `05-UI-SPEC.md` § Existing Shared Vocabulary)",
    "q": "none",
    "qNote": "net-new"
   },
   {
    "file": "`test/web/class-vocabulary.test.ts` (NEW, D-08)",
    "group": null,
    "role": "test",
    "flow": "batch (source-scan)",
    "analog": "`test/web/css-source-order.test.ts` + `test/web/visual-contract.test.ts`",
    "q": "exact",
    "qNote": "same text-scan idiom"
   },
   {
    "file": "`test/rendering/section-projection.test.ts` (NEW)",
    "group": null,
    "role": "test",
    "flow": "transform",
    "analog": "`test/handlers.test.ts` (pure-function assertions over `ParsedArtifact`)",
    "q": "role",
    "qNote": null
   }
  ],
  "noAnalog": [
   {
    "file": "`src/web/views/generic-fallback.tsx`",
    "reason": "VIEW-06's \"visibly marked unrecognized\" has no rendering analog anywhere in the codebase — `unknownKind` (`src/presentation/tree.ts:171`) is computed and tested but never rendered (RESEARCH.md Pitfall 1, confirmed by grep). Build from `EmptyState`'s neutral-tone philosophy and the `.notice` block pattern, not from an existing unrecognized-type UI, because none exists."
   },
   {
    "file": "`docs/design-language.md`",
    "reason": "Net-new document; no prior design-language doc exists in this repo (`.claude/CLAUDE.md` § Conventions currently reads \"not yet established\"). Content is compiled from `05-UI-SPEC.md` § Existing Shared Vocabulary, not copied from another file."
   },
   {
    "file": "`src/planning-repo/decisions-registry.ts` / `warnings-registry.ts`",
    "reason": "No file in `src/presentation/` or `src/rendering/` currently builds a decision- or warning-keyed lookup map (RESEARCH.md Pitfall 2, confirmed by grep for `decisionsOf`/`extractDecision`/`WR-` extraction logic). `context.ts`'s `extractTag` is the closest structural precedent (tag-scanning discipline) but extracts a whole tag body, not per-bullet/per-heading entries — the per-entry split is new parsing work."
   }
  ],
  "noAIntro": null,
  "assignments": [
   {
    "heading": "`src/rendering/section-projection.ts` (utility, transform)",
    "targets": [
     "src/rendering/section-projection.ts"
    ],
    "tail": "(utility, transform)",
    "analog": "`src/planning-repo/handlers/markdown-sections.ts` (primitives to compose) and `src/rendering/frontmatter-views.ts` (registry/builder shape to mirror).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "A sibling `SECTION_PROJECTION_EXTRACTORS`-style table, keyed by `artifact.kind`, follows this\nexact frozen-array-of-`{key, label, build}` shape (per RESEARCH.md's own recommendation).",
     "**Error handling pattern:** none of the three composed primitives throw — `splitSections` on a\nmalformed body returns `[]`; `parseMarkdownTable` on <2 table lines returns `[]`. The extractor\nmust preserve this \"degrade to empty, never throw\" contract so D-06 (silent omission) holds\nstructurally, not via a try/catch wrapper."
    ],
    "excerpts": 4
   },
   {
    "heading": "`src/web/views/registry.ts` (provider/store, transform)",
    "targets": [
     "src/web/views/registry.ts"
    ],
    "tail": "(provider/store, transform)",
    "analog": "`src/planning-repo/handlers/index.ts` (ordered registry shape) — note this is a **structural** analog only; the new registry dispatches on the already-granular `artifact.kind` wire value (see RESEARCH.md's \"Corrected Understanding\"), not on `ArtifactHandler.kind`.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Mirror this exactly: a keyed lookup (map or array) from `artifact.kind` string to a view manifest,\nwith an unconditional fallback entry (VIEW-06's speculative structural view) — the client-side\nequivalent of `GenericMarkdownHandler`'s \"match: () => true, MUST stay last/default\" contract.",
     "**Manifest promotion-order contract (D-04):** the registry entry for each kind must expose an\nordered list of \"promoted\" keys (fields or sections) — this list is *both* the render order and,\nper D-11, the outline's data source. Do not let the manifest and the outline diverge into two\nlists."
    ],
    "excerpts": 2
   },
   {
    "heading": "`src/web/views/verification.tsx` (component, transform — VIEW-03)",
    "targets": [
     "src/web/views/verification.tsx"
    ],
    "tail": "(component, transform — VIEW-03)",
    "analog": "`src/planning-repo/handlers/frontmatter-only.ts` (parse-side confirmation `human_verification[]` is already on `artifact.frontmatter`, zero handler work) + `src/web/pages/artifact-page.tsx` `MetadataPanel`/`ValueView` (dt/dd rendering pattern to reuse).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Per 05-UI-SPEC.md §4, the VERIFICATION view reuses `.metadata-list` dt/dd styling directly (Check\n/ Expected / Why a person rows) rather than inventing a bespoke card — this is the same\n`<dl>`/`<dt>`/`<dd>` shape as `ValueView`'s record branch above.",
     "**Silent-omission pattern (D-06, field-level, per UI-SPEC §4):** a check missing `expected` or\n`why_human` omits just that `dt`/`dd` pair — model this the same way `ValueView`'s record branch\nalready omits nothing but must be extended to skip `undefined` entries per key, not per whole\nrecord."
    ],
    "excerpts": 2
   },
   {
    "heading": "`src/web/views/plan.tsx` (component, transform — VIEW-04)",
    "targets": [
     "src/web/views/plan.tsx"
    ],
    "tail": "(component, transform — VIEW-04)",
    "analog": "`src/rendering/markdown.ts` (`renderPlanRange`, `planSectionOpen`, `PLAN_ATTRIBUTE_NAMES`) — the data this view needs is already computed server-side and emitted as `data-plan-*` attributes.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Per RESEARCH.md Pattern 3, prefer extracting the same segment tree from `segmentPlanBody` output\n(imported in `markdown.ts` from `./plan-segments.ts`) over scraping the rendered HTML's `data-*`\nattributes — cleaner, and avoids a second parse of already-produced HTML."
    ],
    "excerpts": 1
   },
   {
    "heading": "`src/web/views/discussion-log.tsx` (component, transform — VIEW-02 proof case)",
    "targets": [
     "src/web/views/discussion-log.tsx"
    ],
    "tail": "(component, transform — VIEW-02 proof case)",
    "analog": "`src/rendering/section-projection.ts` (own new extractor, above) for data, and `src/web/pages/artifact-page.tsx` for the `.section-heading.compact` / `.status-chip` shared vocabulary usage pattern.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Per 05-UI-SPEC.md §3, the chosen-option chip is `data-tone=\"active\"` (accent-tinted), not\n`destructive`/`warning` — same component (`status-chip`), different tone value; do not invent a\nnew chip class for this state."
    ],
    "excerpts": 1
   },
   {
    "heading": "`src/web/views/generic-fallback.tsx` (component, transform — VIEW-06)",
    "targets": [
     "src/web/views/generic-fallback.tsx"
    ],
    "tail": "(component, transform — VIEW-06)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**No live analog exists — this is genuinely new UI, confirmed by RESEARCH.md's Pitfall 1.**\n`unknownKind` is computed but never rendered anywhere in the codebase:",
     "A full-repo grep of `unknownKind` outside this computation site and its one test\n(`test/presentation/tree.test.ts:198`) returns nothing — no CSS rule, no conditional render.\nBudget this view as new work, not a wiring task."
    ],
    "excerpts": 2
   },
   {
    "heading": "`src/web/components/document-view-toggle.tsx` (component, event-driven — D-01/D-03)",
    "targets": [
     "src/web/components/document-view-toggle.tsx"
    ],
    "tail": "(component, event-driven — D-01/D-03)",
    "analog": "`src/web/components/ui/button.tsx` (variant/size system) + `src/web/pages/plan-pair-page.tsx` (the exact `ArtifactHeader` `children` slot this toggle occupies, precedent already established by `plan-pair-jumps`).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "`ArtifactHeader`'s own doc comment (source: `src/web/components/artifact-header.tsx:10-18`)\nconfirms `children` \"render last inside the header\" — this is exactly where the new\n`document-view-toggle.tsx` mounts for every per-type view page.",
     "Per 05-UI-SPEC.md §1: active = `variant=\"secondary\"` + `aria-pressed=\"true\"`; inactive =\n`variant=\"ghost\"` + `aria-pressed=\"false\"`; both at `size=\"xs\"`."
    ],
    "excerpts": 2
   },
   {
    "heading": "`src/web/components/document-outline.tsx` (component, event-driven — D-11/D-12/D-13)",
    "targets": [
     "src/web/components/document-outline.tsx"
    ],
    "tail": "(component, event-driven — D-11/D-12/D-13)",
    "analog": "`src/web/pages/artifact-page.tsx` `DocumentOutline` (existing, to be extended/moved) + `src/web/components/reference-preview.tsx` (`Popover` usage pattern for the narrow-width overlay).",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Per D-11, swap the data source from `document.headings` to the view registry's promoted-section\nlist (plus the D-02 remainder as a final entry) — the `<nav className=\"document-outline\">` /\n`<ol>`/`<li>`/`<a>` markup shape itself carries over unchanged.",
     "Per 05-UI-SPEC.md §7, the new `.document-outline-trigger` popup content reuses the *same*\n`.document-outline` `<ol>` markup shown above — do not duplicate the list styling into a second\nclass."
    ],
    "excerpts": 3
   },
   {
    "heading": "`src/planning-repo/mentions.ts` (utility/scanner, transform — BACK-02, `warning` scheme)",
    "targets": [
     "src/planning-repo/mentions.ts"
    ],
    "tail": "(utility/scanner, transform — BACK-02,  scheme)",
    "analog": "itself — the existing `decision` scheme is the direct sibling the new `warning` scheme must match in form and precedence discipline.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "A `warning: /\\bWR-\\d+\\b/g`-shaped entry (mirroring `decision`'s exact bounded-quantifier,\nword-boundary shape) must be inserted **before** `requirement` in object literal order — insertion\norder is the tie-break in `collectRawMatches`'s stable sort (source:\n`src/planning-repo/mentions.ts:169-172`, `candidates.sort(...)` — longer match wins at equal\nstart, otherwise earliest `Object.keys(ID_PATTERNS)` iteration order wins), and `WR-01` currently\nfalls to `requirement`'s `/\\b[A-Z][A-Z0-9]+-\\d{2,}\\b/g` since it has 2+ leading uppercase letters.",
     "**Bounded-quantifier / ReDoS discipline to match (V5, ASVS):** every existing pattern is\nword-boundary-anchored with bounded quantifiers (`\\d{2,}`, `\\d+`) — no nested unbounded groups.\nThe new `warning` pattern must satisfy the identical shape and run through the existing\n`stripCodeForScanning` pass (source: `src/planning-repo/mentions.ts:66-68`) exactly as every\nexisting scheme does — no new call site should skip it."
    ],
    "excerpts": 1
   },
   {
    "heading": "`src/presentation/references.ts` (service, transform — BACK-02 preview builders)",
    "targets": [
     "src/presentation/references.ts"
    ],
    "tail": "(service, transform — BACK-02 preview builders)",
    "analog": "itself — `requirementPreview`/`phasePreview`/`planPreview` are the direct shape new `decisionPreview`/`warningPreview` functions must follow.",
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "Add `'decision' | 'warning'`.",
     "Per D-15, the new `decision`/`warning` previews' `detail` field carries \"the decision's own\nstatement or the warning's finding title, plus which phase defines it\" — exactly the\n`{ label, value }` pair shape above, reused verbatim."
    ],
    "excerpts": 4
   },
   {
    "heading": "`docs/design-language.md` (config/doc, D-07) and `test/web/class-vocabulary.test.ts` (test, D-08)",
    "targets": [
     "docs/design-language.md"
    ],
    "tail": "(config/doc, D-07) and  (test, D-08)",
    "analog": null,
    "applyTo": null,
    "useInstead": null,
    "guidance": [
     "**No code analog for the doc itself** — its content is the seed list already compiled in\n`05-UI-SPEC.md` § \"Existing Shared Vocabulary\" (17 rows: `.page-stack`, `.eyebrow`,\n`.section-heading`, `.status-chip[data-tone]`, `.empty-note`/`.empty-flow`, `.quiet-state`,\n`.notice`, `.source-note`/`.source-link`, `.artifact-metadata`, `.metadata-panel`/`.metadata-record`/\n`.metadata-list`, `.document-outline`, `.history-*`, `.roadmap-loading`/`.search-group-label`) plus\nthe reserved `view-<kind>-*` namespace regex `^view-[a-z-]+-[a-z-]+$`.",
     "`class-vocabulary.test.ts` follows this exact shape: read `docs/design-language.md` for the\nallowlist, then regex-scan `className=\"...\"` literals (and the `view-<kind>-*` prefix pattern)\nacross every file in `src/web/views/`, `src/web/pages/`, `src/web/components/` — no `ts-morph`, no\n`@babel/parser`, matching the codebase's zero-AST-dependency precedent (confirmed absent from\n`package.json` devDependencies)."
    ],
    "excerpts": 1
   }
  ],
  "shared": [
   {
    "name": "Status/tone chips",
    "source": "`.status-chip[data-tone=...]`, used at `src/web/pages/artifact-page.tsx:460-469, 489-494` and `src/web/pages/plan-pair-page.tsx:202` (coverage-matrix row).",
    "applyTo": "DISCUSSION-LOG's \"Chosen\" chip (`data-tone=\"active\"`), PLAN task-index's \"Gates\" chip (`data-tone=\"active\"`), VIEW-06's \"Unrecognized type\" chip (`data-tone=\"quiet\"`) — one shared component, only the `data-tone` value differs per view. ```typescript <span className=\"status-chip\" data-tone=\"active\">Chosen</span> ```",
    "rule": null,
    "excerpts": 1
   },
   {
    "name": "Collapsed disclosure (`<details className=\"artifact-metadata\">`)",
    "source": "`src/web/pages/artifact-page.tsx:472-483` (Document metadata) and `:485-534` (warning disclosure) — both already use the identical `<details className=\"artifact-metadata\">` + `<summary>label <span>{N} count</span></summary>` shape.",
    "applyTo": "D-02's collapsed remainder (\"More in this document · {N} sections\") — same class, same summary-with-trailing-count shape, zero new CSS. ```typescript <details className=\"artifact-metadata\"> <summary>Document metadata <span>{panels.length} sections</span></summary> <div className=\"metadata-panels\" aria-label=\"Structured artifact metadata\">{/* ... */}</div> </details> ```",
    "rule": null,
    "excerpts": 1
   },
   {
    "name": "`EmptyState`/absence copy",
    "source": "`src/web/components/empty-state.tsx` (full file).",
    "applyTo": "Any view surface that needs to say nothing-is-here (VIEW-06's deepest fallback case only, per D-06 — everywhere else, absence is silent per D-06 and renders no component at all). `EMPTY_STATE_MESSAGE = 'Nothing here yet.'` — reuse verbatim, never author new absence copy.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "`ArtifactHeader` shared page-open component",
    "source": "`src/web/components/artifact-header.tsx` (full file, 60 lines) — already used identically by `artifact-page.tsx` and `plan-pair-page.tsx`.",
    "applyTo": "every one of the 17 per-type views (16 kinds + unrecognized fallback) — this component is explicitly called out in `05-UI-SPEC.md` as \"the shared document-page header every Phase 5 view reuses without modification.\" Do not fork it per view.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "`Popover` (`@base-ui/react/popover`) overlay pattern",
    "source": "`src/web/components/reference-preview.tsx:1-95` (full file).",
    "applyTo": "D-12's narrow-width outline disclosure — reuse the `Popover.Root`/`Portal`/ `Positioner`/`Popup` nesting and its `open`/`onOpenChange`/`onOpenChangeComplete` controlled-state shape rather than introducing a `<details>`-based or custom-portal alternative.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "Error handling (mention-scanner regex safety, V5/ASVS)",
    "source": "`src/planning-repo/mentions.ts:30-68` (`ID_PATTERNS` + `stripCodeForScanning`).",
    "applyTo": "the new `warning` scheme in `mentions.ts` and any regex added to `src/presentation/references.ts`'s `tokenIdentity()` (source: `references.ts:196-208`) — bounded quantifiers, word-boundary anchors, run through `stripCodeForScanning` before matching, mirroring `decision`'s exact shape.",
    "rule": null,
    "excerpts": 0
   },
   {
    "name": "rehype pipeline ordering (if any manifest ever touches the hast tree — flagged, not expected)",
    "source": "`src/rendering/markdown.ts:233-241` (`createProcessor`'s `.use()` chain). ```typescript .use(rehypeRaw) .use(rehypeSanitize, schema) .use(rehypeResolvedReferences) .use(rehypeSlug) .use(trustedEnrichment(highlighter)) .use(rehypeStringify); ```",
    "applyTo": "N/A for Phase 5's manifests directly (they operate on `structured`/`frontmatter` JSON, not the hast tree, per D-03) — documented here only because RESEARCH.md's Pitfall 4 flags it as the one ordering rule any future hast-touching addition must respect.",
    "rule": null,
    "excerpts": 1
   }
  ],
  "other": [],
  "scope": "`src/planning-repo/handlers/`, `src/rendering/`, `src/presentation/`, `src/web/pages/`, `src/web/components/`, `src/server/`, `test/web/`, `test/handlers.test.ts`.",
  "scanned": "37 (all confirmed git-tracked via `git ls-files` before citation).",
  "lines": 572
 }
};
